export const qk = {
  releases: (params: Record<string, unknown>) => ['releases', params] as const,
  releaseCount: (params: Record<string, unknown>) => ['releases', 'count', params] as const,
  release: (id: number) => ['release', id] as const,
  releasesByIds: (ids: readonly number[]) => ['releases', 'byIds', [...ids].sort()] as const,
  featuredRelease: () => ['releases', 'featured'] as const,
  releaseImage: (id: number) => ['release', id, 'image'] as const,
  releaseContentUrl: (id: number) => ['release', id, 'content-url'] as const,
  likeStatus: (id: number) => ['release', id, 'like'] as const,
  comments: (id: number, page: number) => ['release', id, 'comments', page] as const,
  myProjects: (params: Record<string, unknown>) => ['projects', 'mine', params] as const,
  project: (id: number) => ['project', id] as const,
  projectImage: (id: number) => ['project', id, 'image'] as const,
  publicProfile: (username: string) => ['user', username] as const,
  userGames: (id: number, kind: 'published' | 'liked') => ['user', id, kind] as const,
};
