// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape
} from "./client";
import { client } from "./client.gen";
import type {
  AuthControllerLoginData,
  AuthControllerLoginErrors,
  AuthControllerLoginResponses,
  AuthControllerLoginWithGoogleData,
  AuthControllerLoginWithGoogleErrors,
  AuthControllerLoginWithGoogleResponses,
  AuthControllerLogoutData,
  AuthControllerLogoutResponses,
  AuthControllerRefreshData,
  AuthControllerRefreshErrors,
  AuthControllerRefreshResponses,
  AuthControllerRegisterData,
  AuthControllerRegisterErrors,
  AuthControllerRegisterResponses,
  MultiplayerControllerCloseHostData,
  MultiplayerControllerCloseHostErrors,
  MultiplayerControllerCloseHostResponses,
  MultiplayerControllerJoinHostData,
  MultiplayerControllerJoinHostErrors,
  MultiplayerControllerJoinHostResponses,
  MultiplayerControllerLeaveHostData,
  MultiplayerControllerLeaveHostErrors,
  MultiplayerControllerLeaveHostResponses,
  MultiplayerControllerLookupHostsData,
  MultiplayerControllerLookupHostsErrors,
  MultiplayerControllerLookupHostsResponses,
  MultiplayerControllerOpenHostData,
  MultiplayerControllerOpenHostErrors,
  MultiplayerControllerOpenHostResponses,
  ProjectControllerAddCollaboratorData,
  ProjectControllerAddCollaboratorErrors,
  ProjectControllerAddCollaboratorResponses,
  ProjectControllerCreateData,
  ProjectControllerCreateErrors,
  ProjectControllerCreateResponses,
  ProjectControllerDeleteCheckpointData,
  ProjectControllerDeleteCheckpointErrors,
  ProjectControllerDeleteCheckpointResponses,
  ProjectControllerFetchProjectContentData,
  ProjectControllerFetchProjectContentErrors,
  ProjectControllerFetchProjectContentResponses,
  ProjectControllerFindAllData,
  ProjectControllerFindAllErrors,
  ProjectControllerFindAllResponses,
  ProjectControllerFindOneData,
  ProjectControllerFindOneErrors,
  ProjectControllerFindOneResponses,
  ProjectControllerGetAllReleasesData,
  ProjectControllerGetAllReleasesResponses,
  ProjectControllerGetCheckpointData,
  ProjectControllerGetCheckpointErrors,
  ProjectControllerGetCheckpointResponses,
  ProjectControllerGetCheckpointsData,
  ProjectControllerGetCheckpointsErrors,
  ProjectControllerGetCheckpointsResponses,
  ProjectControllerGetProjectImageData,
  ProjectControllerGetProjectImageErrors,
  ProjectControllerGetProjectImageResponses,
  ProjectControllerGetReleaseContentData,
  ProjectControllerGetReleaseContentResponses,
  ProjectControllerGetReleaseContentUrlData,
  ProjectControllerGetReleaseContentUrlResponses,
  ProjectControllerGetReleaseData,
  ProjectControllerGetReleaseResponses,
  ProjectControllerGetVersionData,
  ProjectControllerGetVersionErrors,
  ProjectControllerGetVersionResponses,
  ProjectControllerGetVersionsData,
  ProjectControllerGetVersionsErrors,
  ProjectControllerGetVersionsResponses,
  ProjectControllerPublishData,
  ProjectControllerPublishErrors,
  ProjectControllerPublishResponses,
  ProjectControllerRemoveCollaboratorData,
  ProjectControllerRemoveCollaboratorErrors,
  ProjectControllerRemoveCollaboratorResponses,
  ProjectControllerRemoveData,
  ProjectControllerRemoveErrors,
  ProjectControllerRemoveResponses,
  ProjectControllerSaveCheckpointData,
  ProjectControllerSaveCheckpointErrors,
  ProjectControllerSaveCheckpointResponses,
  ProjectControllerSaveProjectContentData,
  ProjectControllerSaveProjectContentErrors,
  ProjectControllerSaveProjectContentResponses,
  ProjectControllerUnpublishData,
  ProjectControllerUnpublishErrors,
  ProjectControllerUnpublishResponses,
  ProjectControllerUpdateData,
  ProjectControllerUpdateErrors,
  ProjectControllerUpdateResponses,
  ProjectControllerUploadProjectImageData,
  ProjectControllerUploadProjectImageErrors,
  ProjectControllerUploadProjectImageResponses,
  UserControllerFindAllData,
  UserControllerFindAllErrors,
  UserControllerFindAllResponses,
  UserControllerFindOneData,
  UserControllerFindOneErrors,
  UserControllerFindOneResponses,
  UserControllerGetProfileData,
  UserControllerGetProfileErrors,
  UserControllerGetProfilePictureData,
  UserControllerGetProfilePictureErrors,
  UserControllerGetProfilePictureResponses,
  UserControllerGetProfileResponses,
  UserControllerRemoveData,
  UserControllerRemoveErrors,
  UserControllerRemoveResponses,
  UserControllerUpdateData,
  UserControllerUpdateErrors,
  UserControllerUpdateResponses,
  UserControllerUploadProfilePictureData,
  UserControllerUploadProfilePictureErrors,
  UserControllerUploadProfilePictureResponses,
  WorkSessionControllerGetInfoData,
  WorkSessionControllerGetInfoErrors,
  WorkSessionControllerGetInfoResponses,
  WorkSessionControllerJoinData,
  WorkSessionControllerJoinErrors,
  WorkSessionControllerJoinResponses,
  WorkSessionControllerKickData,
  WorkSessionControllerKickErrors,
  WorkSessionControllerKickResponses,
  WorkSessionControllerLeaveData,
  WorkSessionControllerLeaveErrors,
  WorkSessionControllerLeaveResponses
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all released projects
 */
export const projectControllerGetAllReleases = <
  ThrowOnError extends boolean = false
>(
  options?: Options<ProjectControllerGetAllReleasesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ProjectControllerGetAllReleasesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/releases",
    ...options
  });

/**
 * Get project release version
 */
export const projectControllerGetRelease = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerGetReleaseData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerGetReleaseResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/releases/{id}",
    ...options
  });

/**
 * Get project release version
 */
export const projectControllerGetReleaseContent = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerGetReleaseContentData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerGetReleaseContentResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "blob",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/releases/{id}/content",
    ...options
  });

/**
 * Get signed CDN URL for a release
 */
export const projectControllerGetReleaseContentUrl = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerGetReleaseContentUrlData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerGetReleaseContentUrlResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/releases/{id}/content-url",
    ...options
  });

/**
 * Retrieve the list of projects
 */
export const projectControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectControllerFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ProjectControllerFindAllResponses,
    ProjectControllerFindAllErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects",
    ...options
  });

/**
 * Create a new project
 */
export const projectControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ProjectControllerCreateResponses,
    ProjectControllerCreateErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Delete a project
 */
export const projectControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerRemoveData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ProjectControllerRemoveResponses,
    ProjectControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}",
    ...options
  });

/**
 * Retrieve a single project
 */
export const projectControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerFindOneData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerFindOneResponses,
    ProjectControllerFindOneErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}",
    ...options
  });

/**
 * Update an existing project
 */
export const projectControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerUpdateData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ProjectControllerUpdateResponses,
    ProjectControllerUpdateErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Add a new collaborator
 *
 * Add a collaborator to a project by providing either userId, username, or email. At least one must be provided.
 */
export const projectControllerAddCollaborator = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerAddCollaboratorData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    ProjectControllerAddCollaboratorResponses,
    ProjectControllerAddCollaboratorErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/add-collaborator",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Remove a collaborator
 *
 * Remove a collaborator from a project by providing either userId, username, or email. At least one must be provided.
 */
export const projectControllerRemoveCollaborator = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerRemoveCollaboratorData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ProjectControllerRemoveCollaboratorResponses,
    ProjectControllerRemoveCollaboratorErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/remove-collaborator",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Save project's content (Upload)
 */
export const projectControllerSaveProjectContent = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerSaveProjectContentData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    ProjectControllerSaveProjectContentResponses,
    ProjectControllerSaveProjectContentErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/saveContent",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers
    }
  });

/**
 * Get signed CDN access to project image
 */
export const projectControllerGetProjectImage = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerGetProjectImageData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerGetProjectImageResponses,
    ProjectControllerGetProjectImageErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/image",
    ...options
  });

/**
 * Upload project image
 */
export const projectControllerUploadProjectImage = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerUploadProjectImageData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ProjectControllerUploadProjectImageResponses,
    ProjectControllerUploadProjectImageErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/image",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers
    }
  });

/**
 * Fetch project's content
 */
export const projectControllerFetchProjectContent = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerFetchProjectContentData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerFetchProjectContentResponses,
    ProjectControllerFetchProjectContentErrors,
    ThrowOnError
  >({
    responseType: "blob",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/fetchContent",
    ...options
  });

/**
 * Save project's checkpoint
 */
export const projectControllerSaveCheckpoint = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerSaveCheckpointData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ProjectControllerSaveCheckpointResponses,
    ProjectControllerSaveCheckpointErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/saveCheckpoint/{name}",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers
    }
  });

/**
 * Delete project's checkpoint
 */
export const projectControllerDeleteCheckpoint = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerDeleteCheckpointData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ProjectControllerDeleteCheckpointResponses,
    ProjectControllerDeleteCheckpointErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/deleteCheckpoint/{name}",
    ...options
  });

/**
 * Publish project
 */
export const projectControllerPublish = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerPublishData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ProjectControllerPublishResponses,
    ProjectControllerPublishErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/publish",
    ...options
  });

/**
 * Unpublish project
 */
export const projectControllerUnpublish = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerUnpublishData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ProjectControllerUnpublishResponses,
    ProjectControllerUnpublishErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/unpublish",
    ...options
  });

/**
 * Get project versions
 */
export const projectControllerGetVersions = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerGetVersionsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerGetVersionsResponses,
    ProjectControllerGetVersionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/versions",
    ...options
  });

/**
 * Get project checkpoints
 */
export const projectControllerGetCheckpoints = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerGetCheckpointsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerGetCheckpointsResponses,
    ProjectControllerGetCheckpointsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/checkpoints",
    ...options
  });

/**
 * Fetch a project version
 */
export const projectControllerGetVersion = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerGetVersionData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerGetVersionResponses,
    ProjectControllerGetVersionErrors,
    ThrowOnError
  >({
    responseType: "blob",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/versions/{version}",
    ...options
  });

/**
 * Fetch a project checkpoint
 */
export const projectControllerGetCheckpoint = <
  ThrowOnError extends boolean = false
>(
  options: Options<ProjectControllerGetCheckpointData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectControllerGetCheckpointResponses,
    ProjectControllerGetCheckpointErrors,
    ThrowOnError
  >({
    responseType: "blob",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects/{id}/checkpoints/{checkpoint}",
    ...options
  });

/**
 * List available game hosts/sessions from the user's perspective
 */
export const multiplayerControllerLookupHosts = <
  ThrowOnError extends boolean = false
>(
  options?: Options<MultiplayerControllerLookupHostsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    MultiplayerControllerLookupHostsResponses,
    MultiplayerControllerLookupHostsErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/multiplayer/list-hosts",
    ...options
  });

/**
 * Open a new game host/session, with the caller being the game host
 */
export const multiplayerControllerOpenHost = <
  ThrowOnError extends boolean = false
>(
  options: Options<MultiplayerControllerOpenHostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    MultiplayerControllerOpenHostResponses,
    MultiplayerControllerOpenHostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/multiplayer/open-host",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Close an existing game host/session, with the caller being the game host
 */
export const multiplayerControllerCloseHost = <
  ThrowOnError extends boolean = false
>(
  options: Options<MultiplayerControllerCloseHostData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    MultiplayerControllerCloseHostResponses,
    MultiplayerControllerCloseHostErrors,
    ThrowOnError
  >({
    url: "/multiplayer/close-host",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Join an existing game host/session as a player
 */
export const multiplayerControllerJoinHost = <
  ThrowOnError extends boolean = false
>(
  options: Options<MultiplayerControllerJoinHostData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    MultiplayerControllerJoinHostResponses,
    MultiplayerControllerJoinHostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/multiplayer/join-host",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Leave a game host/session as a player
 */
export const multiplayerControllerLeaveHost = <
  ThrowOnError extends boolean = false
>(
  options: Options<MultiplayerControllerLeaveHostData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    MultiplayerControllerLeaveHostResponses,
    MultiplayerControllerLeaveHostErrors,
    ThrowOnError
  >({
    url: "/multiplayer/leave-host",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Authenticate a user and return an access token
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthControllerLoginResponses,
    AuthControllerLoginErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Register a new user and return an access token
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRegisterData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthControllerRegisterResponses,
    AuthControllerRegisterErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Authenticate with Google OAuth token
 */
export const authControllerLoginWithGoogle = <
  ThrowOnError extends boolean = false
>(
  options: Options<AuthControllerLoginWithGoogleData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthControllerLoginWithGoogleResponses,
    AuthControllerLoginWithGoogleErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/google",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Refresh the access token using refresh token cookie
 */
export const authControllerRefresh = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerRefreshData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthControllerRefreshResponses,
    AuthControllerRefreshErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/refresh",
    ...options
  });

/**
 * Remove refresh token cookie
 */
export const authControllerLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerLogoutData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthControllerLogoutResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/logout",
    ...options
  });

/**
 * Get current user profile
 */
export const userControllerGetProfile = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerGetProfileData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    UserControllerGetProfileResponses,
    UserControllerGetProfileErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/profile",
    ...options
  });

/**
 * Get signed CDN access to a user's profile picture
 */
export const userControllerGetProfilePicture = <
  ThrowOnError extends boolean = false
>(
  options: Options<UserControllerGetProfilePictureData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UserControllerGetProfilePictureResponses,
    UserControllerGetProfilePictureErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}/profile-picture",
    ...options
  });

/**
 * Upload a user's profile picture
 */
export const userControllerUploadProfilePicture = <
  ThrowOnError extends boolean = false
>(
  options: Options<UserControllerUploadProfilePictureData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UserControllerUploadProfilePictureResponses,
    UserControllerUploadProfilePictureErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}/profile-picture",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers
    }
  });

/**
 * Get all users with pagination and filtering
 */
export const userControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    UserControllerFindAllResponses,
    UserControllerFindAllErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users",
    ...options
  });

/**
 * Delete a user by ID
 */
export const userControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerRemoveData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    UserControllerRemoveResponses,
    UserControllerRemoveErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options
  });

/**
 * Get a user by ID
 */
export const userControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerFindOneData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UserControllerFindOneResponses,
    UserControllerFindOneErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options
  });

/**
 * Update a user by ID
 */
export const userControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UserControllerUpdateResponses,
    UserControllerUpdateErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Join a work session
 */
export const workSessionControllerJoin = <ThrowOnError extends boolean = false>(
  options: Options<WorkSessionControllerJoinData, ThrowOnError>
) =>
  (options.client ?? client).post<
    WorkSessionControllerJoinResponses,
    WorkSessionControllerJoinErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/work-sessions/join/{id}",
    ...options
  });

/**
 * Leave a work session
 */
export const workSessionControllerLeave = <
  ThrowOnError extends boolean = false
>(
  options: Options<WorkSessionControllerLeaveData, ThrowOnError>
) =>
  (options.client ?? client).post<
    WorkSessionControllerLeaveResponses,
    WorkSessionControllerLeaveErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/work-sessions/leave/{id}",
    ...options
  });

/**
 * Kick user from work session
 */
export const workSessionControllerKick = <ThrowOnError extends boolean = false>(
  options: Options<WorkSessionControllerKickData, ThrowOnError>
) =>
  (options.client ?? client).post<
    WorkSessionControllerKickResponses,
    WorkSessionControllerKickErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/work-sessions/kick/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });

/**
 * Get work session info
 */
export const workSessionControllerGetInfo = <
  ThrowOnError extends boolean = false
>(
  options: Options<WorkSessionControllerGetInfoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    WorkSessionControllerGetInfoResponses,
    WorkSessionControllerGetInfoErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/work-sessions/info/{id}",
    ...options
  });
