// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string;
};

export type ProjectResponseDto = {
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: "IN_PROGRESS" | "COMPLETED" | "ARCHIVED";
  /**
   * The monetization strategy for this project
   */
  monetization: "NONE" | "ADS" | "PAID";
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
};

export type SignedUrlResponseDto = {
  /**
   * The signed CloudFront URL for accessing the protected file
   */
  signedUrl: string;
};

export type UserBasicInfoDto = {
  /**
   * The unique identifier of the user
   */
  id: number;
  /**
   * The username
   */
  username: string;
  /**
   * The email address
   */
  email: string;
};

export type ProjectExResponseDto = {
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: "IN_PROGRESS" | "COMPLETED" | "ARCHIVED";
  /**
   * The monetization strategy for this project
   */
  monetization: "NONE" | "ADS" | "PAID";
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The users collaborating on this project
   */
  collaborators: Array<UserBasicInfoDto>;
  /**
   * The creator of this project
   */
  creator: UserBasicInfoDto;
};

export type CreateProjectDto = {
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * URL to the project icon
   */
  iconUrl?: string;
};

export type UpdateProjectDto = {
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc?: {
    [key: string]: unknown;
  };
  /**
   * URL to the project icon
   */
  iconUrl?: string;
  /**
   * Project status
   */
  status?: "IN_PROGRESS" | "COMPLETED" | "ARCHIVED";
  /**
   * Monetization type
   */
  monetization?: "NONE" | "ADS" | "PAID";
  /**
   * The price of the project
   */
  price?: number;
};

export type AddCollaboratorDto = {
  /**
   * User ID of the user to add as collaborator
   */
  userId?: number;
  /**
   * Username of the user to add as collaborator
   */
  username?: string;
  /**
   * Email of the user to add as collaborator
   */
  email?: string;
};

export type RemoveCollaboratorDto = {
  /**
   * User ID of the user to remove as collaborator
   */
  userId?: number;
  /**
   * Username of the user to remove as collaborator
   */
  username?: string;
  /**
   * Email of the user to remove as collaborator
   */
  email?: string;
};

export type ImageUrlResponseDto = {
  /**
   * The public CDN URL for the image
   */
  url: string;
};

export type LookupHostsResponseDtoHost = {
  sessionUuid: string;
  sessionVisibility: "PUBLIC" | "FRIENDS_ONLY" | "PRIVATE";
  playerCount: number;
};

export type LookupHostsResponseDto = {
  hosts: Array<LookupHostsResponseDtoHost>;
};

export type OpenHostRequestDto = {
  projectId: number;
  visibility: "PUBLIC" | "FRIENDS_ONLY" | "PRIVATE";
};

export type WebRtcOfferPeerIceServerConfig = {
  urls: string;
  username?: {
    [key: string]: unknown;
  };
  credentials?: {
    [key: string]: unknown;
  };
};

export type WebRtcOfferPeerOptsConfig = {
  iceServers: Array<WebRtcOfferPeerIceServerConfig>;
};

export type WebRtcOfferPeerOpts = {
  config: WebRtcOfferPeerOptsConfig;
};

export type WebRtcOfferDto = {
  signaling: string;
  maxConns: number;
  peerOpts: WebRtcOfferPeerOpts;
};

export type OpenHostResponseDto = {
  sessionUuid: string;
  webrtcConfig: WebRtcOfferDto;
};

export type CloseHostRequestDto = {
  /**
   * ID of the project whose session to close
   */
  projectId: number;
};

export type JoinHostRequestDto = {
  sessionUuid: string;
};

export type JoinHostResponseDto = {
  webrtcConfig: WebRtcOfferDto;
};

export type LeaveHostRequestDto = {
  sessionUuid: string;
};

export type LoginDto = {
  /**
   * User email address
   */
  email: string;
  /**
   * User password
   */
  password: string;
};

export type AuthResponseDto = {
  access_token: string;
};

export type CreateUserDto = {
  /**
   * User email address
   */
  email: string;
  /**
   * User username
   */
  username: string;
  /**
   * User nick name
   */
  nickname?: string;
  /**
   * User password
   */
  password: string;
};

export type UserRoleDto = {
  /**
   * Role ID
   */
  id: number;
  /**
   * Role name
   */
  name: string;
};

export type UserResponseDto = {
  /**
   * User ID
   */
  id: number;
  /**
   * User email address
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname
   */
  nickname: string | null;
  /**
   * User roles
   */
  roles?: Array<UserRoleDto>;
  /**
   * User creation date
   */
  createdAt: string;
  /**
   * User last update date
   */
  updatedAt: string;
};

export type PaginationMetaDto = {
  /**
   * Current page number
   */
  page: number;
  /**
   * Number of items per page
   */
  limit: number;
  /**
   * Total number of items
   */
  total: number;
  /**
   * Total number of pages
   */
  totalPages: number;
};

export type UserListResponseDto = {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * List of users
   */
  data: Array<UserResponseDto>;
  /**
   * Pagination metadata
   */
  meta: PaginationMetaDto;
};

export type UserSingleResponseDto = {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * User data
   */
  data: UserResponseDto;
};

export type UserProfileResponseDto = {
  /**
   * User ID
   */
  id: number;
  /**
   * User email address
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname
   */
  nickname: string | null;
  /**
   * User roles
   */
  roles?: Array<UserRoleDto>;
  /**
   * User creation date
   */
  createdAt: string;
  /**
   * User last update date
   */
  updatedAt: string;
  /**
   * User profile message
   */
  message: string;
};

export type SignedCdnResourceDto = {
  /**
   * The CDN URL for the resource (requires signed cookies)
   */
  resourceUrl: string;
  /**
   * Signed Edge cookies (also set as HTTP-only cookies)
   */
  cookies: {
    [key: string]: unknown;
  };
};

export type UpdateUserDto = {
  /**
   * User email address
   */
  email?: string;
  /**
   * User username
   */
  username?: string;
  /**
   * User nick name
   */
  nickname?: string;
  /**
   * User password
   */
  password?: string;
};

export type KickWorkSessionDto = {
  /**
   * The ID of the user participating in the work session
   */
  userId: number;
};

export type FetchWorkSessionDto = {
  /**
   * The ID of the user participating in the work session
   */
  users: Array<string>;
  /**
   * The ID of the session's host
   */
  host: number;
  /**
   * The ID of the project this work session belongs to
   */
  project: number;
  /**
   * The date and time when the work session started
   */
  startedAt: string;
  /**
   * The ID of the room for this work session
   */
  roomId: string;
  /**
   * The password for the room of this work session
   */
  roomPassword: string;
};

export type ProjectControllerGetAllReleasesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/projects/releases";
};

export type ProjectControllerGetAllReleasesResponses = {
  /**
   * A JSON array of projects with collaborators and creator information
   */
  200: Array<ProjectResponseDto>;
};

export type ProjectControllerGetAllReleasesResponse =
  ProjectControllerGetAllReleasesResponses[keyof ProjectControllerGetAllReleasesResponses];

export type ProjectControllerGetReleaseData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}";
};

export type ProjectControllerGetReleaseResponses = {
  /**
   * Project release file
   */
  200: unknown;
};

export type ProjectControllerGetReleaseContentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}/content";
};

export type ProjectControllerGetReleaseContentResponses = {
  /**
   * Project release file
   */
  200: Blob | File;
};

export type ProjectControllerGetReleaseContentResponse =
  ProjectControllerGetReleaseContentResponses[keyof ProjectControllerGetReleaseContentResponses];

export type ProjectControllerGetReleaseContentUrlData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}/content-url";
};

export type ProjectControllerGetReleaseContentUrlResponses = {
  /**
   * Signed Edge URL for the release
   */
  200: SignedUrlResponseDto;
};

export type ProjectControllerGetReleaseContentUrlResponse =
  ProjectControllerGetReleaseContentUrlResponses[keyof ProjectControllerGetReleaseContentUrlResponses];

export type ProjectControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/projects";
};

export type ProjectControllerFindAllErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type ProjectControllerFindAllResponses = {
  /**
   * A JSON array of projects with collaborators and creator information
   */
  200: Array<ProjectExResponseDto>;
};

export type ProjectControllerFindAllResponse =
  ProjectControllerFindAllResponses[keyof ProjectControllerFindAllResponses];

export type ProjectControllerCreateData = {
  body: CreateProjectDto;
  path?: never;
  query?: never;
  url: "/projects";
};

export type ProjectControllerCreateErrors = {
  /**
   * Bad request – invalid input
   */
  400: unknown;
};

export type ProjectControllerCreateResponses = {
  /**
   * Project created successfully
   */
  201: ProjectResponseDto;
};

export type ProjectControllerCreateResponse =
  ProjectControllerCreateResponses[keyof ProjectControllerCreateResponses];

export type ProjectControllerRemoveData = {
  body?: never;
  path: {
    /**
     * Numeric ID of the project to delete
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}";
};

export type ProjectControllerRemoveErrors = {
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Error deleting project
   */
  500: unknown;
};

export type ProjectControllerRemoveResponses = {
  /**
   * Project deleted successfully (no content)
   */
  204: void;
};

export type ProjectControllerRemoveResponse =
  ProjectControllerRemoveResponses[keyof ProjectControllerRemoveResponses];

export type ProjectControllerFindOneData = {
  body?: never;
  path: {
    /**
     * Numeric ID of the project to retrieve
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}";
};

export type ProjectControllerFindOneErrors = {
  /**
   * Invalid user or project ID
   */
  403: unknown;
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type ProjectControllerFindOneResponses = {
  /**
   * Project object
   */
  200: ProjectResponseDto;
};

export type ProjectControllerFindOneResponse =
  ProjectControllerFindOneResponses[keyof ProjectControllerFindOneResponses];

export type ProjectControllerUpdateData = {
  body: UpdateProjectDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}";
};

export type ProjectControllerUpdateErrors = {
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Error updating project
   */
  500: unknown;
};

export type ProjectControllerUpdateResponses = {
  /**
   * Updated project object
   */
  200: ProjectResponseDto;
};

export type ProjectControllerUpdateResponse =
  ProjectControllerUpdateResponses[keyof ProjectControllerUpdateResponses];

export type ProjectControllerAddCollaboratorData = {
  body: AddCollaboratorDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}/add-collaborator";
};

export type ProjectControllerAddCollaboratorErrors = {
  /**
   * Bad request - no valid identifier provided
   */
  400: unknown;
  /**
   * Project or user not found
   */
  404: unknown;
  /**
   * Error Patching project
   */
  500: unknown;
};

export type ProjectControllerAddCollaboratorResponses = {
  /**
   * Updated project object with collaborators
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerAddCollaboratorResponse =
  ProjectControllerAddCollaboratorResponses[keyof ProjectControllerAddCollaboratorResponses];

export type ProjectControllerRemoveCollaboratorData = {
  body: RemoveCollaboratorDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}/remove-collaborator";
};

export type ProjectControllerRemoveCollaboratorErrors = {
  /**
   * Bad request - no valid identifier provided
   */
  400: unknown;
  /**
   * Forbidden - cannot remove project creator
   */
  403: unknown;
  /**
   * Project or user not found
   */
  404: unknown;
  /**
   * Error remove collaborator on project
   */
  500: unknown;
};

export type ProjectControllerRemoveCollaboratorResponses = {
  /**
   * Updated project object with collaborators
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerRemoveCollaboratorResponse =
  ProjectControllerRemoveCollaboratorResponses[keyof ProjectControllerRemoveCollaboratorResponses];

export type ProjectControllerSaveProjectContentData = {
  body: {
    /**
     * Project file (zip, pdf, png, etc.)
     */
    file?: Blob | File;
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/projects/{id}/saveContent";
};

export type ProjectControllerSaveProjectContentErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * File validation failed
   */
  422: unknown;
};

export type ProjectControllerSaveProjectContentResponses = {
  /**
   * File uploaded successfully
   */
  201: unknown;
};

export type ProjectControllerGetProjectImageData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/projects/{id}/image";
};

export type ProjectControllerGetProjectImageErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetProjectImageResponses = {
  /**
   * CDN URL for the project image
   */
  200: ImageUrlResponseDto;
  /**
   * Project has no image
   */
  204: void;
};

export type ProjectControllerGetProjectImageResponse =
  ProjectControllerGetProjectImageResponses[keyof ProjectControllerGetProjectImageResponses];

export type ProjectControllerUploadProjectImageData = {
  body: {
    /**
     * Project image file (JPEG, PNG, GIF, WebP)
     */
    file?: Blob | File;
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/projects/{id}/image";
};

export type ProjectControllerUploadProjectImageErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Invalid file type or size
   */
  422: unknown;
};

export type ProjectControllerUploadProjectImageResponses = {
  /**
   * Image uploaded successfully
   */
  201: unknown;
};

export type ProjectControllerGetPublishedProjectImageData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/projects/public/{id}/image";
};

export type ProjectControllerGetPublishedProjectImageErrors = {
  /**
   * Project not found, not published, or has no image
   */
  404: unknown;
};

export type ProjectControllerGetPublishedProjectImageResponses = {
  /**
   * Returns the CDN URL for the project image
   */
  200: ImageUrlResponseDto;
};

export type ProjectControllerGetPublishedProjectImageResponse =
  ProjectControllerGetPublishedProjectImageResponses[keyof ProjectControllerGetPublishedProjectImageResponses];

export type ProjectControllerFetchProjectContentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/fetchContent";
};

export type ProjectControllerFetchProjectContentErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * File not found
   */
  404: unknown;
};

export type ProjectControllerFetchProjectContentResponses = {
  /**
   * File fetched successfully
   */
  200: Blob | File;
};

export type ProjectControllerFetchProjectContentResponse =
  ProjectControllerFetchProjectContentResponses[keyof ProjectControllerFetchProjectContentResponses];

export type ProjectControllerSaveCheckpointData = {
  body: {
    file?: Blob | File;
  };
  path: {
    id: string;
    name: string;
  };
  query?: never;
  url: "/projects/{id}/saveCheckpoint/{name}";
};

export type ProjectControllerSaveCheckpointErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerSaveCheckpointResponses = {
  /**
   * File uploaded successfully
   */
  201: unknown;
};

export type ProjectControllerDeleteCheckpointData = {
  body?: never;
  path: {
    id: string;
    name: string;
  };
  query?: never;
  url: "/projects/{id}/deleteCheckpoint/{name}";
};

export type ProjectControllerDeleteCheckpointErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerDeleteCheckpointResponses = {
  /**
   * File deleted successfully
   */
  201: unknown;
};

export type ProjectControllerPublishData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/publish";
};

export type ProjectControllerPublishErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerPublishResponses = {
  /**
   * Project published successfully
   */
  201: unknown;
};

export type ProjectControllerUnpublishData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/unpublish";
};

export type ProjectControllerUnpublishErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerUnpublishResponses = {
  /**
   * Project unpublished successfully
   */
  201: unknown;
};

export type ProjectControllerGetVersionsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/versions";
};

export type ProjectControllerGetVersionsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetVersionsResponses = {
  /**
   * Project versions retrieved successfully
   */
  200: unknown;
};

export type ProjectControllerGetCheckpointsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/checkpoints";
};

export type ProjectControllerGetCheckpointsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetCheckpointsResponses = {
  /**
   * Project checkpoints retrieved successfully
   */
  200: unknown;
};

export type ProjectControllerGetVersionData = {
  body?: never;
  path: {
    id: string;
    version: string;
  };
  query?: never;
  url: "/projects/{id}/versions/{version}";
};

export type ProjectControllerGetVersionErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetVersionResponses = {
  /**
   * Project version retrieved successfully
   */
  200: Blob | File;
};

export type ProjectControllerGetVersionResponse =
  ProjectControllerGetVersionResponses[keyof ProjectControllerGetVersionResponses];

export type ProjectControllerGetCheckpointData = {
  body?: never;
  path: {
    id: string;
    checkpoint: string;
  };
  query?: never;
  url: "/projects/{id}/checkpoints/{checkpoint}";
};

export type ProjectControllerGetCheckpointErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetCheckpointResponses = {
  /**
   * Project checkpoint retrieved successfully
   */
  200: Blob | File;
};

export type ProjectControllerGetCheckpointResponse =
  ProjectControllerGetCheckpointResponses[keyof ProjectControllerGetCheckpointResponses];

export type MultiplayerControllerLookupHostsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/multiplayer/list-hosts";
};

export type MultiplayerControllerLookupHostsErrors = {
  /**
   * Bad request (wrong project ID).
   */
  400: unknown;
  /**
   * Unhandled server error.
   */
  500: unknown;
};

export type MultiplayerControllerLookupHostsResponses = {
  /**
   * A list of available game hosts is returned.
   */
  200: LookupHostsResponseDto;
};

export type MultiplayerControllerLookupHostsResponse =
  MultiplayerControllerLookupHostsResponses[keyof MultiplayerControllerLookupHostsResponses];

export type MultiplayerControllerOpenHostData = {
  body: OpenHostRequestDto;
  path?: never;
  query?: never;
  url: "/multiplayer/open-host";
};

export type MultiplayerControllerOpenHostErrors = {
  /**
   * The user is already hosting a game session for this project.
   */
  400: unknown;
  /**
   * The user or project was not found.
   */
  404: unknown;
};

export type MultiplayerControllerOpenHostResponses = {
  /**
   * The game host/session has been successfully opened.
   */
  200: OpenHostResponseDto;
};

export type MultiplayerControllerOpenHostResponse =
  MultiplayerControllerOpenHostResponses[keyof MultiplayerControllerOpenHostResponses];

export type MultiplayerControllerCloseHostData = {
  body: CloseHostRequestDto;
  path?: never;
  query?: never;
  url: "/multiplayer/close-host";
};

export type MultiplayerControllerCloseHostErrors = {
  /**
   * The user, project, or game session was not found.
   */
  404: unknown;
};

export type MultiplayerControllerCloseHostResponses = {
  /**
   * The game host/session has been successfully closed.
   */
  200: unknown;
};

export type MultiplayerControllerJoinHostData = {
  body: JoinHostRequestDto;
  path?: never;
  query?: never;
  url: "/multiplayer/join-host";
};

export type MultiplayerControllerJoinHostErrors = {
  /**
   * User is already in the session or is the host.
   */
  400: unknown;
  /**
   * Game session or user not found.
   */
  404: unknown;
};

export type MultiplayerControllerJoinHostResponses = {
  /**
   * Successfully joined the game session.
   */
  200: JoinHostResponseDto;
};

export type MultiplayerControllerJoinHostResponse =
  MultiplayerControllerJoinHostResponses[keyof MultiplayerControllerJoinHostResponses];

export type MultiplayerControllerLeaveHostData = {
  body: LeaveHostRequestDto;
  path?: never;
  query?: never;
  url: "/multiplayer/leave-host";
};

export type MultiplayerControllerLeaveHostErrors = {
  /**
   * User is not part of the session or is the host.
   */
  400: unknown;
  /**
   * Game session or user not found.
   */
  404: unknown;
};

export type MultiplayerControllerLeaveHostResponses = {
  /**
   * Successfully left the game session.
   */
  200: unknown;
};

export type AuthControllerLoginData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type AuthControllerLoginErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Cannot register as an admin
   */
  403: unknown;
  /**
   * Email or username already in use
   */
  409: unknown;
};

export type AuthControllerLoginResponses = {
  /**
   * User registered successfully
   */
  201: AuthResponseDto;
};

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRegisterData = {
  body: CreateUserDto;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type AuthControllerRegisterErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Cannot register as an admin
   */
  403: unknown;
  /**
   * Email already in use
   */
  409: unknown;
};

export type AuthControllerRegisterResponses = {
  /**
   * User registered successfully
   */
  201: AuthResponseDto;
};

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginWithGoogleData = {
  body: {
    token?: string;
  };
  path?: never;
  query?: never;
  url: "/auth/google";
};

export type AuthControllerLoginWithGoogleErrors = {
  /**
   * Invalid Google token
   */
  400: unknown;
};

export type AuthControllerLoginWithGoogleResponses = {
  /**
   * Login successful with Google
   */
  201: AuthResponseDto;
};

export type AuthControllerLoginWithGoogleResponse =
  AuthControllerLoginWithGoogleResponses[keyof AuthControllerLoginWithGoogleResponses];

export type AuthControllerRefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/refresh";
};

export type AuthControllerRefreshErrors = {
  /**
   * Refresh token missing or invalid
   */
  401: unknown;
};

export type AuthControllerRefreshResponses = {
  /**
   * Access token refreshed successfully
   */
  201: AuthResponseDto;
};

export type AuthControllerRefreshResponse =
  AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/logout";
};

export type AuthControllerLogoutResponses = {
  /**
   * Logout successful
   */
  200: unknown;
};

export type UserControllerGetProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/profile";
};

export type UserControllerGetProfileErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerGetProfileResponses = {
  /**
   * Returns the current user profile
   */
  200: UserProfileResponseDto;
};

export type UserControllerGetProfileResponse =
  UserControllerGetProfileResponses[keyof UserControllerGetProfileResponses];

export type UserControllerGetProfilePictureData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}/profile-picture";
};

export type UserControllerGetProfilePictureErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type UserControllerGetProfilePictureResponses = {
  /**
   * Signed cookies and CDN resource URL
   */
  200: SignedCdnResourceDto;
};

export type UserControllerGetProfilePictureResponse =
  UserControllerGetProfilePictureResponses[keyof UserControllerGetProfilePictureResponses];

export type UserControllerUploadProfilePictureData = {
  body: {
    /**
     * Profile picture file
     */
    file?: Blob | File;
  };
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}/profile-picture";
};

export type UserControllerUploadProfilePictureErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerUploadProfilePictureResponses = {
  /**
   * Profile uploaded
   */
  201: unknown;
};

export type UserControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Filter by nickname
     */
    nickname?: string;
    /**
     * Filter by email
     */
    email?: string;
    /**
     * Sort by field
     */
    sortBy?: "id" | "username" | "email" | "createdAt";
    /**
     * Sort order
     */
    order?: "asc" | "desc";
  };
  url: "/users";
};

export type UserControllerFindAllErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerFindAllResponses = {
  /**
   * Returns paginated list of users
   */
  200: UserListResponseDto;
};

export type UserControllerFindAllResponse =
  UserControllerFindAllResponses[keyof UserControllerFindAllResponses];

export type UserControllerRemoveData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerRemoveErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Insufficient permissions
   */
  403: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UserControllerRemoveResponses = {
  /**
   * User deleted successfully
   */
  200: {
    statusCode?: number;
    message?: string;
  };
};

export type UserControllerRemoveResponse =
  UserControllerRemoveResponses[keyof UserControllerRemoveResponses];

export type UserControllerFindOneData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerFindOneErrors = {
  /**
   * Invalid ID format
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UserControllerFindOneResponses = {
  /**
   * Returns the user
   */
  200: UserSingleResponseDto;
};

export type UserControllerFindOneResponse =
  UserControllerFindOneResponses[keyof UserControllerFindOneResponses];

export type UserControllerUpdateData = {
  body: UpdateUserDto;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerUpdateErrors = {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Insufficient permissions
   */
  403: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UserControllerUpdateResponses = {
  /**
   * User updated successfully
   */
  200: UserSingleResponseDto;
};

export type UserControllerUpdateResponse =
  UserControllerUpdateResponses[keyof UserControllerUpdateResponses];

export type UserControllerGetPublicProfilePictureData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/public/{id}/profile-picture";
};

export type UserControllerGetPublicProfilePictureErrors = {
  /**
   * User not found or has no profile picture
   */
  404: unknown;
};

export type UserControllerGetPublicProfilePictureResponses = {
  /**
   * Returns the CDN URL for the profile picture
   */
  200: ImageUrlResponseDto;
};

export type UserControllerGetPublicProfilePictureResponse =
  UserControllerGetPublicProfilePictureResponses[keyof UserControllerGetPublicProfilePictureResponses];

export type WorkSessionControllerJoinData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/work-sessions/join/{id}";
};

export type WorkSessionControllerJoinErrors = {
  /**
   * Bad request.
   */
  400: unknown;
};

export type WorkSessionControllerJoinResponses = {
  /**
   * The work session has been successfully created.
   */
  201: unknown;
};

export type WorkSessionControllerLeaveData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/work-sessions/leave/{id}";
};

export type WorkSessionControllerLeaveErrors = {
  /**
   * Bad request.
   */
  400: unknown;
};

export type WorkSessionControllerLeaveResponses = {
  /**
   * Successfully left the work session.
   */
  204: void;
};

export type WorkSessionControllerLeaveResponse =
  WorkSessionControllerLeaveResponses[keyof WorkSessionControllerLeaveResponses];

export type WorkSessionControllerKickData = {
  body: KickWorkSessionDto;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/work-sessions/kick/{id}";
};

export type WorkSessionControllerKickErrors = {
  /**
   * Bad request.
   */
  400: unknown;
};

export type WorkSessionControllerKickResponses = {
  /**
   * Successfully left the work session.
   */
  204: void;
};

export type WorkSessionControllerKickResponse =
  WorkSessionControllerKickResponses[keyof WorkSessionControllerKickResponses];

export type WorkSessionControllerGetInfoData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/work-sessions/info/{id}";
};

export type WorkSessionControllerGetInfoErrors = {
  /**
   * Work session not found.
   */
  404: unknown;
};

export type WorkSessionControllerGetInfoResponses = {
  /**
   * Work session info retrieved successfully.
   */
  200: FetchWorkSessionDto;
};

export type WorkSessionControllerGetInfoResponse =
  WorkSessionControllerGetInfoResponses[keyof WorkSessionControllerGetInfoResponses];
