// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string;
};

export type UserBasicInfoDto = {
  /**
   * The unique identifier of the user
   */
  id: number;
  /**
   * The username
   */
  username: string;
  /**
   * The email address
   */
  email: string;
};

export type ProjectExResponseDto = {
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * Tags associated with the project
   */
  tags: Array<string>;
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: "IN_PROGRESS" | "COMPLETED" | "ARCHIVED";
  /**
   * The monetization strategy for this project
   */
  monetization: "NONE" | "ADS" | "PAID";
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The date and time when the project was last updated
   */
  updatedAt: string;
  /**
   * The date and time when the project was last published
   */
  publishedAt: string | null;
  /**
   * The number of times players opened this game's play page
   */
  viewCount: number;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The number of comments on the project
   */
  commentCount?: number;
  /**
   * The number of forks created from this project
   */
  forkCount?: number;
  /**
   * The ID of the project this was forked from, if any
   */
  forkedFromId?: number | null;
  /**
   * The users collaborating on this project
   */
  collaborators: Array<UserBasicInfoDto>;
  /**
   * The creator of this project
   */
  creator: UserBasicInfoDto;
};

export type PaginatedProjectsResponseDto = {
  /**
   * The projects included in the current page
   */
  projects: Array<ProjectExResponseDto>;
  /**
   * The total number of projects matching the request
   */
  total: number;
  /**
   * The current page number
   */
  page: number;
  /**
   * The number of projects requested per page
   */
  limit: number;
};

export type ProjectsCountResponseDto = {
  /**
   * The total number of projects matching the request
   */
  total: number;
};

export type SignedUrlResponseDto = {
  /**
   * The signed CloudFront URL for accessing the protected file
   */
  signedUrl: string;
};

export type ProjectResponseDto = {
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * Tags associated with the project
   */
  tags: Array<string>;
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: "IN_PROGRESS" | "COMPLETED" | "ARCHIVED";
  /**
   * The monetization strategy for this project
   */
  monetization: "NONE" | "ADS" | "PAID";
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The date and time when the project was last updated
   */
  updatedAt: string;
  /**
   * The date and time when the project was last published
   */
  publishedAt: string | null;
  /**
   * The number of times players opened this game's play page
   */
  viewCount: number;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The number of comments on the project
   */
  commentCount?: number;
  /**
   * The number of forks created from this project
   */
  forkCount?: number;
  /**
   * The ID of the project this was forked from, if any
   */
  forkedFromId?: number | null;
};

export type CreateProjectDto = {
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * URL to the project icon
   */
  iconUrl?: string;
  /**
   * Tags attached to the project
   */
  tags?: Array<string>;
};

export type ForkProjectResponseDto = {
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * Tags associated with the project
   */
  tags: Array<string>;
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: "IN_PROGRESS" | "COMPLETED" | "ARCHIVED";
  /**
   * The monetization strategy for this project
   */
  monetization: "NONE" | "ADS" | "PAID";
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The date and time when the project was last updated
   */
  updatedAt: string;
  /**
   * The date and time when the project was last published
   */
  publishedAt: string | null;
  /**
   * The number of times players opened this game's play page
   */
  viewCount: number;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The number of comments on the project
   */
  commentCount?: number;
  /**
   * The number of forks created from this project
   */
  forkCount?: number;
  /**
   * The ID of the project this was forked from, if any
   */
  forkedFromId?: number | null;
  /**
   * The users collaborating on this project
   */
  collaborators: Array<UserBasicInfoDto>;
  /**
   * The creator of this project
   */
  creator: UserBasicInfoDto;
};

export type UpdateProjectDto = {
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc?: {
    [key: string]: unknown;
  };
  /**
   * Tags attached to the project
   */
  tags?: Array<string>;
  /**
   * URL to the project icon
   */
  iconUrl?: string;
  /**
   * Project status
   */
  status?: "IN_PROGRESS" | "COMPLETED" | "ARCHIVED";
  /**
   * Monetization type
   */
  monetization?: "NONE" | "ADS" | "PAID";
  /**
   * The price of the project
   */
  price?: number;
};

export type AddCollaboratorDto = {
  /**
   * User ID of the user to add as collaborator
   */
  userId?: number;
  /**
   * Username of the user to add as collaborator
   */
  username?: string;
  /**
   * Email of the user to add as collaborator
   */
  email?: string;
};

export type RemoveCollaboratorDto = {
  /**
   * User ID of the user to remove as collaborator
   */
  userId?: number;
  /**
   * Username of the user to remove as collaborator
   */
  username?: string;
  /**
   * Email of the user to remove as collaborator
   */
  email?: string;
};

export type ImageUrlResponseDto = {
  /**
   * The public CDN URL for the image
   */
  url: string;
};

export type LikeResponseDto = {
  /**
   * Total number of likes on the project
   */
  likes: number;
  /**
   * Whether the current user has liked this project
   */
  liked: boolean;
};

export type ViewResponseDto = {
  /**
   * The number of play opens registered for the project
   */
  viewCount: number;
};

export type CreateGameSessionDto = {
  /**
   * ID of the project this session is played on
   */
  projectId: number;
  /**
   * Human-readable title of the session
   */
  title: string;
  /**
   * Maximum number of players, host included
   */
  maxPlayers: number;
  visibility: "PUBLIC" | "FRIENDS_ONLY" | "INVITE_CODE";
};

export type WebRtcOfferPeerIceServerConfig = {
  urls: string;
  username?: {
    [key: string]: unknown;
  };
  credential?: {
    [key: string]: unknown;
  };
};

export type WebRtcOfferPeerOptsConfig = {
  iceServers: Array<WebRtcOfferPeerIceServerConfig>;
};

export type WebRtcOfferPeerOpts = {
  config: WebRtcOfferPeerOptsConfig;
};

export type WebRtcOfferDto = {
  signaling: Array<string>;
  maxConns: number;
  peerOpts: WebRtcOfferPeerOpts;
};

export type GameSessionConnectionResponseDto = {
  sessionUuid: string;
  /**
   * Player id assigned to this connection
   */
  playerId: number;
  webrtcConfig: WebRtcOfferDto;
  /**
   * Short-lived signed ticket presented on the WebRTC connection
   */
  connectionTicket: string;
  /**
   * Join code to share, present only when hosting an INVITE_CODE session
   */
  joinCode?: string;
};

export type JoinByCodeDto = {
  /**
   * Invite code of the session to join
   */
  joinCode: string;
  /**
   * Set by the game editor to allow a self-join for solo testing
   */
  editorTest?: boolean;
};

export type GameSessionResponseDto = {
  sessionUuid: string;
  title: string;
  visibility: "PUBLIC" | "FRIENDS_ONLY" | "INVITE_CODE";
  /**
   * ID of the host user
   */
  hostId: number;
  /**
   * Username of the host
   */
  hostUsername: string;
  /**
   * Display nickname of the host, if set
   */
  hostNickname?: string;
  /**
   * Name of the game (project) being played
   */
  projectName: string;
  /**
   * Maximum number of players, host included
   */
  maxPlayers: number;
  /**
   * Current number of players, host included
   */
  playerCount: number;
};

export type GameSessionListResponseDto = {
  sessions: Array<GameSessionResponseDto>;
};

export type UpdateGameSessionDto = {
  /**
   * New title of the session
   */
  title?: string;
  /**
   * New maximum number of players, host included
   */
  maxPlayers?: number;
  visibility?: "PUBLIC" | "FRIENDS_ONLY" | "INVITE_CODE";
};

export type JoinGameSessionDto = {
  /**
   * Join code, required for INVITE_CODE sessions
   */
  joinCode?: string;
  /**
   * Set by the game editor to allow a self-join for solo testing
   */
  editorTest?: boolean;
};

export type CommentAuthorDto = {
  id: number;
  username: string;
  nickname?: string | null;
};

export type CommentResponseDto = {
  id: number;
  content: string;
  createdAt: string;
  projectId: number;
  author: CommentAuthorDto;
  deleted?: boolean;
  /**
   * Replies to this comment (only for top-level comments)
   */
  replies?: Array<CommentResponseDto>;
};

export type PaginatedCommentsResponseDto = {
  comments: Array<CommentResponseDto>;
  total: number;
  page: number;
  limit: number;
};

export type CreateCommentDto = {
  /**
   * The content of the comment
   */
  content: string;
};

export type CreateReportDto = {
  targetType: "USER" | "PROJECT" | "COMMENT";
  targetId: number;
  reason: string;
  details?: string;
};

export type ReportResponseDto = {
  id: number;
  targetType: "USER" | "PROJECT" | "COMMENT";
  targetId: number;
  reporterId: number;
  reason: string;
  details: {
    [key: string]: unknown;
  } | null;
  status: "OPEN" | "IN_REVIEW" | "RESOLVED" | "DISMISSED";
  createdAt: string;
};

export type AdminLoginDto = {
  email: string;
  password: string;
};

export type AdminMeDto = {
  id: number;
  email: string;
  username: string;
  nickname?: {
    [key: string]: unknown;
  } | null;
  accountStatus: "ACTIVE" | "SUSPENDED" | "BANNED";
  roles: Array<string>;
};

export type CreateAdminUserDto = {
  email: string;
  username: string;
  nickname?: string;
  password: string;
  roles: Array<string>;
};

export type UpdateAdminUserDto = {
  email?: string;
  username?: string;
  nickname?: {
    [key: string]: unknown;
  } | null;
  roles?: Array<string>;
  /**
   * Free-form audit reason, recorded in the moderation log
   */
  reason?: string;
};

export type ModerationReasonDto = {
  /**
   * Free-form reason recorded in the audit log
   */
  reason?: string;
  /**
   * Optional related report id
   */
  reportId?: number;
};

export type AdminUserResponseDto = {
  id: number;
  email: string;
  username: string;
  nickname?: {
    [key: string]: unknown;
  } | null;
  accountStatus: "ACTIVE" | "SUSPENDED" | "BANNED";
  roles: Array<string>;
  createdAt: string;
  moderationReason?: {
    [key: string]: unknown;
  } | null;
  moderatedAt?: {
    [key: string]: unknown;
  } | null;
  moderatedById?: {
    [key: string]: unknown;
  } | null;
};

export type ResetPasswordDto = {
  newPassword: string;
  reason?: string;
};

export type AdminUpdateProjectDto = {
  name?: string;
  shortDesc?: string;
  longDesc?: {
    [key: string]: unknown;
  } | null;
  publishedName?: {
    [key: string]: unknown;
  } | null;
  publishedShortDesc?: {
    [key: string]: unknown;
  } | null;
  publishedLongDesc?: {
    [key: string]: unknown;
  } | null;
  tags?: Array<string>;
  publishedTags?: Array<string>;
  iconUrl?: {
    [key: string]: unknown;
  } | null;
  monetization?: "NONE" | "ADS" | "PAID";
  price?: {
    [key: string]: unknown;
  } | null;
  hiddenReason?: {
    [key: string]: unknown;
  } | null;
  reason?: string;
};

export type AdminUpdateCommentDto = {
  content: string;
  reason?: string;
};

export type ReportActionDto = {
  resolutionNote?: string;
};

export type CreateRoleDto = {
  name: string;
  reason?: string;
};

export type UpdateRoleDto = {
  name: string;
  reason?: string;
};

export type DeleteRoleDto = {
  reason?: string;
};

export type NotificationTestDto = {
  /**
   * The title of the test notification
   */
  title: string;
  /**
   * The message content of the test notification
   */
  message: string;
  /**
   * The type of the notification
   */
  type: "INFO" | "WARNING";
};

export type LoginDto = {
  /**
   * User email address
   */
  email: string;
  /**
   * User password
   */
  password: string;
};

export type CreateUserDto = {
  /**
   * User email address
   */
  email: string;
  /**
   * User username
   */
  username: string;
  /**
   * User nick name
   */
  nickname?: string;
  /**
   * User password
   */
  password: string;
};

export type GoogleCodeDto = {
  /**
   * Google authorization code
   */
  code: string;
  /**
   * PKCE code verifier
   */
  codeVerifier: string;
};

export type GithubLoginDto = {
  /**
   * GitHub OAuth authorization code
   */
  code: string;
};

export type MicrosoftLoginDto = {
  /**
   * Microsoft ID token
   */
  token: string;
};

export type ChangePasswordDto = {
  /**
   * Current password (not required for OAuth accounts)
   */
  currentPassword?: string;
  /**
   * New password
   */
  newPassword: string;
};

export type UserRoleDto = {
  /**
   * Role ID
   */
  id: number;
  /**
   * Role name
   */
  name: string;
};

export type UserResponseDto = {
  /**
   * User ID
   */
  id: number;
  /**
   * User email address
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname
   */
  nickname: string | null;
  /**
   * User roles
   */
  roles?: Array<UserRoleDto>;
  /**
   * Current account moderation status
   */
  accountStatus: "ACTIVE" | "SUSPENDED" | "BANNED";
  /**
   * User creation date
   */
  createdAt: string;
  /**
   * User last update date
   */
  updatedAt: string;
};

export type PaginationMetaDto = {
  /**
   * Current page number
   */
  page: number;
  /**
   * Number of items per page
   */
  limit: number;
  /**
   * Total number of items
   */
  total: number;
  /**
   * Total number of pages
   */
  totalPages: number;
};

export type UserListResponseDto = {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * List of users
   */
  data: Array<UserResponseDto>;
  /**
   * Pagination metadata
   */
  meta: PaginationMetaDto;
};

export type UserSingleResponseDto = {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * User data
   */
  data: UserResponseDto;
};

export type UserProfileResponseDto = {
  /**
   * User ID
   */
  id: number;
  /**
   * User email address
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname
   */
  nickname: string | null;
  /**
   * User roles
   */
  roles?: Array<UserRoleDto>;
  /**
   * Current account moderation status
   */
  accountStatus: "ACTIVE" | "SUSPENDED" | "BANNED";
  /**
   * User creation date
   */
  createdAt: string;
  /**
   * User last update date
   */
  updatedAt: string;
  /**
   * User profile message
   */
  message: string;
};

export type PublicUserProfileDto = {
  /**
   * User ID
   */
  id: number;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname / bio
   */
  nickname?: string | null;
  /**
   * User profile description
   */
  description?: string | null;
  /**
   * Public CDN URL of the profile image (if any)
   */
  profileImageUrl?: string | null;
  /**
   * Public CDN URL of the profile background image (if any)
   */
  backgroundImageUrl?: string | null;
};

export type PublicUserProfileResponseDto = {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * Public user profile
   */
  data: PublicUserProfileDto;
};

export type UpdateUserProfileDto = {
  /**
   * Public nickname / bio displayed on the profile
   */
  nickname?: string;
  /**
   * Public profile description displayed on the profile
   */
  description?: string;
};

export type SignedCdnResourceDto = {
  /**
   * The CDN URL for the resource (requires signed cookies)
   */
  resourceUrl: string;
  /**
   * Signed Edge cookies (also set as HTTP-only cookies)
   */
  cookies: {
    [key: string]: unknown;
  };
};

export type UpdateUserDto = {
  /**
   * User email address
   */
  email?: string;
  /**
   * User username
   */
  username?: string;
  /**
   * User nick name
   */
  nickname?: string;
  /**
   * User password
   */
  password?: string;
};

export type JoinWorkSessionDto = {
  /**
   * The unique room ID for the work session
   */
  roomId: string;
  /**
   * The user ID of the session's host
   */
  hostId: number;
  /**
   * The WebRTC offer given to the client
   */
  webrtcOffer: WebRtcOfferDto;
};

export type KickWorkSessionDto = {
  /**
   * The ID of the user participating in the work session
   */
  userId: number;
};

export type FetchWorkSessionDto = {
  /**
   * The ID of the user participating in the work session
   */
  users: Array<string>;
  /**
   * The ID of the session's host
   */
  hostId: number;
  /**
   * The ID of the project this work session belongs to
   */
  project: number;
  /**
   * The date and time when the work session started
   */
  startedAt: string;
  /**
   * The ID of the room for this work session
   */
  roomId: string;
};

export type ProjectControllerGetAllReleasesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/projects/releases";
};

export type ProjectControllerGetAllReleasesResponses = {
  /**
   * A JSON array of projects with collaborators and creator information
   */
  200: Array<ProjectExResponseDto>;
};

export type ProjectControllerGetAllReleasesResponse =
  ProjectControllerGetAllReleasesResponses[keyof ProjectControllerGetAllReleasesResponses];

export type ProjectControllerGetPaginatedReleasesData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/projects/releases/paginated";
};

export type ProjectControllerGetPaginatedReleasesResponses = {
  /**
   * A paginated list of released projects
   */
  200: PaginatedProjectsResponseDto;
};

export type ProjectControllerGetPaginatedReleasesResponse =
  ProjectControllerGetPaginatedReleasesResponses[keyof ProjectControllerGetPaginatedReleasesResponses];

export type ProjectControllerCountReleasedProjectsData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
    /**
     * Comma-separated tag list
     */
    tags?: string;
    releaseWindow?: "all" | "365d" | "30d" | "7d";
  };
  url: "/projects/releases/count";
};

export type ProjectControllerCountReleasedProjectsResponses = {
  /**
   * The total number of released projects matching the request
   */
  200: ProjectsCountResponseDto;
};

export type ProjectControllerCountReleasedProjectsResponse =
  ProjectControllerCountReleasedProjectsResponses[keyof ProjectControllerCountReleasedProjectsResponses];

export type ProjectControllerGetReleaseData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}";
};

export type ProjectControllerGetReleaseResponses = {
  /**
   * Project release metadata
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerGetReleaseResponse =
  ProjectControllerGetReleaseResponses[keyof ProjectControllerGetReleaseResponses];

export type ProjectControllerGetReleaseContentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}/content";
};

export type ProjectControllerGetReleaseContentResponses = {
  /**
   * Project release file
   */
  200: Blob | File;
};

export type ProjectControllerGetReleaseContentResponse =
  ProjectControllerGetReleaseContentResponses[keyof ProjectControllerGetReleaseContentResponses];

export type ProjectControllerGetReleaseContentUrlData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}/content-url";
};

export type ProjectControllerGetReleaseContentUrlResponses = {
  /**
   * Signed Edge URL for the release
   */
  200: SignedUrlResponseDto;
};

export type ProjectControllerGetReleaseContentUrlResponse =
  ProjectControllerGetReleaseContentUrlResponses[keyof ProjectControllerGetReleaseContentUrlResponses];

export type ProjectControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/projects";
};

export type ProjectControllerFindAllErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type ProjectControllerFindAllResponses = {
  /**
   * A paginated list of projects with collaborators and creator information
   */
  200: PaginatedProjectsResponseDto;
};

export type ProjectControllerFindAllResponse =
  ProjectControllerFindAllResponses[keyof ProjectControllerFindAllResponses];

export type ProjectControllerCreateData = {
  body: CreateProjectDto;
  path?: never;
  query?: never;
  url: "/projects";
};

export type ProjectControllerCreateErrors = {
  /**
   * Bad request – invalid input
   */
  400: unknown;
};

export type ProjectControllerCreateResponses = {
  /**
   * Project created successfully
   */
  201: ProjectResponseDto;
};

export type ProjectControllerCreateResponse =
  ProjectControllerCreateResponses[keyof ProjectControllerCreateResponses];

export type ProjectControllerCountProjectsData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
    /**
     * Comma-separated tag list
     */
    tags?: string;
    status?: "all" | "drafts" | "published";
  };
  url: "/projects/count";
};

export type ProjectControllerCountProjectsResponses = {
  /**
   * The total number of user projects matching the request
   */
  200: ProjectsCountResponseDto;
};

export type ProjectControllerCountProjectsResponse =
  ProjectControllerCountProjectsResponses[keyof ProjectControllerCountProjectsResponses];

export type ProjectControllerRemoveData = {
  body?: never;
  path: {
    /**
     * Numeric ID of the project to delete
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}";
};

export type ProjectControllerRemoveErrors = {
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Error deleting project
   */
  500: unknown;
};

export type ProjectControllerRemoveResponses = {
  /**
   * Project deleted successfully (no content)
   */
  204: void;
};

export type ProjectControllerRemoveResponse =
  ProjectControllerRemoveResponses[keyof ProjectControllerRemoveResponses];

export type ProjectControllerFindOneData = {
  body?: never;
  path: {
    /**
     * Numeric ID of the project to retrieve
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}";
};

export type ProjectControllerFindOneErrors = {
  /**
   * Invalid user or project ID
   */
  403: unknown;
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type ProjectControllerFindOneResponses = {
  /**
   * Project object
   */
  200: ProjectResponseDto;
};

export type ProjectControllerFindOneResponse =
  ProjectControllerFindOneResponses[keyof ProjectControllerFindOneResponses];

export type ProjectControllerUpdateData = {
  body: UpdateProjectDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}";
};

export type ProjectControllerUpdateErrors = {
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Error updating project
   */
  500: unknown;
};

export type ProjectControllerUpdateResponses = {
  /**
   * Updated project object
   */
  200: ProjectResponseDto;
};

export type ProjectControllerUpdateResponse =
  ProjectControllerUpdateResponses[keyof ProjectControllerUpdateResponses];

export type ProjectControllerForkData = {
  body?: never;
  path: {
    /**
     * Numeric ID of the published project to fork
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}/fork";
};

export type ProjectControllerForkErrors = {
  /**
   * Project is not published
   */
  400: unknown;
  /**
   * Project not found
   */
  404: unknown;
};

export type ProjectControllerForkResponses = {
  /**
   * Forked project created successfully
   */
  201: ForkProjectResponseDto;
};

export type ProjectControllerForkResponse =
  ProjectControllerForkResponses[keyof ProjectControllerForkResponses];

export type ProjectControllerAddCollaboratorData = {
  body: AddCollaboratorDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}/add-collaborator";
};

export type ProjectControllerAddCollaboratorErrors = {
  /**
   * Bad request - no valid identifier provided
   */
  400: unknown;
  /**
   * Project or user not found
   */
  404: unknown;
  /**
   * Error Patching project
   */
  500: unknown;
};

export type ProjectControllerAddCollaboratorResponses = {
  /**
   * Updated project object with collaborators
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerAddCollaboratorResponse =
  ProjectControllerAddCollaboratorResponses[keyof ProjectControllerAddCollaboratorResponses];

export type ProjectControllerRemoveCollaboratorData = {
  body: RemoveCollaboratorDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: "/projects/{id}/remove-collaborator";
};

export type ProjectControllerRemoveCollaboratorErrors = {
  /**
   * Bad request - no valid identifier provided
   */
  400: unknown;
  /**
   * Forbidden - cannot remove project creator
   */
  403: unknown;
  /**
   * Project or user not found
   */
  404: unknown;
  /**
   * Error remove collaborator on project
   */
  500: unknown;
};

export type ProjectControllerRemoveCollaboratorResponses = {
  /**
   * Updated project object with collaborators
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerRemoveCollaboratorResponse =
  ProjectControllerRemoveCollaboratorResponses[keyof ProjectControllerRemoveCollaboratorResponses];

export type ProjectControllerSaveProjectContentData = {
  body: {
    /**
     * Project file (zip, pdf, png, etc.)
     */
    file?: Blob | File;
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/projects/{id}/saveContent";
};

export type ProjectControllerSaveProjectContentErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * File validation failed
   */
  422: unknown;
};

export type ProjectControllerSaveProjectContentResponses = {
  /**
   * File uploaded successfully
   */
  201: unknown;
};

export type ProjectControllerGetProjectImageData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/projects/{id}/image";
};

export type ProjectControllerGetProjectImageErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetProjectImageResponses = {
  /**
   * CDN URL for the project image
   */
  200: ImageUrlResponseDto;
  /**
   * Project has no image
   */
  204: void;
};

export type ProjectControllerGetProjectImageResponse =
  ProjectControllerGetProjectImageResponses[keyof ProjectControllerGetProjectImageResponses];

export type ProjectControllerUploadProjectImageData = {
  body: {
    /**
     * Project image file (JPEG, PNG, GIF, WebP)
     */
    file?: Blob | File;
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/projects/{id}/image";
};

export type ProjectControllerUploadProjectImageErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Invalid file type or size
   */
  422: unknown;
};

export type ProjectControllerUploadProjectImageResponses = {
  /**
   * Image uploaded successfully
   */
  201: unknown;
};

export type ProjectControllerGetPublishedProjectImageData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/projects/public/{id}/image";
};

export type ProjectControllerGetPublishedProjectImageErrors = {
  /**
   * Project not found, not published, or has no image
   */
  404: unknown;
};

export type ProjectControllerGetPublishedProjectImageResponses = {
  /**
   * Returns the CDN URL for the project image
   */
  200: ImageUrlResponseDto;
};

export type ProjectControllerGetPublishedProjectImageResponse =
  ProjectControllerGetPublishedProjectImageResponses[keyof ProjectControllerGetPublishedProjectImageResponses];

export type ProjectControllerGetProjectPreviewData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/preview";
};

export type ProjectControllerGetProjectPreviewErrors = {
  /**
   * Staff access required
   */
  403: unknown;
  /**
   * Project not found
   */
  404: unknown;
};

export type ProjectControllerGetProjectPreviewResponses = {
  /**
   * Project metadata
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerGetProjectPreviewResponse =
  ProjectControllerGetProjectPreviewResponses[keyof ProjectControllerGetProjectPreviewResponses];

export type ProjectControllerGetProjectPreviewContentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/preview/content";
};

export type ProjectControllerGetProjectPreviewContentErrors = {
  /**
   * Staff access required
   */
  403: unknown;
  /**
   * Project or content not found
   */
  404: unknown;
};

export type ProjectControllerGetProjectPreviewContentResponses = {
  /**
   * Playable project content
   */
  200: Blob | File;
};

export type ProjectControllerGetProjectPreviewContentResponse =
  ProjectControllerGetProjectPreviewContentResponses[keyof ProjectControllerGetProjectPreviewContentResponses];

export type ProjectControllerFetchProjectContentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/fetchContent";
};

export type ProjectControllerFetchProjectContentErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * File not found
   */
  404: unknown;
};

export type ProjectControllerFetchProjectContentResponses = {
  /**
   * File fetched successfully
   */
  200: Blob | File;
};

export type ProjectControllerFetchProjectContentResponse =
  ProjectControllerFetchProjectContentResponses[keyof ProjectControllerFetchProjectContentResponses];

export type ProjectControllerSaveCheckpointData = {
  body: {
    file?: Blob | File;
  };
  path: {
    id: string;
    name: string;
  };
  query?: never;
  url: "/projects/{id}/saveCheckpoint/{name}";
};

export type ProjectControllerSaveCheckpointErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerSaveCheckpointResponses = {
  /**
   * File uploaded successfully
   */
  201: unknown;
};

export type ProjectControllerDeleteCheckpointData = {
  body?: never;
  path: {
    id: string;
    name: string;
  };
  query?: never;
  url: "/projects/{id}/deleteCheckpoint/{name}";
};

export type ProjectControllerDeleteCheckpointErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerDeleteCheckpointResponses = {
  /**
   * File deleted successfully
   */
  201: unknown;
};

export type ProjectControllerPublishData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/publish";
};

export type ProjectControllerPublishErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerPublishResponses = {
  /**
   * Project published successfully
   */
  201: unknown;
};

export type ProjectControllerUnpublishData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/unpublish";
};

export type ProjectControllerUnpublishErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerUnpublishResponses = {
  /**
   * Project unpublished successfully
   */
  201: unknown;
};

export type ProjectControllerGetVersionsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/versions";
};

export type ProjectControllerGetVersionsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetVersionsResponses = {
  /**
   * Project versions retrieved successfully
   */
  200: unknown;
};

export type ProjectControllerGetCheckpointsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/checkpoints";
};

export type ProjectControllerGetCheckpointsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetCheckpointsResponses = {
  /**
   * Project checkpoints retrieved successfully
   */
  200: unknown;
};

export type ProjectControllerGetVersionData = {
  body?: never;
  path: {
    id: string;
    version: string;
  };
  query?: never;
  url: "/projects/{id}/versions/{version}";
};

export type ProjectControllerGetVersionErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetVersionResponses = {
  /**
   * Project version retrieved successfully
   */
  200: Blob | File;
};

export type ProjectControllerGetVersionResponse =
  ProjectControllerGetVersionResponses[keyof ProjectControllerGetVersionResponses];

export type ProjectControllerGetCheckpointData = {
  body?: never;
  path: {
    id: string;
    checkpoint: string;
  };
  query?: never;
  url: "/projects/{id}/checkpoints/{checkpoint}";
};

export type ProjectControllerGetCheckpointErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetCheckpointResponses = {
  /**
   * Project checkpoint retrieved successfully
   */
  200: Blob | File;
};

export type ProjectControllerGetCheckpointResponse =
  ProjectControllerGetCheckpointResponses[keyof ProjectControllerGetCheckpointResponses];

export type ProjectControllerUnlikeProjectData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}/like";
};

export type ProjectControllerUnlikeProjectResponses = {
  /**
   * Like removed
   */
  200: LikeResponseDto;
};

export type ProjectControllerUnlikeProjectResponse =
  ProjectControllerUnlikeProjectResponses[keyof ProjectControllerUnlikeProjectResponses];

export type ProjectControllerLikeProjectData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}/like";
};

export type ProjectControllerLikeProjectResponses = {
  /**
   * Like status
   */
  200: LikeResponseDto;
};

export type ProjectControllerLikeProjectResponse =
  ProjectControllerLikeProjectResponses[keyof ProjectControllerLikeProjectResponses];

export type ProjectControllerGetLikeStatusData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}/like-status";
};

export type ProjectControllerGetLikeStatusResponses = {
  /**
   * Like status
   */
  200: LikeResponseDto;
};

export type ProjectControllerGetLikeStatusResponse =
  ProjectControllerGetLikeStatusResponses[keyof ProjectControllerGetLikeStatusResponses];

export type ProjectControllerRegisterReleaseViewData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/releases/{id}/view";
};

export type ProjectControllerRegisterReleaseViewResponses = {
  /**
   * Updated view count
   */
  200: ViewResponseDto;
};

export type ProjectControllerRegisterReleaseViewResponse =
  ProjectControllerRegisterReleaseViewResponses[keyof ProjectControllerRegisterReleaseViewResponses];

export type ProjectControllerUpdateReleaseData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/projects/{id}/update-release";
};

export type ProjectControllerUpdateReleaseErrors = {
  /**
   * Project is not published
   */
  400: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerUpdateReleaseResponses = {
  /**
   * Release updated successfully
   */
  200: unknown;
};

export type MultiplayerControllerListData = {
  body?: never;
  path?: never;
  query: {
    projectId: number;
  };
  url: "/game-sessions";
};

export type MultiplayerControllerListResponses = {
  200: GameSessionListResponseDto;
};

export type MultiplayerControllerListResponse =
  MultiplayerControllerListResponses[keyof MultiplayerControllerListResponses];

export type MultiplayerControllerCreateData = {
  body: CreateGameSessionDto;
  path?: never;
  query?: never;
  url: "/game-sessions";
};

export type MultiplayerControllerCreateResponses = {
  201: GameSessionConnectionResponseDto;
};

export type MultiplayerControllerCreateResponse =
  MultiplayerControllerCreateResponses[keyof MultiplayerControllerCreateResponses];

export type MultiplayerControllerJoinByCodeData = {
  body: JoinByCodeDto;
  path?: never;
  query?: never;
  url: "/game-sessions/join-by-code";
};

export type MultiplayerControllerJoinByCodeResponses = {
  200: GameSessionConnectionResponseDto;
};

export type MultiplayerControllerJoinByCodeResponse =
  MultiplayerControllerJoinByCodeResponses[keyof MultiplayerControllerJoinByCodeResponses];

export type MultiplayerControllerRemoveData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/game-sessions/{sessionId}";
};

export type MultiplayerControllerRemoveResponses = {
  200: unknown;
};

export type MultiplayerControllerGetData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/game-sessions/{sessionId}";
};

export type MultiplayerControllerGetResponses = {
  200: GameSessionResponseDto;
};

export type MultiplayerControllerGetResponse =
  MultiplayerControllerGetResponses[keyof MultiplayerControllerGetResponses];

export type MultiplayerControllerUpdateData = {
  body: UpdateGameSessionDto;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/game-sessions/{sessionId}";
};

export type MultiplayerControllerUpdateResponses = {
  200: unknown;
};

export type MultiplayerControllerJoinData = {
  body: JoinGameSessionDto;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/game-sessions/{sessionId}/join";
};

export type MultiplayerControllerJoinResponses = {
  200: GameSessionConnectionResponseDto;
};

export type MultiplayerControllerJoinResponse =
  MultiplayerControllerJoinResponses[keyof MultiplayerControllerJoinResponses];

export type MultiplayerControllerLeaveData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/game-sessions/{sessionId}/leave";
};

export type MultiplayerControllerLeaveResponses = {
  200: unknown;
};

export type MultiplayerControllerRefreshTicketData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/game-sessions/{sessionId}/ticket";
};

export type MultiplayerControllerRefreshTicketResponses = {
  200: GameSessionConnectionResponseDto;
};

export type MultiplayerControllerRefreshTicketResponse =
  MultiplayerControllerRefreshTicketResponses[keyof MultiplayerControllerRefreshTicketResponses];

export type ProjectCommentControllerGetCommentsData = {
  body?: never;
  path: {
    projectId: number;
  };
  query?: {
    page?: number;
    limit?: number;
    sort?: "newest" | "oldest";
  };
  url: "/projects/{projectId}/comments";
};

export type ProjectCommentControllerGetCommentsResponses = {
  /**
   * Paginated list of comments
   */
  200: PaginatedCommentsResponseDto;
};

export type ProjectCommentControllerGetCommentsResponse =
  ProjectCommentControllerGetCommentsResponses[keyof ProjectCommentControllerGetCommentsResponses];

export type ProjectCommentControllerCreateCommentData = {
  body: CreateCommentDto;
  path: {
    projectId: number;
  };
  query?: never;
  url: "/projects/{projectId}/comments";
};

export type ProjectCommentControllerCreateCommentResponses = {
  /**
   * Comment created
   */
  201: CommentResponseDto;
};

export type ProjectCommentControllerCreateCommentResponse =
  ProjectCommentControllerCreateCommentResponses[keyof ProjectCommentControllerCreateCommentResponses];

export type ProjectCommentControllerCreateReplyData = {
  body: CreateCommentDto;
  path: {
    projectId: number;
    commentId: number;
  };
  query?: never;
  url: "/projects/{projectId}/comments/{commentId}/reply";
};

export type ProjectCommentControllerCreateReplyResponses = {
  /**
   * Reply created
   */
  201: CommentResponseDto;
};

export type ProjectCommentControllerCreateReplyResponse =
  ProjectCommentControllerCreateReplyResponses[keyof ProjectCommentControllerCreateReplyResponses];

export type ProjectCommentControllerDeleteCommentData = {
  body?: never;
  path: {
    projectId: number;
    commentId: number;
  };
  query?: never;
  url: "/projects/{projectId}/comments/{commentId}";
};

export type ProjectCommentControllerDeleteCommentResponses = {
  /**
   * Comment deleted
   */
  204: void;
};

export type ProjectCommentControllerDeleteCommentResponse =
  ProjectCommentControllerDeleteCommentResponses[keyof ProjectCommentControllerDeleteCommentResponses];

export type ProjectCommentControllerUpdateCommentData = {
  body: CreateCommentDto;
  path: {
    commentId: number;
    projectId: number;
  };
  query?: never;
  url: "/projects/{projectId}/comments/{commentId}";
};

export type ProjectCommentControllerUpdateCommentResponses = {
  /**
   * Comment updated
   */
  200: CommentResponseDto;
};

export type ProjectCommentControllerUpdateCommentResponse =
  ProjectCommentControllerUpdateCommentResponses[keyof ProjectCommentControllerUpdateCommentResponses];

export type ReportControllerCreateData = {
  body: CreateReportDto;
  path?: never;
  query?: never;
  url: "/reports";
};

export type ReportControllerCreateResponses = {
  /**
   * Report submitted
   */
  201: ReportResponseDto;
};

export type ReportControllerCreateResponse =
  ReportControllerCreateResponses[keyof ReportControllerCreateResponses];

export type AdminAuthControllerLoginData = {
  body: AdminLoginDto;
  path?: never;
  query?: never;
  url: "/admin/auth/login";
};

export type AdminAuthControllerLoginErrors = {
  401: unknown;
  403: unknown;
};

export type AdminAuthControllerLoginResponses = {
  200: AdminMeDto;
};

export type AdminAuthControllerLoginResponse =
  AdminAuthControllerLoginResponses[keyof AdminAuthControllerLoginResponses];

export type AdminAuthControllerRefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/admin/auth/refresh";
};

export type AdminAuthControllerRefreshErrors = {
  401: unknown;
  403: unknown;
};

export type AdminAuthControllerRefreshResponses = {
  200: AdminMeDto;
};

export type AdminAuthControllerRefreshResponse =
  AdminAuthControllerRefreshResponses[keyof AdminAuthControllerRefreshResponses];

export type AdminAuthControllerLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/admin/auth/logout";
};

export type AdminAuthControllerLogoutResponses = {
  200: unknown;
};

export type AdminAuthControllerMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/admin/auth/me";
};

export type AdminAuthControllerMeResponses = {
  200: AdminMeDto;
};

export type AdminAuthControllerMeResponse =
  AdminAuthControllerMeResponses[keyof AdminAuthControllerMeResponses];

export type AdminInsightsControllerGetDashboardData = {
  body?: never;
  path?: never;
  query?: {
    days?: number;
  };
  url: "/admin/insights/dashboard";
};

export type AdminInsightsControllerGetDashboardResponses = {
  200: unknown;
};

export type AdminInsightsControllerGetLiveData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/admin/insights/live";
};

export type AdminInsightsControllerGetLiveResponses = {
  200: unknown;
};

export type AdminInsightsControllerGetSocialData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/admin/insights/social";
};

export type AdminInsightsControllerGetSocialResponses = {
  200: unknown;
};

export type AdminUserControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    sortBy?:
      | "id"
      | "email"
      | "username"
      | "nickname"
      | "createdAt"
      | "accountStatus";
    order?: "asc" | "desc";
    email?: string;
    username?: string;
    nickname?: string;
    accountStatus?: "ACTIVE" | "SUSPENDED" | "BANNED";
    /**
     * Filter users having this role name
     */
    role?: string;
  };
  url: "/admin/users";
};

export type AdminUserControllerListResponses = {
  200: unknown;
};

export type AdminUserControllerCreateData = {
  body: CreateAdminUserDto;
  path?: never;
  query?: never;
  url: "/admin/users";
};

export type AdminUserControllerCreateResponses = {
  201: unknown;
};

export type AdminUserControllerRemoveData = {
  body: ModerationReasonDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/users/{id}";
};

export type AdminUserControllerRemoveResponses = {
  200: unknown;
};

export type AdminUserControllerGetData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/users/{id}";
};

export type AdminUserControllerGetResponses = {
  200: unknown;
};

export type AdminUserControllerUpdateData = {
  body: UpdateAdminUserDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/users/{id}";
};

export type AdminUserControllerUpdateResponses = {
  200: unknown;
};

export type AdminUserControllerSuspendData = {
  body: ModerationReasonDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/users/{id}/suspend";
};

export type AdminUserControllerSuspendResponses = {
  200: unknown;
};

export type AdminUserControllerBanData = {
  body: ModerationReasonDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/users/{id}/ban";
};

export type AdminUserControllerBanResponses = {
  200: unknown;
};

export type AdminUserControllerRestoreData = {
  body: ModerationReasonDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/users/{id}/restore";
};

export type AdminUserControllerRestoreResponses = {
  200: unknown;
};

export type AdminUserControllerRevokeRoleData = {
  body: ModerationReasonDto;
  path: {
    id: number;
    role: "Admin" | "Moderator";
  };
  query?: never;
  url: "/admin/users/{id}/roles/{role}";
};

export type AdminUserControllerRevokeRoleErrors = {
  /**
   * Unknown role
   */
  400: unknown;
};

export type AdminUserControllerRevokeRoleResponses = {
  200: AdminUserResponseDto;
};

export type AdminUserControllerRevokeRoleResponse =
  AdminUserControllerRevokeRoleResponses[keyof AdminUserControllerRevokeRoleResponses];

export type AdminUserControllerGrantRoleData = {
  body: ModerationReasonDto;
  path: {
    id: number;
    role: "Admin" | "Moderator";
  };
  query?: never;
  url: "/admin/users/{id}/roles/{role}";
};

export type AdminUserControllerGrantRoleErrors = {
  /**
   * Unknown role
   */
  400: unknown;
};

export type AdminUserControllerGrantRoleResponses = {
  200: AdminUserResponseDto;
};

export type AdminUserControllerGrantRoleResponse =
  AdminUserControllerGrantRoleResponses[keyof AdminUserControllerGrantRoleResponses];

export type AdminUserControllerResetPasswordData = {
  body: ResetPasswordDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/users/{id}/reset-password";
};

export type AdminUserControllerResetPasswordResponses = {
  200: unknown;
};

export type AdminProjectControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    sortBy?:
      | "id"
      | "name"
      | "createdAt"
      | "updatedAt"
      | "publishedAt"
      | "likes"
      | "viewCount";
    order?: "asc" | "desc";
    name?: string;
    status?: "IN_PROGRESS" | "COMPLETED" | "ARCHIVED";
    hidden?: boolean;
    userId?: number;
  };
  url: "/admin/projects";
};

export type AdminProjectControllerListResponses = {
  200: unknown;
};

export type AdminProjectControllerGetData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/projects/{id}";
};

export type AdminProjectControllerGetResponses = {
  200: unknown;
};

export type AdminProjectControllerUpdateData = {
  body: AdminUpdateProjectDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/projects/{id}";
};

export type AdminProjectControllerUpdateResponses = {
  200: unknown;
};

export type AdminProjectControllerHideData = {
  body: ModerationReasonDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/projects/{id}/hide";
};

export type AdminProjectControllerHideResponses = {
  200: unknown;
};

export type AdminProjectControllerRestoreData = {
  body: ModerationReasonDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/projects/{id}/restore";
};

export type AdminProjectControllerRestoreResponses = {
  200: unknown;
};

export type AdminProjectControllerUnpublishData = {
  body: ModerationReasonDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/projects/{id}/unpublish";
};

export type AdminProjectControllerUnpublishResponses = {
  200: unknown;
};

export type AdminCommentControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    sortBy?: "id" | "createdAt";
    order?: "asc" | "desc";
    projectId?: number;
    authorId?: number;
    hidden?: boolean;
    deleted?: boolean;
  };
  url: "/admin/comments";
};

export type AdminCommentControllerListResponses = {
  200: unknown;
};

export type AdminCommentControllerGetData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/comments/{id}";
};

export type AdminCommentControllerGetResponses = {
  200: unknown;
};

export type AdminCommentControllerUpdateData = {
  body: AdminUpdateCommentDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/comments/{id}";
};

export type AdminCommentControllerUpdateResponses = {
  200: unknown;
};

export type AdminCommentControllerHideData = {
  body: ModerationReasonDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/comments/{id}/hide";
};

export type AdminCommentControllerHideResponses = {
  200: unknown;
};

export type AdminCommentControllerRestoreData = {
  body: ModerationReasonDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/comments/{id}/restore";
};

export type AdminCommentControllerRestoreResponses = {
  200: unknown;
};

export type AdminReportControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    sortBy?: "id" | "createdAt" | "updatedAt" | "status";
    order?: "asc" | "desc";
    targetType?: "USER" | "PROJECT" | "COMMENT";
    targetId?: number;
    status?: "OPEN" | "IN_REVIEW" | "RESOLVED" | "DISMISSED";
    reporterId?: number;
  };
  url: "/admin/reports";
};

export type AdminReportControllerListResponses = {
  200: unknown;
};

export type AdminReportControllerGetData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/reports/{id}";
};

export type AdminReportControllerGetResponses = {
  200: unknown;
};

export type AdminReportControllerUpdateData = {
  body: ReportActionDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/reports/{id}";
};

export type AdminReportControllerUpdateResponses = {
  200: unknown;
};

export type AdminReportControllerReviewData = {
  body: ReportActionDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/reports/{id}/review";
};

export type AdminReportControllerReviewResponses = {
  200: unknown;
};

export type AdminReportControllerResolveData = {
  body: ReportActionDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/reports/{id}/resolve";
};

export type AdminReportControllerResolveResponses = {
  200: unknown;
};

export type AdminReportControllerDismissData = {
  body: ReportActionDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/reports/{id}/dismiss";
};

export type AdminReportControllerDismissResponses = {
  200: unknown;
};

export type AdminModerationLogControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    sortBy?: string;
    order?: "asc" | "desc";
    actorId?: number;
    targetType?: "USER" | "PROJECT" | "COMMENT" | "REPORT";
    targetId?: number;
    action?:
      | "SUSPEND_USER"
      | "BAN_USER"
      | "RESTORE_USER"
      | "HIDE_PROJECT"
      | "RESTORE_PROJECT"
      | "UNPUBLISH_PROJECT"
      | "HIDE_COMMENT"
      | "RESTORE_COMMENT"
      | "REVIEW_REPORT"
      | "RESOLVE_REPORT"
      | "DISMISS_REPORT"
      | "ANONYMIZE_USER"
      | "HARD_DELETE_USER"
      | "CREATE_STAFF_USER"
      | "UPDATE_ROLES"
      | "EDIT_USER"
      | "EDIT_PROJECT"
      | "EDIT_COMMENT"
      | "UPDATE_REPORT"
      | "RESET_PASSWORD"
      | "CREATE_ROLE"
      | "RENAME_ROLE"
      | "DELETE_ROLE";
    createdAfter?: string;
    createdBefore?: string;
  };
  url: "/admin/moderation-log";
};

export type AdminModerationLogControllerListResponses = {
  200: unknown;
};

export type AdminModerationLogControllerGetData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/moderation-log/{id}";
};

export type AdminModerationLogControllerGetResponses = {
  200: unknown;
};

export type AdminRoleControllerListData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/admin/roles";
};

export type AdminRoleControllerListResponses = {
  200: unknown;
};

export type AdminRoleControllerCreateData = {
  body: CreateRoleDto;
  path?: never;
  query?: never;
  url: "/admin/roles";
};

export type AdminRoleControllerCreateResponses = {
  201: unknown;
};

export type AdminRoleControllerRemoveData = {
  body: DeleteRoleDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/roles/{id}";
};

export type AdminRoleControllerRemoveResponses = {
  200: unknown;
};

export type AdminRoleControllerRenameData = {
  body: UpdateRoleDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/admin/roles/{id}";
};

export type AdminRoleControllerRenameResponses = {
  200: unknown;
};

export type NotificationsControllerGetWebRtcOfferData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/notifications/webrtc-offer";
};

export type NotificationsControllerGetWebRtcOfferResponses = {
  /**
   * Notification websocket configuration
   */
  200: unknown;
};

export type NotificationsControllerSendTestNotificationData = {
  body: NotificationTestDto;
  path?: never;
  query?: never;
  url: "/notifications/test";
};

export type NotificationsControllerSendTestNotificationResponses = {
  /**
   * Notification created and sent
   */
  200: unknown;
};

export type NotificationsControllerMarkAsReadData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/notifications/{id}/read";
};

export type NotificationsControllerMarkAsReadResponses = {
  /**
   * Notification marked as read
   */
  200: unknown;
};

export type AuthControllerLoginData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type AuthControllerLoginErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Invalid credentials
   */
  401: unknown;
};

export type AuthControllerLoginResponses = {
  /**
   * User logged in successfully
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRegisterData = {
  body: CreateUserDto;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type AuthControllerRegisterErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Cannot register as an admin
   */
  403: unknown;
  /**
   * Email already in use
   */
  409: unknown;
};

export type AuthControllerRegisterResponses = {
  /**
   * User registered successfully
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginWithGoogleCodeData = {
  body: GoogleCodeDto;
  path?: never;
  query?: never;
  url: "/auth/google/code";
};

export type AuthControllerLoginWithGoogleCodeErrors = {
  /**
   * Invalid Google code or code_verifier
   */
  401: unknown;
};

export type AuthControllerLoginWithGoogleCodeResponses = {
  /**
   * Login successful with Google
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerLoginWithGoogleCodeResponse =
  AuthControllerLoginWithGoogleCodeResponses[keyof AuthControllerLoginWithGoogleCodeResponses];

export type AuthControllerLoginWithGithubData = {
  body: GithubLoginDto;
  path?: never;
  query?: never;
  url: "/auth/github";
};

export type AuthControllerLoginWithGithubErrors = {
  /**
   * Invalid or expired GitHub code
   */
  401: unknown;
};

export type AuthControllerLoginWithGithubResponses = {
  /**
   * Login successful with GitHub
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerLoginWithGithubResponse =
  AuthControllerLoginWithGithubResponses[keyof AuthControllerLoginWithGithubResponses];

export type AuthControllerLoginWithMicrosoftData = {
  body: MicrosoftLoginDto;
  path?: never;
  query?: never;
  url: "/auth/microsoft";
};

export type AuthControllerLoginWithMicrosoftErrors = {
  /**
   * Invalid Microsoft ID token
   */
  401: unknown;
};

export type AuthControllerLoginWithMicrosoftResponses = {
  /**
   * Login successful with Microsoft
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerLoginWithMicrosoftResponse =
  AuthControllerLoginWithMicrosoftResponses[keyof AuthControllerLoginWithMicrosoftResponses];

export type AuthControllerRefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/refresh";
};

export type AuthControllerRefreshErrors = {
  /**
   * Refresh token missing or invalid
   */
  401: unknown;
};

export type AuthControllerRefreshResponses = {
  /**
   * Access token refreshed successfully
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerRefreshResponse =
  AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerChangePasswordData = {
  body: ChangePasswordDto;
  path?: never;
  query?: never;
  url: "/auth/password";
};

export type AuthControllerChangePasswordErrors = {
  /**
   * Current password required for non-OAuth accounts
   */
  400: unknown;
  /**
   * Current password incorrect
   */
  401: unknown;
};

export type AuthControllerChangePasswordResponses = {
  /**
   * Password updated successfully
   */
  200: unknown;
};

export type AuthControllerLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/logout";
};

export type AuthControllerLogoutResponses = {
  /**
   * Logout successful
   */
  200: unknown;
};

export type UserControllerGetProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/profile";
};

export type UserControllerGetProfileErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerGetProfileResponses = {
  /**
   * Returns the current user profile
   */
  200: UserProfileResponseDto;
};

export type UserControllerGetProfileResponse =
  UserControllerGetProfileResponses[keyof UserControllerGetProfileResponses];

export type UserControllerUpdateMyProfileData = {
  body: UpdateUserProfileDto;
  path?: never;
  query?: never;
  url: "/users/profile";
};

export type UserControllerUpdateMyProfileErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerUpdateMyProfileResponses = {
  /**
   * User profile updated successfully
   */
  200: PublicUserProfileResponseDto;
};

export type UserControllerUpdateMyProfileResponse =
  UserControllerUpdateMyProfileResponses[keyof UserControllerUpdateMyProfileResponses];

export type UserControllerGetProfilePictureData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}/profile-picture";
};

export type UserControllerGetProfilePictureErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type UserControllerGetProfilePictureResponses = {
  /**
   * Signed cookies and CDN resource URL
   */
  200: SignedCdnResourceDto;
};

export type UserControllerGetProfilePictureResponse =
  UserControllerGetProfilePictureResponses[keyof UserControllerGetProfilePictureResponses];

export type UserControllerUploadProfilePictureData = {
  body: {
    /**
     * Profile picture file
     */
    file?: Blob | File;
  };
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}/profile-picture";
};

export type UserControllerUploadProfilePictureErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerUploadProfilePictureResponses = {
  /**
   * Profile uploaded
   */
  201: unknown;
};

export type UserControllerUploadProfileBackgroundData = {
  body: {
    /**
     * Profile background file
     */
    file?: Blob | File;
  };
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}/profile-background";
};

export type UserControllerUploadProfileBackgroundErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerUploadProfileBackgroundResponses = {
  /**
   * Profile background uploaded
   */
  201: unknown;
};

export type UserControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Filter by nickname
     */
    nickname?: string;
    /**
     * Filter by email
     */
    email?: string;
    /**
     * Sort by field
     */
    sortBy?: "id" | "username" | "email" | "createdAt";
    /**
     * Sort order
     */
    order?: "asc" | "desc";
  };
  url: "/users";
};

export type UserControllerFindAllErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerFindAllResponses = {
  /**
   * Returns paginated list of users
   */
  200: UserListResponseDto;
};

export type UserControllerFindAllResponse =
  UserControllerFindAllResponses[keyof UserControllerFindAllResponses];

export type UserControllerRemoveData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerRemoveErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Insufficient permissions
   */
  403: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UserControllerRemoveResponses = {
  /**
   * User deleted successfully
   */
  200: {
    statusCode?: number;
    message?: string;
  };
};

export type UserControllerRemoveResponse =
  UserControllerRemoveResponses[keyof UserControllerRemoveResponses];

export type UserControllerFindOneData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerFindOneErrors = {
  /**
   * Invalid ID format
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UserControllerFindOneResponses = {
  /**
   * Returns the user
   */
  200: UserSingleResponseDto;
};

export type UserControllerFindOneResponse =
  UserControllerFindOneResponses[keyof UserControllerFindOneResponses];

export type UserControllerUpdateData = {
  body: UpdateUserDto;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerUpdateErrors = {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Insufficient permissions
   */
  403: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UserControllerUpdateResponses = {
  /**
   * User updated successfully
   */
  200: UserSingleResponseDto;
};

export type UserControllerUpdateResponse =
  UserControllerUpdateResponses[keyof UserControllerUpdateResponses];

export type UserPublicControllerGetPublicProfileData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: "/users/public/{id}/profile";
};

export type UserPublicControllerGetPublicProfileErrors = {
  /**
   * User not found
   */
  404: unknown;
};

export type UserPublicControllerGetPublicProfileResponses = {
  /**
   * Returns the public user profile
   */
  200: PublicUserProfileResponseDto;
};

export type UserPublicControllerGetPublicProfileResponse =
  UserPublicControllerGetPublicProfileResponses[keyof UserPublicControllerGetPublicProfileResponses];

export type UserPublicControllerGetPublicProfileByUsernameData = {
  body?: never;
  path: {
    /**
     * Username
     */
    username: string;
  };
  query?: never;
  url: "/users/public/username/{username}/profile";
};

export type UserPublicControllerGetPublicProfileByUsernameErrors = {
  /**
   * User not found
   */
  404: unknown;
};

export type UserPublicControllerGetPublicProfileByUsernameResponses = {
  /**
   * Returns the public user profile
   */
  200: PublicUserProfileResponseDto;
};

export type UserPublicControllerGetPublicProfileByUsernameResponse =
  UserPublicControllerGetPublicProfileByUsernameResponses[keyof UserPublicControllerGetPublicProfileByUsernameResponses];

export type UserPublicControllerGetLikedGamesData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/users/public/{id}/likes";
};

export type UserPublicControllerGetLikedGamesResponses = {
  /**
   * Returns the list of published games liked by the user
   */
  200: Array<ProjectExResponseDto>;
};

export type UserPublicControllerGetLikedGamesResponse =
  UserPublicControllerGetLikedGamesResponses[keyof UserPublicControllerGetLikedGamesResponses];

export type UserPublicControllerGetPublishedGamesData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/users/public/{id}/published-games";
};

export type UserPublicControllerGetPublishedGamesResponses = {
  /**
   * Returns the list of games published by the user
   */
  200: Array<ProjectExResponseDto>;
};

export type UserPublicControllerGetPublishedGamesResponse =
  UserPublicControllerGetPublishedGamesResponses[keyof UserPublicControllerGetPublishedGamesResponses];

export type WorkSessionControllerJoinData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/work-sessions/join/{id}";
};

export type WorkSessionControllerJoinErrors = {
  /**
   * Bad request.
   */
  400: unknown;
};

export type WorkSessionControllerJoinResponses = {
  /**
   * The work session has been successfully created.
   */
  201: JoinWorkSessionDto;
};

export type WorkSessionControllerJoinResponse =
  WorkSessionControllerJoinResponses[keyof WorkSessionControllerJoinResponses];

export type WorkSessionControllerLeaveData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/work-sessions/leave/{id}";
};

export type WorkSessionControllerLeaveErrors = {
  /**
   * Bad request.
   */
  400: unknown;
};

export type WorkSessionControllerLeaveResponses = {
  /**
   * Successfully left the work session.
   */
  204: void;
};

export type WorkSessionControllerLeaveResponse =
  WorkSessionControllerLeaveResponses[keyof WorkSessionControllerLeaveResponses];

export type WorkSessionControllerKickData = {
  body: KickWorkSessionDto;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/work-sessions/kick/{id}";
};

export type WorkSessionControllerKickErrors = {
  /**
   * Bad request.
   */
  400: unknown;
};

export type WorkSessionControllerKickResponses = {
  /**
   * Successfully left the work session.
   */
  204: void;
};

export type WorkSessionControllerKickResponse =
  WorkSessionControllerKickResponses[keyof WorkSessionControllerKickResponses];

export type WorkSessionControllerGetInfoData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: "/work-sessions/info/{id}";
};

export type WorkSessionControllerGetInfoErrors = {
  /**
   * Work session not found.
   */
  404: unknown;
};

export type WorkSessionControllerGetInfoResponses = {
  /**
   * Work session info retrieved successfully.
   */
  200: FetchWorkSessionDto;
};

export type WorkSessionControllerGetInfoResponse =
  WorkSessionControllerGetInfoResponses[keyof WorkSessionControllerGetInfoResponses];
