// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AuthControllerChangePasswordData,
  AuthControllerChangePasswordErrors,
  AuthControllerChangePasswordResponses,
  AuthControllerLoginData,
  AuthControllerLoginErrors,
  AuthControllerLoginResponses,
  AuthControllerLoginWithGithubData,
  AuthControllerLoginWithGithubErrors,
  AuthControllerLoginWithGithubResponses,
  AuthControllerLoginWithGoogleCodeData,
  AuthControllerLoginWithGoogleCodeErrors,
  AuthControllerLoginWithGoogleCodeResponses,
  AuthControllerLoginWithMicrosoftData,
  AuthControllerLoginWithMicrosoftErrors,
  AuthControllerLoginWithMicrosoftResponses,
  AuthControllerLogoutData,
  AuthControllerLogoutResponses,
  AuthControllerRefreshData,
  AuthControllerRefreshErrors,
  AuthControllerRefreshResponses,
  AuthControllerRegisterData,
  AuthControllerRegisterErrors,
  AuthControllerRegisterResponses,
  MultiplayerControllerCreateData,
  MultiplayerControllerCreateResponses,
  MultiplayerControllerGetData,
  MultiplayerControllerGetResponses,
  MultiplayerControllerJoinByCodeData,
  MultiplayerControllerJoinByCodeResponses,
  MultiplayerControllerJoinData,
  MultiplayerControllerJoinResponses,
  MultiplayerControllerLeaveData,
  MultiplayerControllerLeaveResponses,
  MultiplayerControllerListData,
  MultiplayerControllerListResponses,
  MultiplayerControllerRefreshTicketData,
  MultiplayerControllerRefreshTicketResponses,
  MultiplayerControllerRemoveData,
  MultiplayerControllerRemoveResponses,
  MultiplayerControllerUpdateData,
  MultiplayerControllerUpdateResponses,
  NotificationsControllerGetWebRtcOfferData,
  NotificationsControllerGetWebRtcOfferResponses,
  NotificationsControllerMarkAsReadData,
  NotificationsControllerMarkAsReadResponses,
  NotificationsControllerSendTestNotificationData,
  NotificationsControllerSendTestNotificationResponses,
  ProjectCommentControllerCreateCommentData,
  ProjectCommentControllerCreateCommentResponses,
  ProjectCommentControllerCreateReplyData,
  ProjectCommentControllerCreateReplyResponses,
  ProjectCommentControllerDeleteCommentData,
  ProjectCommentControllerDeleteCommentResponses,
  ProjectCommentControllerGetCommentsData,
  ProjectCommentControllerGetCommentsResponses,
  ProjectCommentControllerUpdateCommentData,
  ProjectCommentControllerUpdateCommentResponses,
  ProjectControllerAddCollaboratorData,
  ProjectControllerAddCollaboratorErrors,
  ProjectControllerAddCollaboratorResponses,
  ProjectControllerCountProjectsData,
  ProjectControllerCountProjectsResponses,
  ProjectControllerCountReleasedProjectsData,
  ProjectControllerCountReleasedProjectsResponses,
  ProjectControllerCreateData,
  ProjectControllerCreateErrors,
  ProjectControllerCreateResponses,
  ProjectControllerDeleteCheckpointData,
  ProjectControllerDeleteCheckpointErrors,
  ProjectControllerDeleteCheckpointResponses,
  ProjectControllerFetchProjectContentData,
  ProjectControllerFetchProjectContentErrors,
  ProjectControllerFetchProjectContentResponses,
  ProjectControllerFindAllData,
  ProjectControllerFindAllErrors,
  ProjectControllerFindAllResponses,
  ProjectControllerFindOneData,
  ProjectControllerFindOneErrors,
  ProjectControllerFindOneResponses,
  ProjectControllerForkData,
  ProjectControllerForkErrors,
  ProjectControllerForkResponses,
  ProjectControllerGetAllReleasesData,
  ProjectControllerGetAllReleasesResponses,
  ProjectControllerGetCheckpointData,
  ProjectControllerGetCheckpointErrors,
  ProjectControllerGetCheckpointResponses,
  ProjectControllerGetCheckpointsData,
  ProjectControllerGetCheckpointsErrors,
  ProjectControllerGetCheckpointsResponses,
  ProjectControllerGetLikeStatusData,
  ProjectControllerGetLikeStatusResponses,
  ProjectControllerGetPaginatedReleasesData,
  ProjectControllerGetPaginatedReleasesResponses,
  ProjectControllerGetProjectImageData,
  ProjectControllerGetProjectImageErrors,
  ProjectControllerGetProjectImageResponses,
  ProjectControllerGetPublishedProjectImageData,
  ProjectControllerGetPublishedProjectImageErrors,
  ProjectControllerGetPublishedProjectImageResponses,
  ProjectControllerGetReleaseContentData,
  ProjectControllerGetReleaseContentResponses,
  ProjectControllerGetReleaseContentUrlData,
  ProjectControllerGetReleaseContentUrlResponses,
  ProjectControllerGetReleaseData,
  ProjectControllerGetReleaseResponses,
  ProjectControllerGetVersionData,
  ProjectControllerGetVersionErrors,
  ProjectControllerGetVersionResponses,
  ProjectControllerGetVersionsData,
  ProjectControllerGetVersionsErrors,
  ProjectControllerGetVersionsResponses,
  ProjectControllerLikeProjectData,
  ProjectControllerLikeProjectResponses,
  ProjectControllerPublishData,
  ProjectControllerPublishErrors,
  ProjectControllerPublishResponses,
  ProjectControllerRegisterReleaseViewData,
  ProjectControllerRegisterReleaseViewResponses,
  ProjectControllerRemoveCollaboratorData,
  ProjectControllerRemoveCollaboratorErrors,
  ProjectControllerRemoveCollaboratorResponses,
  ProjectControllerRemoveData,
  ProjectControllerRemoveErrors,
  ProjectControllerRemoveResponses,
  ProjectControllerSaveCheckpointData,
  ProjectControllerSaveCheckpointErrors,
  ProjectControllerSaveCheckpointResponses,
  ProjectControllerSaveProjectContentData,
  ProjectControllerSaveProjectContentErrors,
  ProjectControllerSaveProjectContentResponses,
  ProjectControllerUnlikeProjectData,
  ProjectControllerUnlikeProjectResponses,
  ProjectControllerUnpublishData,
  ProjectControllerUnpublishErrors,
  ProjectControllerUnpublishResponses,
  ProjectControllerUpdateData,
  ProjectControllerUpdateErrors,
  ProjectControllerUpdateReleaseData,
  ProjectControllerUpdateReleaseErrors,
  ProjectControllerUpdateReleaseResponses,
  ProjectControllerUpdateResponses,
  ProjectControllerUploadProjectImageData,
  ProjectControllerUploadProjectImageErrors,
  ProjectControllerUploadProjectImageResponses,
  UserControllerFindAllData,
  UserControllerFindAllErrors,
  UserControllerFindAllResponses,
  UserControllerFindOneData,
  UserControllerFindOneErrors,
  UserControllerFindOneResponses,
  UserControllerGetProfileData,
  UserControllerGetProfileErrors,
  UserControllerGetProfilePictureData,
  UserControllerGetProfilePictureErrors,
  UserControllerGetProfilePictureResponses,
  UserControllerGetProfileResponses,
  UserControllerRemoveData,
  UserControllerRemoveErrors,
  UserControllerRemoveResponses,
  UserControllerUpdateData,
  UserControllerUpdateErrors,
  UserControllerUpdateMyProfileData,
  UserControllerUpdateMyProfileErrors,
  UserControllerUpdateMyProfileResponses,
  UserControllerUpdateResponses,
  UserControllerUploadProfileBackgroundData,
  UserControllerUploadProfileBackgroundErrors,
  UserControllerUploadProfileBackgroundResponses,
  UserControllerUploadProfilePictureData,
  UserControllerUploadProfilePictureErrors,
  UserControllerUploadProfilePictureResponses,
  UserPublicControllerGetLikedGamesData,
  UserPublicControllerGetLikedGamesResponses,
  UserPublicControllerGetPublicProfileByUsernameData,
  UserPublicControllerGetPublicProfileByUsernameErrors,
  UserPublicControllerGetPublicProfileByUsernameResponses,
  UserPublicControllerGetPublicProfileData,
  UserPublicControllerGetPublicProfileErrors,
  UserPublicControllerGetPublicProfileResponses,
  UserPublicControllerGetPublishedGamesData,
  UserPublicControllerGetPublishedGamesResponses,
  WorkSessionControllerGetInfoData,
  WorkSessionControllerGetInfoErrors,
  WorkSessionControllerGetInfoResponses,
  WorkSessionControllerJoinData,
  WorkSessionControllerJoinErrors,
  WorkSessionControllerJoinResponses,
  WorkSessionControllerKickData,
  WorkSessionControllerKickErrors,
  WorkSessionControllerKickResponses,
  WorkSessionControllerLeaveData,
  WorkSessionControllerLeaveErrors,
  WorkSessionControllerLeaveResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get all released projects
 */
export const projectControllerGetAllReleases = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectControllerGetAllReleasesData, ThrowOnError>,
): RequestResult<ProjectControllerGetAllReleasesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ProjectControllerGetAllReleasesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/releases',
    ...options,
  });

/**
 * Get released projects with pagination
 */
export const projectControllerGetPaginatedReleases = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectControllerGetPaginatedReleasesData, ThrowOnError>,
): RequestResult<ProjectControllerGetPaginatedReleasesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ProjectControllerGetPaginatedReleasesResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/releases/paginated',
    ...options,
  });

/**
 * Count released projects with filters
 */
export const projectControllerCountReleasedProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectControllerCountReleasedProjectsData, ThrowOnError>,
): RequestResult<ProjectControllerCountReleasedProjectsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ProjectControllerCountReleasedProjectsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/releases/count',
    ...options,
  });

/**
 * Get project release version
 */
export const projectControllerGetRelease = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetReleaseData, ThrowOnError>,
): RequestResult<ProjectControllerGetReleaseResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<ProjectControllerGetReleaseResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/releases/{id}',
    ...options,
  });

/**
 * Get project release version
 */
export const projectControllerGetReleaseContent = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetReleaseContentData, ThrowOnError>,
): RequestResult<ProjectControllerGetReleaseContentResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    ProjectControllerGetReleaseContentResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/releases/{id}/content',
    ...options,
  });

/**
 * Get signed CDN URL for a release
 */
export const projectControllerGetReleaseContentUrl = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetReleaseContentUrlData, ThrowOnError>,
): RequestResult<ProjectControllerGetReleaseContentUrlResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    ProjectControllerGetReleaseContentUrlResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/releases/{id}/content-url',
    ...options,
  });

/**
 * Retrieve the paginated list of projects
 */
export const projectControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectControllerFindAllData, ThrowOnError>,
): RequestResult<ProjectControllerFindAllResponses, ProjectControllerFindAllErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ProjectControllerFindAllResponses,
    ProjectControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects',
    ...options,
  });

/**
 * Create a new project
 */
export const projectControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerCreateData, ThrowOnError>,
): RequestResult<ProjectControllerCreateResponses, ProjectControllerCreateErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ProjectControllerCreateResponses,
    ProjectControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Count the user's projects with filters
 */
export const projectControllerCountProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectControllerCountProjectsData, ThrowOnError>,
): RequestResult<ProjectControllerCountProjectsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ProjectControllerCountProjectsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/count',
    ...options,
  });

/**
 * Delete a project
 */
export const projectControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerRemoveData, ThrowOnError>,
): RequestResult<ProjectControllerRemoveResponses, ProjectControllerRemoveErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    ProjectControllerRemoveResponses,
    ProjectControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}',
    ...options,
  });

/**
 * Retrieve a single project
 */
export const projectControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerFindOneData, ThrowOnError>,
): RequestResult<ProjectControllerFindOneResponses, ProjectControllerFindOneErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ProjectControllerFindOneResponses,
    ProjectControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}',
    ...options,
  });

/**
 * Update an existing project
 */
export const projectControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerUpdateData, ThrowOnError>,
): RequestResult<ProjectControllerUpdateResponses, ProjectControllerUpdateErrors, ThrowOnError> =>
  (options.client ?? client).put<
    ProjectControllerUpdateResponses,
    ProjectControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Fork a published project
 */
export const projectControllerFork = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerForkData, ThrowOnError>,
): RequestResult<ProjectControllerForkResponses, ProjectControllerForkErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ProjectControllerForkResponses,
    ProjectControllerForkErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/fork',
    ...options,
  });

/**
 * Add a new collaborator
 *
 * Add a collaborator to a project by providing either userId, username, or email. At least one must be provided.
 */
export const projectControllerAddCollaborator = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerAddCollaboratorData, ThrowOnError>,
): RequestResult<
  ProjectControllerAddCollaboratorResponses,
  ProjectControllerAddCollaboratorErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    ProjectControllerAddCollaboratorResponses,
    ProjectControllerAddCollaboratorErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/add-collaborator',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove a collaborator
 *
 * Remove a collaborator from a project by providing either userId, username, or email. At least one must be provided.
 */
export const projectControllerRemoveCollaborator = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerRemoveCollaboratorData, ThrowOnError>,
): RequestResult<
  ProjectControllerRemoveCollaboratorResponses,
  ProjectControllerRemoveCollaboratorErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    ProjectControllerRemoveCollaboratorResponses,
    ProjectControllerRemoveCollaboratorErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/remove-collaborator',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Save project's content (Upload)
 */
export const projectControllerSaveProjectContent = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerSaveProjectContentData, ThrowOnError>,
): RequestResult<
  ProjectControllerSaveProjectContentResponses,
  ProjectControllerSaveProjectContentErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    ProjectControllerSaveProjectContentResponses,
    ProjectControllerSaveProjectContentErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/saveContent',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Get CDN URL for project image (authenticated, any project status)
 */
export const projectControllerGetProjectImage = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetProjectImageData, ThrowOnError>,
): RequestResult<
  ProjectControllerGetProjectImageResponses,
  ProjectControllerGetProjectImageErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectControllerGetProjectImageResponses,
    ProjectControllerGetProjectImageErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/image',
    ...options,
  });

/**
 * Upload project image
 */
export const projectControllerUploadProjectImage = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerUploadProjectImageData, ThrowOnError>,
): RequestResult<
  ProjectControllerUploadProjectImageResponses,
  ProjectControllerUploadProjectImageErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectControllerUploadProjectImageResponses,
    ProjectControllerUploadProjectImageErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/image',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Get public CDN URL for a published project's image
 */
export const projectControllerGetPublishedProjectImage = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetPublishedProjectImageData, ThrowOnError>,
): RequestResult<
  ProjectControllerGetPublishedProjectImageResponses,
  ProjectControllerGetPublishedProjectImageErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectControllerGetPublishedProjectImageResponses,
    ProjectControllerGetPublishedProjectImageErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/public/{id}/image',
    ...options,
  });

/**
 * Fetch project's content
 */
export const projectControllerFetchProjectContent = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerFetchProjectContentData, ThrowOnError>,
): RequestResult<
  ProjectControllerFetchProjectContentResponses,
  ProjectControllerFetchProjectContentErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectControllerFetchProjectContentResponses,
    ProjectControllerFetchProjectContentErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/fetchContent',
    ...options,
  });

/**
 * Save project's checkpoint
 */
export const projectControllerSaveCheckpoint = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerSaveCheckpointData, ThrowOnError>,
): RequestResult<
  ProjectControllerSaveCheckpointResponses,
  ProjectControllerSaveCheckpointErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectControllerSaveCheckpointResponses,
    ProjectControllerSaveCheckpointErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/saveCheckpoint/{name}',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Delete project's checkpoint
 */
export const projectControllerDeleteCheckpoint = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerDeleteCheckpointData, ThrowOnError>,
): RequestResult<
  ProjectControllerDeleteCheckpointResponses,
  ProjectControllerDeleteCheckpointErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    ProjectControllerDeleteCheckpointResponses,
    ProjectControllerDeleteCheckpointErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/deleteCheckpoint/{name}',
    ...options,
  });

/**
 * Publish project
 */
export const projectControllerPublish = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerPublishData, ThrowOnError>,
): RequestResult<ProjectControllerPublishResponses, ProjectControllerPublishErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ProjectControllerPublishResponses,
    ProjectControllerPublishErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/publish',
    ...options,
  });

/**
 * Unpublish project
 */
export const projectControllerUnpublish = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerUnpublishData, ThrowOnError>,
): RequestResult<
  ProjectControllerUnpublishResponses,
  ProjectControllerUnpublishErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectControllerUnpublishResponses,
    ProjectControllerUnpublishErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/unpublish',
    ...options,
  });

/**
 * Get project versions
 */
export const projectControllerGetVersions = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetVersionsData, ThrowOnError>,
): RequestResult<
  ProjectControllerGetVersionsResponses,
  ProjectControllerGetVersionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectControllerGetVersionsResponses,
    ProjectControllerGetVersionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/versions',
    ...options,
  });

/**
 * Get project checkpoints
 */
export const projectControllerGetCheckpoints = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetCheckpointsData, ThrowOnError>,
): RequestResult<
  ProjectControllerGetCheckpointsResponses,
  ProjectControllerGetCheckpointsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectControllerGetCheckpointsResponses,
    ProjectControllerGetCheckpointsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/checkpoints',
    ...options,
  });

/**
 * Fetch a project version
 */
export const projectControllerGetVersion = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetVersionData, ThrowOnError>,
): RequestResult<
  ProjectControllerGetVersionResponses,
  ProjectControllerGetVersionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectControllerGetVersionResponses,
    ProjectControllerGetVersionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/versions/{version}',
    ...options,
  });

/**
 * Fetch a project checkpoint
 */
export const projectControllerGetCheckpoint = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetCheckpointData, ThrowOnError>,
): RequestResult<
  ProjectControllerGetCheckpointResponses,
  ProjectControllerGetCheckpointErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectControllerGetCheckpointResponses,
    ProjectControllerGetCheckpointErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/checkpoints/{checkpoint}',
    ...options,
  });

/**
 * Unlike a published project (authenticated users only)
 */
export const projectControllerUnlikeProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerUnlikeProjectData, ThrowOnError>,
): RequestResult<ProjectControllerUnlikeProjectResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<ProjectControllerUnlikeProjectResponses, unknown, ThrowOnError>(
    {
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/projects/releases/{id}/like',
      ...options,
    },
  );

/**
 * Like a published project (idempotent, authenticated users only)
 */
export const projectControllerLikeProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerLikeProjectData, ThrowOnError>,
): RequestResult<ProjectControllerLikeProjectResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<ProjectControllerLikeProjectResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/releases/{id}/like',
    ...options,
  });

/**
 * Get like status for a project (authenticated users only)
 */
export const projectControllerGetLikeStatus = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetLikeStatusData, ThrowOnError>,
): RequestResult<ProjectControllerGetLikeStatusResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<ProjectControllerGetLikeStatusResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/releases/{id}/like-status',
    ...options,
  });

/**
 * Register a play view for a published project
 */
export const projectControllerRegisterReleaseView = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerRegisterReleaseViewData, ThrowOnError>,
): RequestResult<ProjectControllerRegisterReleaseViewResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    ProjectControllerRegisterReleaseViewResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/releases/{id}/view',
    ...options,
  });

/**
 * Update an already published project's release content
 */
export const projectControllerUpdateRelease = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerUpdateReleaseData, ThrowOnError>,
): RequestResult<
  ProjectControllerUpdateReleaseResponses,
  ProjectControllerUpdateReleaseErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectControllerUpdateReleaseResponses,
    ProjectControllerUpdateReleaseErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/update-release',
    ...options,
  });

/**
 * List game sessions for a project, from the caller's perspective
 */
export const multiplayerControllerList = <ThrowOnError extends boolean = false>(
  options: Options<MultiplayerControllerListData, ThrowOnError>,
): RequestResult<MultiplayerControllerListResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<MultiplayerControllerListResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/game-sessions',
    ...options,
  });

/**
 * Create a new game session, with the caller as host
 */
export const multiplayerControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<MultiplayerControllerCreateData, ThrowOnError>,
): RequestResult<MultiplayerControllerCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<MultiplayerControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/game-sessions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Join an invite-code game session by its code
 */
export const multiplayerControllerJoinByCode = <ThrowOnError extends boolean = false>(
  options: Options<MultiplayerControllerJoinByCodeData, ThrowOnError>,
): RequestResult<MultiplayerControllerJoinByCodeResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<MultiplayerControllerJoinByCodeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/game-sessions/join-by-code',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Close/delete a game session (host only)
 */
export const multiplayerControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<MultiplayerControllerRemoveData, ThrowOnError>,
): RequestResult<MultiplayerControllerRemoveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<MultiplayerControllerRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/game-sessions/{sessionId}',
    ...options,
  });

/**
 * Fetch a single game session
 */
export const multiplayerControllerGet = <ThrowOnError extends boolean = false>(
  options: Options<MultiplayerControllerGetData, ThrowOnError>,
): RequestResult<MultiplayerControllerGetResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<MultiplayerControllerGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/game-sessions/{sessionId}',
    ...options,
  });

/**
 * Update game session settings (host only)
 */
export const multiplayerControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<MultiplayerControllerUpdateData, ThrowOnError>,
): RequestResult<MultiplayerControllerUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<MultiplayerControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/game-sessions/{sessionId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Join a game session as a player
 */
export const multiplayerControllerJoin = <ThrowOnError extends boolean = false>(
  options: Options<MultiplayerControllerJoinData, ThrowOnError>,
): RequestResult<MultiplayerControllerJoinResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<MultiplayerControllerJoinResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/game-sessions/{sessionId}/join',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Leave a game session as a player
 */
export const multiplayerControllerLeave = <ThrowOnError extends boolean = false>(
  options: Options<MultiplayerControllerLeaveData, ThrowOnError>,
): RequestResult<MultiplayerControllerLeaveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<MultiplayerControllerLeaveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/game-sessions/{sessionId}/leave',
    ...options,
  });

/**
 * Mint a fresh connection ticket for the caller's session
 */
export const multiplayerControllerRefreshTicket = <ThrowOnError extends boolean = false>(
  options: Options<MultiplayerControllerRefreshTicketData, ThrowOnError>,
): RequestResult<MultiplayerControllerRefreshTicketResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    MultiplayerControllerRefreshTicketResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/game-sessions/{sessionId}/ticket',
    ...options,
  });

/**
 * Get comments for a project
 */
export const projectCommentControllerGetComments = <ThrowOnError extends boolean = false>(
  options: Options<ProjectCommentControllerGetCommentsData, ThrowOnError>,
): RequestResult<ProjectCommentControllerGetCommentsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    ProjectCommentControllerGetCommentsResponses,
    unknown,
    ThrowOnError
  >({ url: '/projects/{projectId}/comments', ...options });

/**
 * Create a comment on a project
 */
export const projectCommentControllerCreateComment = <ThrowOnError extends boolean = false>(
  options: Options<ProjectCommentControllerCreateCommentData, ThrowOnError>,
): RequestResult<ProjectCommentControllerCreateCommentResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    ProjectCommentControllerCreateCommentResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{projectId}/comments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Reply to a comment
 */
export const projectCommentControllerCreateReply = <ThrowOnError extends boolean = false>(
  options: Options<ProjectCommentControllerCreateReplyData, ThrowOnError>,
): RequestResult<ProjectCommentControllerCreateReplyResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    ProjectCommentControllerCreateReplyResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{projectId}/comments/{commentId}/reply',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a comment
 */
export const projectCommentControllerDeleteComment = <ThrowOnError extends boolean = false>(
  options: Options<ProjectCommentControllerDeleteCommentData, ThrowOnError>,
): RequestResult<ProjectCommentControllerDeleteCommentResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<
    ProjectCommentControllerDeleteCommentResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{projectId}/comments/{commentId}',
    ...options,
  });

/**
 * Edit a comment
 */
export const projectCommentControllerUpdateComment = <ThrowOnError extends boolean = false>(
  options: Options<ProjectCommentControllerUpdateCommentData, ThrowOnError>,
): RequestResult<ProjectCommentControllerUpdateCommentResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<
    ProjectCommentControllerUpdateCommentResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{projectId}/comments/{commentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get notification websocket configuration
 */
export const notificationsControllerGetWebRtcOffer = <ThrowOnError extends boolean = false>(
  options?: Options<NotificationsControllerGetWebRtcOfferData, ThrowOnError>,
): RequestResult<NotificationsControllerGetWebRtcOfferResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    NotificationsControllerGetWebRtcOfferResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/notifications/webrtc-offer',
    ...options,
  });

/**
 * Send a test notification to the current user
 */
export const notificationsControllerSendTestNotification = <ThrowOnError extends boolean = false>(
  options: Options<NotificationsControllerSendTestNotificationData, ThrowOnError>,
): RequestResult<NotificationsControllerSendTestNotificationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    NotificationsControllerSendTestNotificationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/notifications/test',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * set one notification as read
 */
export const notificationsControllerMarkAsRead = <ThrowOnError extends boolean = false>(
  options: Options<NotificationsControllerMarkAsReadData, ThrowOnError>,
): RequestResult<NotificationsControllerMarkAsReadResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<
    NotificationsControllerMarkAsReadResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/notifications/{id}/read',
    ...options,
  });

/**
 * Authenticate a user and return an access token
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>,
): RequestResult<AuthControllerLoginResponses, AuthControllerLoginErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthControllerLoginResponses,
    AuthControllerLoginErrors,
    ThrowOnError
  >({
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Register a new user and return an access token
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRegisterData, ThrowOnError>,
): RequestResult<AuthControllerRegisterResponses, AuthControllerRegisterErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthControllerRegisterResponses,
    AuthControllerRegisterErrors,
    ThrowOnError
  >({
    url: '/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Authenticate with Google authorization code + PKCE
 */
export const authControllerLoginWithGoogleCode = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginWithGoogleCodeData, ThrowOnError>,
): RequestResult<
  AuthControllerLoginWithGoogleCodeResponses,
  AuthControllerLoginWithGoogleCodeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthControllerLoginWithGoogleCodeResponses,
    AuthControllerLoginWithGoogleCodeErrors,
    ThrowOnError
  >({
    url: '/auth/google/code',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Authenticate with GitHub OAuth authorization code
 */
export const authControllerLoginWithGithub = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginWithGithubData, ThrowOnError>,
): RequestResult<
  AuthControllerLoginWithGithubResponses,
  AuthControllerLoginWithGithubErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthControllerLoginWithGithubResponses,
    AuthControllerLoginWithGithubErrors,
    ThrowOnError
  >({
    url: '/auth/github',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Authenticate with Microsoft ID token
 */
export const authControllerLoginWithMicrosoft = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginWithMicrosoftData, ThrowOnError>,
): RequestResult<
  AuthControllerLoginWithMicrosoftResponses,
  AuthControllerLoginWithMicrosoftErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthControllerLoginWithMicrosoftResponses,
    AuthControllerLoginWithMicrosoftErrors,
    ThrowOnError
  >({
    url: '/auth/microsoft',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Refresh the access token using refresh token cookie
 */
export const authControllerRefresh = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerRefreshData, ThrowOnError>,
): RequestResult<AuthControllerRefreshResponses, AuthControllerRefreshErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    AuthControllerRefreshResponses,
    AuthControllerRefreshErrors,
    ThrowOnError
  >({ url: '/auth/refresh', ...options });

/**
 * Change password, OAuth users can set one without providing a current password
 */
export const authControllerChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerChangePasswordData, ThrowOnError>,
): RequestResult<
  AuthControllerChangePasswordResponses,
  AuthControllerChangePasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AuthControllerChangePasswordResponses,
    AuthControllerChangePasswordErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove refresh token cookie
 */
export const authControllerLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerLogoutData, ThrowOnError>,
): RequestResult<AuthControllerLogoutResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<AuthControllerLogoutResponses, unknown, ThrowOnError>({
    url: '/auth/logout',
    ...options,
  });

/**
 * Get current user profile
 */
export const userControllerGetProfile = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerGetProfileData, ThrowOnError>,
): RequestResult<UserControllerGetProfileResponses, UserControllerGetProfileErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    UserControllerGetProfileResponses,
    UserControllerGetProfileErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/profile',
    ...options,
  });

/**
 * Update current user profile
 */
export const userControllerUpdateMyProfile = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateMyProfileData, ThrowOnError>,
): RequestResult<
  UserControllerUpdateMyProfileResponses,
  UserControllerUpdateMyProfileErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UserControllerUpdateMyProfileResponses,
    UserControllerUpdateMyProfileErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get signed CDN access to a user's profile picture
 */
export const userControllerGetProfilePicture = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerGetProfilePictureData, ThrowOnError>,
): RequestResult<
  UserControllerGetProfilePictureResponses,
  UserControllerGetProfilePictureErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    UserControllerGetProfilePictureResponses,
    UserControllerGetProfilePictureErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}/profile-picture',
    ...options,
  });

/**
 * Upload a user's profile picture
 */
export const userControllerUploadProfilePicture = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUploadProfilePictureData, ThrowOnError>,
): RequestResult<
  UserControllerUploadProfilePictureResponses,
  UserControllerUploadProfilePictureErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UserControllerUploadProfilePictureResponses,
    UserControllerUploadProfilePictureErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}/profile-picture',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Upload a user's profile background
 */
export const userControllerUploadProfileBackground = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUploadProfileBackgroundData, ThrowOnError>,
): RequestResult<
  UserControllerUploadProfileBackgroundResponses,
  UserControllerUploadProfileBackgroundErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UserControllerUploadProfileBackgroundResponses,
    UserControllerUploadProfileBackgroundErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}/profile-background',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Get all users with pagination and filtering
 */
export const userControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerFindAllData, ThrowOnError>,
): RequestResult<UserControllerFindAllResponses, UserControllerFindAllErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    UserControllerFindAllResponses,
    UserControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options,
  });

/**
 * Delete a user by ID
 */
export const userControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerRemoveData, ThrowOnError>,
): RequestResult<UserControllerRemoveResponses, UserControllerRemoveErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    UserControllerRemoveResponses,
    UserControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}',
    ...options,
  });

/**
 * Get a user by ID
 */
export const userControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerFindOneData, ThrowOnError>,
): RequestResult<UserControllerFindOneResponses, UserControllerFindOneErrors, ThrowOnError> =>
  (options.client ?? client).get<
    UserControllerFindOneResponses,
    UserControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}',
    ...options,
  });

/**
 * Update a user by ID
 */
export const userControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateData, ThrowOnError>,
): RequestResult<UserControllerUpdateResponses, UserControllerUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    UserControllerUpdateResponses,
    UserControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a public user profile by ID
 */
export const userPublicControllerGetPublicProfile = <ThrowOnError extends boolean = false>(
  options: Options<UserPublicControllerGetPublicProfileData, ThrowOnError>,
): RequestResult<
  UserPublicControllerGetPublicProfileResponses,
  UserPublicControllerGetPublicProfileErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    UserPublicControllerGetPublicProfileResponses,
    UserPublicControllerGetPublicProfileErrors,
    ThrowOnError
  >({ url: '/users/public/{id}/profile', ...options });

/**
 * Get a public user profile by username
 */
export const userPublicControllerGetPublicProfileByUsername = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UserPublicControllerGetPublicProfileByUsernameData, ThrowOnError>,
): RequestResult<
  UserPublicControllerGetPublicProfileByUsernameResponses,
  UserPublicControllerGetPublicProfileByUsernameErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    UserPublicControllerGetPublicProfileByUsernameResponses,
    UserPublicControllerGetPublicProfileByUsernameErrors,
    ThrowOnError
  >({ url: '/users/public/username/{username}/profile', ...options });

/**
 * Get a user's liked published games
 */
export const userPublicControllerGetLikedGames = <ThrowOnError extends boolean = false>(
  options: Options<UserPublicControllerGetLikedGamesData, ThrowOnError>,
): RequestResult<UserPublicControllerGetLikedGamesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<UserPublicControllerGetLikedGamesResponses, unknown, ThrowOnError>(
    { url: '/users/public/{id}/likes', ...options },
  );

/**
 * Get a user's published games
 */
export const userPublicControllerGetPublishedGames = <ThrowOnError extends boolean = false>(
  options: Options<UserPublicControllerGetPublishedGamesData, ThrowOnError>,
): RequestResult<UserPublicControllerGetPublishedGamesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    UserPublicControllerGetPublishedGamesResponses,
    unknown,
    ThrowOnError
  >({ url: '/users/public/{id}/published-games', ...options });

/**
 * Join a work session
 */
export const workSessionControllerJoin = <ThrowOnError extends boolean = false>(
  options: Options<WorkSessionControllerJoinData, ThrowOnError>,
): RequestResult<
  WorkSessionControllerJoinResponses,
  WorkSessionControllerJoinErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    WorkSessionControllerJoinResponses,
    WorkSessionControllerJoinErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/work-sessions/join/{id}',
    ...options,
  });

/**
 * Leave a work session
 */
export const workSessionControllerLeave = <ThrowOnError extends boolean = false>(
  options: Options<WorkSessionControllerLeaveData, ThrowOnError>,
): RequestResult<
  WorkSessionControllerLeaveResponses,
  WorkSessionControllerLeaveErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    WorkSessionControllerLeaveResponses,
    WorkSessionControllerLeaveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/work-sessions/leave/{id}',
    ...options,
  });

/**
 * Kick user from work session
 */
export const workSessionControllerKick = <ThrowOnError extends boolean = false>(
  options: Options<WorkSessionControllerKickData, ThrowOnError>,
): RequestResult<
  WorkSessionControllerKickResponses,
  WorkSessionControllerKickErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    WorkSessionControllerKickResponses,
    WorkSessionControllerKickErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/work-sessions/kick/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get work session info
 */
export const workSessionControllerGetInfo = <ThrowOnError extends boolean = false>(
  options: Options<WorkSessionControllerGetInfoData, ThrowOnError>,
): RequestResult<
  WorkSessionControllerGetInfoResponses,
  WorkSessionControllerGetInfoErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    WorkSessionControllerGetInfoResponses,
    WorkSessionControllerGetInfoErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/work-sessions/info/{id}',
    ...options,
  });
