// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type AiConnectionResponseDto = {
  token: string;
  expiresAt: string;
};

export type AiContextDto = {
  /**
   * Editor context, never executable instructions
   */
  content: {
    [key: string]: unknown;
  };
};

export type AiProposalResponseDto = {
  id: string;
  projectId: number;
  userId: number;
  title: string;
  summary: string;
  snapshotHash: string;
  operations: Array<{
    [key: string]: unknown;
  }>;
  contentHash: string;
  status: string;
  reviewedBy: number | null;
  revertsId: string | null;
  inverse: Array<{
    [key: string]: unknown;
  }> | null;
  createdAt: string;
  updatedAt: string;
};

export type AiReviewDto = {
  decision: 'APPROVED' | 'REJECTED';
  contentHash: string;
};

export type AiAckDto = {
  editorId: string;
  snapshot: string;
};

export type AiStartDto = {
  decision: 'APPROVED' | 'REJECTED';
  contentHash: string;
  participants: Array<string>;
};

export type AiBarrierResponseDto = {
  id: string;
  projectId: number;
  proposalId: string;
  status: string;
  expected: Array<string>;
  result: string | null;
  violation: string | null;
  lateUpdates: Array<string>;
  startedAt: string;
  updatedAt: string;
};

export type AiEditorDto = {
  editorId: string;
};

export type AiViolationDto = {
  editorId: string;
  reason: string;
  /**
   * The Yjs update that arrived after the pause, base64
   */
  update?: string;
};

export type AiJobResponseDto = {
  id: string;
  projectId: number;
  userId: number;
  kind: string;
  state: 'QUEUED' | 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'CANCELLED';
  request: {
    [key: string]: unknown;
  };
  result: {
    [key: string]: unknown;
  } | null;
  error: string | null;
  model: string | null;
  cancelRequested: boolean;
  createdAt: string;
  updatedAt: string;
};

export type AiDeclarationDto = {
  categories: Array<'CODE' | 'SPRITES' | 'MAPS' | 'MUSIC' | 'SFX' | 'MULTIPLAYER'>;
  note: string;
};

export type AiDeclarationResponseDto = {
  id: string;
  projectId: number;
  userId: number;
  categories: Array<string>;
  note: string;
  createdAt: string;
};

export type AiAppliedSummaryDto = {
  id: string;
  title: string;
  status: string;
  updatedAt: string;
};

export type AiProvenanceResponseDto = {
  categories: Array<string>;
  declarations: Array<AiDeclarationResponseDto>;
  applied: Array<AiAppliedSummaryDto>;
};

export type AiKeyCreateDto = {
  name: string;
  /**
   * Days until it expires. Omit for a key that never expires.
   */
  expiresInDays?: number | null;
};

export type AiKeyProjectDto = {
  projectId: number;
  name: string;
};

export type AiKeyResponseDto = {
  id: string;
  name: string;
  /**
   * Shown once, never again
   */
  token: string;
  /**
   * null never expires
   */
  expiresAt: string | null;
  createdAt: string;
  projects: Array<AiKeyProjectDto>;
};

export type AiKeySummaryDto = {
  id: string;
  name: string;
  expiresAt: string | null;
  createdAt: string;
  lastUsedAt: string | null;
  projects: Array<AiKeyProjectDto>;
};

export type AiMcpConnectionDto = {
  projectId: number;
  userId: number;
  /**
   * null when the key never expires
   */
  expiresAt: string | null;
};

export type AiContextResponseDto = {
  id: string;
  projectId: number;
  userId: number;
  hash: string;
  content: {
    [key: string]: unknown;
  };
  updatedAt: string;
};

export type AiProposalDto = {
  title: string;
  summary: string;
  snapshotHash: string;
  /**
   * Native operations; validated again against the editor document before preview
   */
  operations: Array<{
    [key: string]: unknown;
  }>;
};

export type AiJobCreateDto = {
  kind: 'sprite';
  /**
   * Prompt and asset constraints sent to the provider
   */
  request: {
    [key: string]: unknown;
  };
};

export type AiJobCompleteDto = {
  result: {
    [key: string]: unknown;
  };
  /**
   * Model identifier and revision that produced the result
   */
  model: string;
};

export type AiJobFailDto = {
  error: string;
};

export type ForkedFromDto = {
  id: number;
  name: string;
  ownerUsername: string;
};

export type UserBasicInfoDto = {
  /**
   * The unique identifier of the user
   */
  id: number;
  /**
   * The username
   */
  username: string;
};

export type ProjectExResponseDto = {
  /**
   * Historical AI-assisted categories; for public releases, the published snapshot
   */
  aiCategories: Array<'CODE' | 'SPRITES' | 'MAPS' | 'MUSIC' | 'SFX'>;
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * Tags associated with the project
   */
  tags: Array<string>;
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED';
  /**
   * The monetization strategy for this project
   */
  monetization: 'NONE' | 'ADS' | 'PAID';
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The date and time when the project was last updated
   */
  updatedAt: string;
  /**
   * The date and time when the project was last published
   */
  publishedAt: string | null;
  /**
   * The number of times players opened this game's play page
   */
  viewCount: number;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The number of comments on the project
   */
  commentCount?: number;
  /**
   * The number of forks created from this project
   */
  forkCount?: number;
  /**
   * The ID of the project this was forked from, if any
   */
  forkedFromId?: number | null;
  /**
   * The project this was forked from, by name — lineage renders a title and an author rather than an id
   */
  forkedFrom?: ForkedFromDto | null;
  /**
   * The users collaborating on this project
   */
  collaborators: Array<UserBasicInfoDto>;
  /**
   * The creator of this project
   */
  creator: UserBasicInfoDto;
};

export type PaginatedProjectsResponseDto = {
  /**
   * The projects included in the current page
   */
  projects: Array<ProjectExResponseDto>;
  /**
   * The total number of projects matching the request
   */
  total: number;
  /**
   * The current page number
   */
  page: number;
  /**
   * The number of projects requested per page
   */
  limit: number;
};

export type ReleaseTagDto = {
  /**
   * The tag, written as the games carry it
   */
  tag: string;
  /**
   * Published games carrying it
   */
  count: number;
};

export type ReleaseTagsResponseDto = {
  /**
   * Tags, most used first
   */
  tags: Array<ReleaseTagDto>;
};

export type ProjectsCountResponseDto = {
  /**
   * The total number of projects matching the request
   */
  total: number;
};

export type SignedUrlResponseDto = {
  /**
   * The signed CloudFront URL for accessing the protected file
   */
  signedUrl: string;
};

export type ProjectLimitsDto = {
  /**
   * Maximum logical content size (bytes) a game can be published at
   */
  maxContentBytes: number;
  /**
   * Maximum size (bytes) of an uploaded project blob
   */
  maxBlobBytes: number;
  /**
   * Named versions a project may hold; saving under an existing name rewrites it
   */
  maxCheckpoints: number;
  /**
   * Autosave slots kept per project, oldest pruned
   */
  maxAutosaves: number;
};

export type ContentSizeBreakdownDto = {
  /**
   * UTF-8 bytes of Lua source
   */
  code: number;
  /**
   * Painted sprite-sheet pixels
   */
  sprites: number;
  /**
   * Sprites with at least one flag set
   */
  flags: number;
  /**
   * Map tiles set
   */
  map: number;
  /**
   * UTF-8 bytes of instruments, patterns, songs, sfx and samples
   */
  sound: number;
  /**
   * Bytes of the colour palette
   */
  palette: number;
  /**
   * Sum of every category
   */
  total: number;
  /**
   * Game document schema version (0 = legacy document)
   */
  schemaVersion: number;
};

export type ProjectSizeDto = {
  /**
   * Project ID
   */
  projectId: number;
  contentSize: ContentSizeBreakdownDto;
  /**
   * Maximum logical content size (bytes) a game can be published at
   */
  maxContentBytes: number;
  /**
   * Whether the project fits within the publishing budget
   */
  withinBudget: boolean;
};

export type CreateProjectDto = {
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * URL to the project icon
   */
  iconUrl?: string;
  /**
   * Tags attached to the project
   */
  tags?: Array<string>;
};

export type ProjectResponseDto = {
  /**
   * Historical AI-assisted categories; for public releases, the published snapshot
   */
  aiCategories: Array<'CODE' | 'SPRITES' | 'MAPS' | 'MUSIC' | 'SFX'>;
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * Tags associated with the project
   */
  tags: Array<string>;
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED';
  /**
   * The monetization strategy for this project
   */
  monetization: 'NONE' | 'ADS' | 'PAID';
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The date and time when the project was last updated
   */
  updatedAt: string;
  /**
   * The date and time when the project was last published
   */
  publishedAt: string | null;
  /**
   * The number of times players opened this game's play page
   */
  viewCount: number;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The number of comments on the project
   */
  commentCount?: number;
  /**
   * The number of forks created from this project
   */
  forkCount?: number;
  /**
   * The ID of the project this was forked from, if any
   */
  forkedFromId?: number | null;
  /**
   * The project this was forked from, by name — lineage renders a title and an author rather than an id
   */
  forkedFrom?: ForkedFromDto | null;
};

export type ForkProjectResponseDto = {
  /**
   * Historical AI-assisted categories; for public releases, the published snapshot
   */
  aiCategories: Array<'CODE' | 'SPRITES' | 'MAPS' | 'MUSIC' | 'SFX'>;
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * Tags associated with the project
   */
  tags: Array<string>;
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED';
  /**
   * The monetization strategy for this project
   */
  monetization: 'NONE' | 'ADS' | 'PAID';
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The date and time when the project was last updated
   */
  updatedAt: string;
  /**
   * The date and time when the project was last published
   */
  publishedAt: string | null;
  /**
   * The number of times players opened this game's play page
   */
  viewCount: number;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The number of comments on the project
   */
  commentCount?: number;
  /**
   * The number of forks created from this project
   */
  forkCount?: number;
  /**
   * The ID of the project this was forked from, if any
   */
  forkedFromId?: number | null;
  /**
   * The project this was forked from, by name — lineage renders a title and an author rather than an id
   */
  forkedFrom?: ForkedFromDto | null;
  /**
   * The users collaborating on this project
   */
  collaborators: Array<UserBasicInfoDto>;
  /**
   * The creator of this project
   */
  creator: UserBasicInfoDto;
};

export type UpdateProjectDto = {
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc?: {
    [key: string]: unknown;
  };
  /**
   * Tags attached to the project
   */
  tags?: Array<string>;
  /**
   * URL to the project icon
   */
  iconUrl?: string;
  /**
   * Project status
   */
  status?: 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED';
  /**
   * Monetization type
   */
  monetization?: 'NONE' | 'ADS' | 'PAID';
  /**
   * The price of the project
   */
  price?: number;
};

export type AddCollaboratorDto = {
  /**
   * User ID of the user to add as collaborator
   */
  userId?: number;
  /**
   * Username of the user to add as collaborator
   */
  username?: string;
  /**
   * Email of the user to add as collaborator
   */
  email?: string;
};

export type RemoveCollaboratorDto = {
  /**
   * User ID of the user to remove as collaborator
   */
  userId?: number;
  /**
   * Username of the user to remove as collaborator
   */
  username?: string;
  /**
   * Email of the user to remove as collaborator
   */
  email?: string;
};

export type ImageUrlResponseDto = {
  /**
   * The public CDN URL for the image
   */
  url: string;
};

export type CheckpointLimitDto = {
  statusCode: number;
  error: string;
  code: string;
  message: string;
  /**
   * Named versions the project holds
   */
  count: number;
  /**
   * Named versions it may hold
   */
  max: number;
};

export type ProjectTooLargeDto = {
  statusCode: number;
  error: string;
  code: string;
  message: string;
  contentSize: ContentSizeBreakdownDto;
  maxContentBytes: number;
};

export type ProjectSaveDto = {
  /**
   * Object name inside the project's save prefix
   */
  name: string;
  /**
   * When the blob was written
   */
  date: string;
};

export type ProjectVersionsResponseDto = {
  /**
   * Autosaves, newest last
   */
  versions: Array<ProjectSaveDto>;
};

export type ProjectCheckpointsResponseDto = {
  /**
   * Named checkpoints
   */
  checkpoints: Array<ProjectSaveDto>;
};

export type LikeResponseDto = {
  /**
   * Total number of likes on the project
   */
  likes: number;
  /**
   * Whether the current user has liked this project
   */
  liked: boolean;
};

export type ViewResponseDto = {
  /**
   * The number of play opens registered for the project
   */
  viewCount: number;
};

export type CreateGameSessionDto = {
  /**
   * ID of the project this session is played on
   */
  projectId: number;
  /**
   * Human-readable title of the session
   */
  title: string;
  /**
   * Maximum number of players, host included
   */
  maxPlayers: number;
  visibility: 'PUBLIC' | 'FRIENDS_ONLY' | 'INVITE_CODE';
};

export type WebRtcOfferPeerIceServerConfig = {
  urls: Array<string>;
  username?: {
    [key: string]: unknown;
  };
  credential?: {
    [key: string]: unknown;
  };
};

export type WebRtcOfferPeerOptsConfig = {
  iceServers: Array<WebRtcOfferPeerIceServerConfig>;
};

export type WebRtcOfferPeerOpts = {
  config: WebRtcOfferPeerOptsConfig;
};

export type WebRtcOfferDto = {
  signaling: Array<string>;
  maxConns: number;
  peerOpts: WebRtcOfferPeerOpts;
};

export type GameSessionConnectionResponseDto = {
  sessionUuid: string;
  /**
   * Player id assigned to this connection
   */
  playerId: number;
  webrtcConfig: WebRtcOfferDto;
  /**
   * Short-lived signed ticket presented on the WebRTC connection
   */
  connectionTicket: string;
  /**
   * Join code to share, present only when hosting an INVITE_CODE session
   */
  joinCode?: string;
};

export type JoinByCodeDto = {
  /**
   * Invite code of the session to join
   */
  joinCode: string;
  /**
   * Set by the game editor to allow a self-join for solo testing
   */
  editorTest?: boolean;
};

export type GameSessionResponseDto = {
  sessionUuid: string;
  title: string;
  visibility: 'PUBLIC' | 'FRIENDS_ONLY' | 'INVITE_CODE';
  /**
   * ID of the host user
   */
  hostId: number;
  /**
   * Username of the host
   */
  hostUsername: string;
  /**
   * Display nickname of the host, if set
   */
  hostNickname?: string;
  /**
   * ID of the game (project) being played
   */
  projectId: number;
  /**
   * Name of the game (project) being played
   */
  projectName: string;
  /**
   * Maximum number of players, host included
   */
  maxPlayers: number;
  /**
   * Current number of players, host included
   */
  playerCount: number;
};

export type GameSessionListResponseDto = {
  sessions: Array<GameSessionResponseDto>;
};

export type SessionPlayerDto = {
  /**
   * User ID
   */
  userId: number;
  /**
   * Username
   */
  username: string;
  /**
   * Display nickname, if set
   */
  nickname?: string | null;
  /**
   * Whether this player is hosting
   */
  host: boolean;
};

export type SessionRosterResponseDto = {
  players: Array<SessionPlayerDto>;
  /**
   * Slots the session was opened with
   */
  maxPlayers: number;
};

export type InviteToSessionDto = {
  /**
   * Who to invite
   */
  userId: number;
};

export type UpdateGameSessionDto = {
  /**
   * New title of the session
   */
  title?: string;
  /**
   * New maximum number of players, host included
   */
  maxPlayers?: number;
  visibility?: 'PUBLIC' | 'FRIENDS_ONLY' | 'INVITE_CODE';
};

export type JoinGameSessionDto = {
  /**
   * Join code, required for INVITE_CODE sessions
   */
  joinCode?: string;
  /**
   * Set by the game editor to allow a self-join for solo testing
   */
  editorTest?: boolean;
};

export type RefreshTicketDto = {
  /**
   * The ticket being replaced. When it was minted for this session, the fresh one keeps its player id and role; otherwise the caller's account decides both.
   */
  ticket?: string;
};

export type CommentAuthorDto = {
  id: number;
  username: string;
  nickname?: string | null;
};

export type CommentResponseDto = {
  id: number;
  content: string;
  createdAt: string;
  projectId: number;
  author: CommentAuthorDto;
  deleted?: boolean;
  /**
   * Replies to this comment (only for top-level comments)
   */
  replies?: Array<CommentResponseDto>;
};

export type PaginatedCommentsResponseDto = {
  comments: Array<CommentResponseDto>;
  total: number;
  page: number;
  limit: number;
};

export type CreateCommentDto = {
  /**
   * The content of the comment
   */
  content: string;
};

export type NotificationTestDto = {
  /**
   * The title of the test notification
   */
  title: string;
  /**
   * The message content of the test notification
   */
  message: string;
  /**
   * The type of the notification
   */
  type: 'INFO' | 'WARNING';
};

export type FriendDto = {
  id: number;
  username: string;
  nickname?: {
    [key: string]: unknown;
  } | null;
  /**
   * When the friendship was created (ISO 8601)
   */
  since: string;
};

export type UserSummaryDto = {
  id: number;
  username: string;
  nickname?: {
    [key: string]: unknown;
  } | null;
};

export type FriendRequestDto = {
  id: number;
  from: UserSummaryDto;
  to: UserSummaryDto;
  /**
   * Friends the two users have in common
   */
  mutuals?: number;
  /**
   * Whether the sender has played a game session hosted on one of the recipient's projects
   */
  playedYourGame?: boolean;
  createdAt: string;
};

export type SendFriendRequestDto = {
  /**
   * ID of the user to befriend
   */
  userId?: number;
  /**
   * Handle of the person to befriend — what the profile shows after the @
   */
  username?: string;
  /**
   * Friend code of the user to befriend (case-insensitive, dashes/spaces ignored)
   */
  friendCode?: string;
};

export type RecentPlayerDto = {
  id: number;
  username: string;
  nickname?: {
    [key: string]: unknown;
  } | null;
  /**
   * Name of the game played together
   */
  game: string;
  /**
   * Start of the most recent shared game session (ISO 8601)
   */
  playedAt: string;
  /**
   * Whether this player is already a friend
   */
  friend: boolean;
};

export const FriendshipStatus = {
  NONE: 'NONE',
  PENDING: 'PENDING',
  FRIENDS: 'FRIENDS',
} as const;

export type FriendshipStatus = (typeof FriendshipStatus)[keyof typeof FriendshipStatus];

export type FriendshipStatusDto = {
  status: FriendshipStatus;
};

export const PresenceKind = {
  IDLE: 'IDLE',
  PLAYING: 'PLAYING',
  BUILDING: 'BUILDING',
  HOSTING: 'HOSTING',
} as const;

export type PresenceKind = (typeof PresenceKind)[keyof typeof PresenceKind];

export type PresenceDto = {
  userId: number;
  /**
   * Who it is, so a row can name them without a second call
   */
  username: string;
  nickname?: {
    [key: string]: unknown;
  } | null;
  kind: PresenceKind;
  /**
   * Released project being played (PLAYING)
   */
  releaseId?: {
    [key: string]: unknown;
  } | null;
  /**
   * Project being edited (BUILDING) or hosted (HOSTING)
   */
  projectId?: {
    [key: string]: unknown;
  } | null;
  /**
   * Game session UUID (HOSTING)
   */
  sessionId?: {
    [key: string]: unknown;
  } | null;
  /**
   * Game session title or project name
   */
  title?: {
    [key: string]: unknown;
  } | null;
  /**
   * Cover of the game being played, built or hosted
   */
  coverUrl?: {
    [key: string]: unknown;
  } | null;
  /**
   * Players in the hosted session, host included
   */
  players?: {
    [key: string]: unknown;
  } | null;
  maxPlayers?: {
    [key: string]: unknown;
  } | null;
  /**
   * Whether the caller may join the hosted session
   */
  joinable?: boolean;
  /**
   * When this activity started (ISO 8601)
   */
  since: string;
};

export type FeaturedCuratorDto = {
  id: number;
  username: string;
};

export type FeaturedReleaseDto = {
  /**
   * Featured entry ID
   */
  id: number;
  /**
   * Featured project ID
   */
  projectId: number;
  note?: string | null;
  startsAt: string;
  endsAt?: string | null;
  featuredBy?: FeaturedCuratorDto | null;
  /**
   * Release metadata of the featured project
   */
  project: ProjectExResponseDto;
};

export type FeaturedReleaseResponseDto = {
  /**
   * The current featured release, or null when none is set
   */
  featured: FeaturedReleaseDto | null;
};

export type SetFeaturedReleaseDto = {
  /**
   * ID of the published project
   */
  projectId: number;
  /**
   * Optional curator note shown next to the featured game
   */
  note?: string;
};

export type FeaturedProjectSummaryDto = {
  id: number;
  name: string;
};

export type FeaturedReleaseHistoryEntryDto = {
  id: number;
  projectId: number;
  note?: string | null;
  startsAt: string;
  endsAt?: string | null;
  featuredBy?: FeaturedCuratorDto | null;
  project: FeaturedProjectSummaryDto;
};

export type FeaturedReleaseHistoryDto = {
  items: Array<FeaturedReleaseHistoryEntryDto>;
  total: number;
  page: number;
  limit: number;
};

export type LoginDto = {
  /**
   * User email address
   */
  email: string;
  /**
   * User password
   */
  password: string;
};

export type PasswordPolicyDto = {
  /**
   * Fewest characters a password may hold
   */
  minLength: number;
  /**
   * How many of the character classes below a password must draw on
   */
  minCharacterClasses: number;
  /**
   * The classes that count towards minCharacterClasses
   */
  characterClasses: Array<'letters' | 'digits' | 'symbols'>;
};

export type CreateUserDto = {
  /**
   * User email address
   */
  email: string;
  /**
   * User username
   */
  username: string;
  /**
   * User nick name
   */
  nickname?: string;
  /**
   * User password
   */
  password: string;
};

export type ViolationDto = {
  /**
   * Dotted path of the rejected field, array indices included
   */
  field: string;
  /**
   * Stable identifier for the rule it broke
   */
  code: string;
};

export type ValidationErrorResponseDto = {
  statusCode: number;
  error: string;
  message: Array<string>;
  violations: Array<ViolationDto>;
};

export type ConflictErrorResponseDto = {
  statusCode: number;
  error: string;
  message: string;
  violations: Array<ViolationDto>;
};

export type GoogleCodeDto = {
  /**
   * Google authorization code
   */
  code: string;
  /**
   * PKCE code verifier
   */
  codeVerifier: string;
};

export type GithubLoginDto = {
  /**
   * GitHub OAuth authorization code
   */
  code: string;
};

export type MicrosoftLoginDto = {
  /**
   * Microsoft ID token
   */
  token: string;
};

export type ChangePasswordDto = {
  /**
   * Current password (not required for OAuth accounts)
   */
  currentPassword?: string;
  /**
   * New password
   */
  newPassword: string;
};

export type UserRoleDto = {
  /**
   * Role ID
   */
  id: number;
  /**
   * Role name
   */
  name: string;
};

export type UserResponseDto = {
  /**
   * User ID
   */
  id: number;
  /**
   * User email address
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname
   */
  nickname: string | null;
  /**
   * User roles
   */
  roles?: Array<UserRoleDto>;
  /**
   * User creation date
   */
  createdAt: string;
  /**
   * User last update date
   */
  updatedAt: string;
};

export type PaginationMetaDto = {
  /**
   * Current page number
   */
  page: number;
  /**
   * Number of items per page
   */
  limit: number;
  /**
   * Total number of items
   */
  total: number;
  /**
   * Total number of pages
   */
  totalPages: number;
};

export type UserListResponseDto = {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * List of users
   */
  data: Array<UserResponseDto>;
  /**
   * Pagination metadata
   */
  meta: PaginationMetaDto;
};

export type UserSingleResponseDto = {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * User data
   */
  data: UserResponseDto;
};

export type UserProfileResponseDto = {
  /**
   * User ID
   */
  id: number;
  /**
   * User email address
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname
   */
  nickname: string | null;
  /**
   * User roles
   */
  roles?: Array<UserRoleDto>;
  /**
   * User creation date
   */
  createdAt: string;
  /**
   * User last update date
   */
  updatedAt: string;
  /**
   * User profile message
   */
  message: string;
  /**
   * Public CDN URL of the profile image (if any)
   */
  profileImageUrl: string | null;
  /**
   * Public CDN URL of the profile background image (if any)
   */
  backgroundImageUrl: string | null;
};

export type PublicUserProfileDto = {
  /**
   * User ID
   */
  id: number;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname / bio
   */
  nickname?: string | null;
  /**
   * User profile description
   */
  description?: string | null;
  /**
   * Public CDN URL of the profile image (if any)
   */
  profileImageUrl?: string | null;
  /**
   * Public CDN URL of the profile background image (if any)
   */
  backgroundImageUrl?: string | null;
  /**
   * The accent this person is drawn in; null until they pick one
   */
  colour?: 'SKY' | 'BLUSH' | 'JADE' | 'GOLD' | 'ORANGE' | 'HOT';
  /**
   * When the account was created — the profile header shows the year
   */
  createdAt: string;
  /**
   * Published games this person owns
   */
  gameCount?: number;
  /**
   * Total plays across their published games
   */
  totalPlays?: number;
  /**
   * Total likes across their published games
   */
  totalLikes?: number;
};

export type PublicUserProfileResponseDto = {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * Public user profile
   */
  data: PublicUserProfileDto;
};

export type UpdateUserProfileDto = {
  /**
   * Public nickname / bio displayed on the profile
   */
  nickname?: string;
  /**
   * Public profile description displayed on the profile
   */
  description?: string;
  /**
   * Handle, unique across the platform — people add you as a friend with it
   */
  username?: string;
  /**
   * The accent this person is drawn in
   */
  colour?: 'SKY' | 'BLUSH' | 'JADE' | 'GOLD' | 'ORANGE' | 'HOT';
};

/**
 * Who may join the game sessions this user hosts
 */
export const SessionJoinPolicy = {
  ANYONE: 'ANYONE',
  FRIENDS: 'FRIENDS',
  CODE_ONLY: 'CODE_ONLY',
} as const;

/**
 * Who may join the game sessions this user hosts
 */
export type SessionJoinPolicy = (typeof SessionJoinPolicy)[keyof typeof SessionJoinPolicy];

export type MeDto = {
  /**
   * Code other users enter to send a friend request
   */
  friendCode: string;
  /**
   * Who may join the game sessions this user hosts
   */
  sessionJoinPolicy: SessionJoinPolicy;
};

export type UpdateMeDto = {
  sessionJoinPolicy?: SessionJoinPolicy;
};

export type DeleteAccountDto = {
  /**
   * Must be the literal string DELETE
   */
  confirmation: 'DELETE';
  /**
   * Also remove the user's published games (default: keep them, attributed to Deleted user)
   */
  removePublishedGames?: boolean;
  /**
   * Current password; verified when provided on a password account
   */
  password?: string;
};

export type ProfileImageUploadResponseDto = {
  message: string;
  /**
   * User ID
   */
  id: number;
  /**
   * Where the image now lives, versioned so a replacement is not served from cache
   */
  resourceUrl: string;
};

export type SignedCdnResourceDto = {
  /**
   * The CDN URL for the resource (requires signed cookies)
   */
  resourceUrl: string;
  /**
   * Signed Edge cookies (also set as HTTP-only cookies)
   */
  cookies: {
    [key: string]: unknown;
  };
};

export type UpdateUserDto = {
  /**
   * User email address
   */
  email?: string;
  /**
   * User username
   */
  username?: string;
  /**
   * User nick name
   */
  nickname?: string;
  /**
   * User password
   */
  password?: string;
};

export type PublicUserSearchHitDto = {
  /**
   * User ID
   */
  id: number;
  /**
   * Handle, unique across the platform
   */
  username: string;
  /**
   * Display name
   */
  nickname?: {
    [key: string]: unknown;
  } | null;
  /**
   * Profile picture, null when the person has not set one
   */
  profileImageUrl?: {
    [key: string]: unknown;
  } | null;
};

export type PublicUserSearchResponseDto = {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * Matching people
   */
  data: Array<PublicUserSearchHitDto>;
};

export type JoinWorkSessionDto = {
  /**
   * The unique room ID for the work session
   */
  roomId: string;
  /**
   * The user ID of the session's host
   */
  hostId: number;
  /**
   * The WebRTC offer given to the client
   */
  webrtcOffer: WebRtcOfferDto;
};

export type KickWorkSessionDto = {
  /**
   * The ID of the user participating in the work session
   */
  userId: number;
};

export type FetchWorkSessionDto = {
  /**
   * The ID of the user participating in the work session
   */
  users: Array<string>;
  /**
   * The ID of the session's host
   */
  hostId: number;
  /**
   * The ID of the project this work session belongs to
   */
  project: number;
  /**
   * The date and time when the work session started
   */
  startedAt: string;
  /**
   * The ID of the room for this work session
   */
  roomId: string;
};

export type AiControllerRevokeData = {
  body?: never;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/ai/projects/{projectId}/connection';
};

export type AiControllerRevokeResponses = {
  200: unknown;
};

export type AiControllerConnectData = {
  body?: never;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/ai/projects/{projectId}/connection';
};

export type AiControllerConnectResponses = {
  201: AiConnectionResponseDto;
};

export type AiControllerConnectResponse =
  AiControllerConnectResponses[keyof AiControllerConnectResponses];

export type AiControllerContextData = {
  body: AiContextDto;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/ai/projects/{projectId}/context';
};

export type AiControllerContextResponses = {
  201: unknown;
};

export type AiControllerListData = {
  body?: never;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/ai/projects/{projectId}/proposals';
};

export type AiControllerListResponses = {
  200: Array<AiProposalResponseDto>;
};

export type AiControllerListResponse = AiControllerListResponses[keyof AiControllerListResponses];

export type AiControllerReviewData = {
  body: AiReviewDto;
  path: {
    projectId: number;
    proposalId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/proposals/{proposalId}/review';
};

export type AiControllerReviewResponses = {
  201: unknown;
};

export type AiControllerPreviewData = {
  body: AiAckDto;
  path: {
    projectId: number;
    proposalId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/proposals/{proposalId}/preview';
};

export type AiControllerPreviewResponses = {
  201: unknown;
};

export type AiControllerRevertData = {
  body?: never;
  path: {
    projectId: number;
    proposalId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/proposals/{proposalId}/revert';
};

export type AiControllerRevertResponses = {
  201: AiProposalResponseDto;
};

export type AiControllerRevertResponse =
  AiControllerRevertResponses[keyof AiControllerRevertResponses];

export type AiControllerStartData = {
  body: AiStartDto;
  path: {
    projectId: number;
    proposalId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/proposals/{proposalId}/apply';
};

export type AiControllerStartResponses = {
  201: AiBarrierResponseDto;
};

export type AiControllerStartResponse =
  AiControllerStartResponses[keyof AiControllerStartResponses];

export type AiControllerHeartbeatData = {
  body: AiEditorDto;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/ai/projects/{projectId}/editors/heartbeat';
};

export type AiControllerHeartbeatResponses = {
  /**
   * Current barrier, or null when none exists
   */
  201: AiBarrierResponseDto;
};

export type AiControllerHeartbeatResponse =
  AiControllerHeartbeatResponses[keyof AiControllerHeartbeatResponses];

export type AiControllerAcknowledgeData = {
  body: AiAckDto;
  path: {
    projectId: number;
    barrierId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/barriers/{barrierId}/ack';
};

export type AiControllerAcknowledgeResponses = {
  201: unknown;
};

export type AiControllerViolationData = {
  body: AiViolationDto;
  path: {
    projectId: number;
    barrierId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/barriers/{barrierId}/violation';
};

export type AiControllerViolationResponses = {
  201: AiBarrierResponseDto;
};

export type AiControllerViolationResponse =
  AiControllerViolationResponses[keyof AiControllerViolationResponses];

export type AiControllerDismissData = {
  body?: never;
  path: {
    projectId: number;
    barrierId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/barriers/{barrierId}/violation/dismiss';
};

export type AiControllerDismissResponses = {
  201: unknown;
};

export type AiControllerFinishData = {
  body?: never;
  path: {
    projectId: number;
    barrierId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/barriers/{barrierId}/finish';
};

export type AiControllerFinishResponses = {
  201: AiBarrierResponseDto;
};

export type AiControllerFinishResponse =
  AiControllerFinishResponses[keyof AiControllerFinishResponses];

export type AiControllerAbortData = {
  body?: never;
  path: {
    projectId: number;
    barrierId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/barriers/{barrierId}/abort';
};

export type AiControllerAbortResponses = {
  201: unknown;
};

export type AiControllerListJobsData = {
  body?: never;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/ai/projects/{projectId}/jobs';
};

export type AiControllerListJobsResponses = {
  200: Array<AiJobResponseDto>;
};

export type AiControllerListJobsResponse =
  AiControllerListJobsResponses[keyof AiControllerListJobsResponses];

export type AiControllerCancelJobData = {
  body?: never;
  path: {
    projectId: number;
    jobId: string;
  };
  query?: never;
  url: '/ai/projects/{projectId}/jobs/{jobId}/cancel';
};

export type AiControllerCancelJobResponses = {
  201: AiJobResponseDto;
};

export type AiControllerCancelJobResponse =
  AiControllerCancelJobResponses[keyof AiControllerCancelJobResponses];

export type AiControllerDeclareData = {
  body: AiDeclarationDto;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/ai/projects/{projectId}/declarations';
};

export type AiControllerDeclareResponses = {
  201: AiDeclarationResponseDto;
};

export type AiControllerDeclareResponse =
  AiControllerDeclareResponses[keyof AiControllerDeclareResponses];

export type AiControllerProvenanceData = {
  body?: never;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/ai/projects/{projectId}/provenance';
};

export type AiControllerProvenanceResponses = {
  200: AiProvenanceResponseDto;
};

export type AiControllerProvenanceResponse =
  AiControllerProvenanceResponses[keyof AiControllerProvenanceResponses];

export type AiKeysControllerListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/ai/keys';
};

export type AiKeysControllerListResponses = {
  200: Array<AiKeySummaryDto>;
};

export type AiKeysControllerListResponse =
  AiKeysControllerListResponses[keyof AiKeysControllerListResponses];

export type AiKeysControllerCreateData = {
  body: AiKeyCreateDto;
  path?: never;
  query?: never;
  url: '/ai/keys';
};

export type AiKeysControllerCreateResponses = {
  201: AiKeyResponseDto;
};

export type AiKeysControllerCreateResponse =
  AiKeysControllerCreateResponses[keyof AiKeysControllerCreateResponses];

export type AiKeysControllerRevokeData = {
  body?: never;
  path: {
    keyId: string;
  };
  query?: never;
  url: '/ai/keys/{keyId}';
};

export type AiKeysControllerRevokeResponses = {
  200: unknown;
};

export type AiKeysControllerUngrantData = {
  body?: never;
  path: {
    keyId: string;
    projectId: number;
  };
  query?: never;
  url: '/ai/keys/{keyId}/projects/{projectId}';
};

export type AiKeysControllerUngrantResponses = {
  200: unknown;
};

export type AiKeysControllerGrantData = {
  body?: never;
  path: {
    keyId: string;
    projectId: number;
  };
  query?: never;
  url: '/ai/keys/{keyId}/projects/{projectId}';
};

export type AiKeysControllerGrantResponses = {
  201: unknown;
};

export type AiMcpControllerConnectionData = {
  body?: never;
  headers: {
    authorization: string;
    'x-naucto-project': string;
  };
  path?: never;
  query?: never;
  url: '/ai/mcp/connection';
};

export type AiMcpControllerConnectionResponses = {
  200: AiMcpConnectionDto;
};

export type AiMcpControllerConnectionResponse =
  AiMcpControllerConnectionResponses[keyof AiMcpControllerConnectionResponses];

export type AiMcpControllerProjectsData = {
  body?: never;
  headers: {
    authorization: string;
    'x-naucto-project': string;
  };
  path?: never;
  query?: never;
  url: '/ai/mcp/projects';
};

export type AiMcpControllerProjectsResponses = {
  200: unknown;
};

export type AiMcpControllerContextData = {
  body?: never;
  headers: {
    authorization: string;
    'x-naucto-project': string;
  };
  path?: never;
  query?: never;
  url: '/ai/mcp/context';
};

export type AiMcpControllerContextResponses = {
  200: AiContextResponseDto;
};

export type AiMcpControllerContextResponse =
  AiMcpControllerContextResponses[keyof AiMcpControllerContextResponses];

export type AiMcpControllerListData = {
  body?: never;
  headers: {
    authorization: string;
    'x-naucto-project': string;
  };
  path?: never;
  query?: never;
  url: '/ai/mcp/proposals';
};

export type AiMcpControllerListResponses = {
  200: Array<AiProposalResponseDto>;
};

export type AiMcpControllerListResponse =
  AiMcpControllerListResponses[keyof AiMcpControllerListResponses];

export type AiMcpControllerProposeData = {
  body: AiProposalDto;
  headers: {
    authorization: string;
    'x-naucto-project': string;
  };
  path?: never;
  query?: never;
  url: '/ai/mcp/proposals';
};

export type AiMcpControllerProposeResponses = {
  201: AiProposalResponseDto;
};

export type AiMcpControllerProposeResponse =
  AiMcpControllerProposeResponses[keyof AiMcpControllerProposeResponses];

export type AiMcpControllerCreateJobData = {
  body: AiJobCreateDto;
  headers: {
    authorization: string;
    'x-naucto-project': string;
  };
  path?: never;
  query?: never;
  url: '/ai/mcp/jobs';
};

export type AiMcpControllerCreateJobResponses = {
  201: AiJobResponseDto;
};

export type AiMcpControllerCreateJobResponse =
  AiMcpControllerCreateJobResponses[keyof AiMcpControllerCreateJobResponses];

export type AiMcpControllerGetJobData = {
  body?: never;
  headers: {
    authorization: string;
    'x-naucto-project': string;
  };
  path: {
    jobId: string;
  };
  query?: never;
  url: '/ai/mcp/jobs/{jobId}';
};

export type AiMcpControllerGetJobResponses = {
  200: AiJobResponseDto;
};

export type AiMcpControllerGetJobResponse =
  AiMcpControllerGetJobResponses[keyof AiMcpControllerGetJobResponses];

export type AiMcpControllerCancelJobData = {
  body?: never;
  headers: {
    authorization: string;
    'x-naucto-project': string;
  };
  path: {
    jobId: string;
  };
  query?: never;
  url: '/ai/mcp/jobs/{jobId}/cancel';
};

export type AiMcpControllerCancelJobResponses = {
  201: AiJobResponseDto;
};

export type AiMcpControllerCancelJobResponse =
  AiMcpControllerCancelJobResponses[keyof AiMcpControllerCancelJobResponses];

export type AiMcpControllerClaimJobData = {
  body?: never;
  headers: {
    authorization: string;
    'x-naucto-project': string;
    'x-naucto-ai-service': string;
  };
  path: {
    jobId: string;
  };
  query?: never;
  url: '/ai/mcp/jobs/{jobId}/claim';
};

export type AiMcpControllerClaimJobResponses = {
  201: unknown;
};

export type AiMcpControllerCompleteJobData = {
  body: AiJobCompleteDto;
  headers: {
    authorization: string;
    'x-naucto-project': string;
    'x-naucto-ai-service': string;
  };
  path: {
    jobId: string;
  };
  query?: never;
  url: '/ai/mcp/jobs/{jobId}/complete';
};

export type AiMcpControllerCompleteJobResponses = {
  201: AiJobResponseDto;
};

export type AiMcpControllerCompleteJobResponse =
  AiMcpControllerCompleteJobResponses[keyof AiMcpControllerCompleteJobResponses];

export type AiMcpControllerFailJobData = {
  body: AiJobFailDto;
  headers: {
    authorization: string;
    'x-naucto-project': string;
    'x-naucto-ai-service': string;
  };
  path: {
    jobId: string;
  };
  query?: never;
  url: '/ai/mcp/jobs/{jobId}/fail';
};

export type AiMcpControllerFailJobResponses = {
  201: unknown;
};

export type ProjectControllerGetAllReleasesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/projects/releases';
};

export type ProjectControllerGetAllReleasesResponses = {
  /**
   * A JSON array of projects with collaborators and creator information
   */
  200: Array<ProjectExResponseDto>;
};

export type ProjectControllerGetAllReleasesResponse =
  ProjectControllerGetAllReleasesResponses[keyof ProjectControllerGetAllReleasesResponses];

export type ProjectControllerGetPaginatedReleasesData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string;
    /**
     * Comma-separated tag list
     */
    tags?: string;
    releaseWindow?: 'all' | '365d' | '30d' | '7d';
    /**
     * Shelf ordering; defaults to newest first
     */
    sort?: 'fresh' | 'popular' | 'liked' | 'discussed' | 'name';
  };
  url: '/projects/releases/paginated';
};

export type ProjectControllerGetPaginatedReleasesResponses = {
  /**
   * A paginated list of released projects
   */
  200: PaginatedProjectsResponseDto;
};

export type ProjectControllerGetPaginatedReleasesResponse =
  ProjectControllerGetPaginatedReleasesResponses[keyof ProjectControllerGetPaginatedReleasesResponses];

export type ProjectControllerGetReleaseTagsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Narrow to tags holding this fragment
     */
    q?: string;
    limit?: number;
  };
  url: '/projects/releases/tags';
};

export type ProjectControllerGetReleaseTagsResponses = {
  /**
   * Tags, most used first
   */
  200: ReleaseTagsResponseDto;
};

export type ProjectControllerGetReleaseTagsResponse =
  ProjectControllerGetReleaseTagsResponses[keyof ProjectControllerGetReleaseTagsResponses];

export type ProjectControllerCountReleasedProjectsData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
    /**
     * Comma-separated tag list
     */
    tags?: string;
    releaseWindow?: 'all' | '365d' | '30d' | '7d';
  };
  url: '/projects/releases/count';
};

export type ProjectControllerCountReleasedProjectsResponses = {
  /**
   * The total number of released projects matching the request
   */
  200: ProjectsCountResponseDto;
};

export type ProjectControllerCountReleasedProjectsResponse =
  ProjectControllerCountReleasedProjectsResponses[keyof ProjectControllerCountReleasedProjectsResponses];

export type ProjectControllerGetReleaseData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}';
};

export type ProjectControllerGetReleaseResponses = {
  /**
   * Project release metadata
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerGetReleaseResponse =
  ProjectControllerGetReleaseResponses[keyof ProjectControllerGetReleaseResponses];

export type ProjectControllerGetReleaseContentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/content';
};

export type ProjectControllerGetReleaseContentResponses = {
  /**
   * Project release file
   */
  200: Blob | File;
};

export type ProjectControllerGetReleaseContentResponse =
  ProjectControllerGetReleaseContentResponses[keyof ProjectControllerGetReleaseContentResponses];

export type ProjectControllerGetReleaseContentUrlData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/content-url';
};

export type ProjectControllerGetReleaseContentUrlResponses = {
  /**
   * Signed Edge URL for the release
   */
  200: SignedUrlResponseDto;
};

export type ProjectControllerGetReleaseContentUrlResponse =
  ProjectControllerGetReleaseContentUrlResponses[keyof ProjectControllerGetReleaseContentUrlResponses];

export type ProjectControllerGetLimitsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/projects/limits';
};

export type ProjectControllerGetLimitsResponses = {
  /**
   * Content budget and blob size limits
   */
  200: ProjectLimitsDto;
};

export type ProjectControllerGetLimitsResponse =
  ProjectControllerGetLimitsResponses[keyof ProjectControllerGetLimitsResponses];

export type ProjectControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/projects';
};

export type ProjectControllerFindAllErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type ProjectControllerFindAllResponses = {
  /**
   * A paginated list of projects with collaborators and creator information
   */
  200: PaginatedProjectsResponseDto;
};

export type ProjectControllerFindAllResponse =
  ProjectControllerFindAllResponses[keyof ProjectControllerFindAllResponses];

export type ProjectControllerCreateData = {
  body: CreateProjectDto;
  path?: never;
  query?: never;
  url: '/projects';
};

export type ProjectControllerCreateErrors = {
  /**
   * Bad request – invalid input
   */
  400: unknown;
};

export type ProjectControllerCreateResponses = {
  /**
   * Project created successfully
   */
  201: ProjectResponseDto;
};

export type ProjectControllerCreateResponse =
  ProjectControllerCreateResponses[keyof ProjectControllerCreateResponses];

export type ProjectControllerCountProjectsData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
    /**
     * Comma-separated tag list
     */
    tags?: string;
    status?: 'all' | 'drafts' | 'published';
  };
  url: '/projects/count';
};

export type ProjectControllerCountProjectsResponses = {
  /**
   * The total number of user projects matching the request
   */
  200: ProjectsCountResponseDto;
};

export type ProjectControllerCountProjectsResponse =
  ProjectControllerCountProjectsResponses[keyof ProjectControllerCountProjectsResponses];

export type ProjectControllerRemoveData = {
  body?: never;
  path: {
    /**
     * Numeric ID of the project to delete
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}';
};

export type ProjectControllerRemoveErrors = {
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Error deleting project
   */
  500: unknown;
};

export type ProjectControllerRemoveResponses = {
  /**
   * Project deleted successfully (no content)
   */
  204: void;
};

export type ProjectControllerRemoveResponse =
  ProjectControllerRemoveResponses[keyof ProjectControllerRemoveResponses];

export type ProjectControllerFindOneData = {
  body?: never;
  path: {
    /**
     * Numeric ID of the project to retrieve
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}';
};

export type ProjectControllerFindOneErrors = {
  /**
   * Invalid user or project ID
   */
  403: unknown;
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type ProjectControllerFindOneResponses = {
  /**
   * Project object
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerFindOneResponse =
  ProjectControllerFindOneResponses[keyof ProjectControllerFindOneResponses];

export type ProjectControllerUpdateData = {
  body: UpdateProjectDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}';
};

export type ProjectControllerUpdateErrors = {
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Error updating project
   */
  500: unknown;
};

export type ProjectControllerUpdateResponses = {
  /**
   * Updated project object
   */
  200: ProjectResponseDto;
};

export type ProjectControllerUpdateResponse =
  ProjectControllerUpdateResponses[keyof ProjectControllerUpdateResponses];

export type ProjectControllerGetSizeData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/projects/{id}/size';
};

export type ProjectControllerGetSizeErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Project not found
   */
  404: unknown;
};

export type ProjectControllerGetSizeResponses = {
  /**
   * Size breakdown
   */
  200: ProjectSizeDto;
};

export type ProjectControllerGetSizeResponse =
  ProjectControllerGetSizeResponses[keyof ProjectControllerGetSizeResponses];

export type ProjectControllerForkData = {
  body?: never;
  path: {
    /**
     * Numeric ID of the published project to fork
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}/fork';
};

export type ProjectControllerForkErrors = {
  /**
   * Project is not published
   */
  400: unknown;
  /**
   * Project not found
   */
  404: unknown;
};

export type ProjectControllerForkResponses = {
  /**
   * Forked project created successfully
   */
  201: ForkProjectResponseDto;
};

export type ProjectControllerForkResponse =
  ProjectControllerForkResponses[keyof ProjectControllerForkResponses];

export type ProjectControllerAddCollaboratorData = {
  body: AddCollaboratorDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}/add-collaborator';
};

export type ProjectControllerAddCollaboratorErrors = {
  /**
   * Bad request - no valid identifier provided
   */
  400: unknown;
  /**
   * Project or user not found
   */
  404: unknown;
  /**
   * Error Patching project
   */
  500: unknown;
};

export type ProjectControllerAddCollaboratorResponses = {
  /**
   * Updated project object with collaborators
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerAddCollaboratorResponse =
  ProjectControllerAddCollaboratorResponses[keyof ProjectControllerAddCollaboratorResponses];

export type ProjectControllerRemoveCollaboratorData = {
  body: RemoveCollaboratorDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}/remove-collaborator';
};

export type ProjectControllerRemoveCollaboratorErrors = {
  /**
   * Bad request - no valid identifier provided
   */
  400: unknown;
  /**
   * Forbidden - cannot remove project creator
   */
  403: unknown;
  /**
   * Project or user not found
   */
  404: unknown;
  /**
   * Error remove collaborator on project
   */
  500: unknown;
};

export type ProjectControllerRemoveCollaboratorResponses = {
  /**
   * Updated project object with collaborators
   */
  200: ProjectExResponseDto;
};

export type ProjectControllerRemoveCollaboratorResponse =
  ProjectControllerRemoveCollaboratorResponses[keyof ProjectControllerRemoveCollaboratorResponses];

export type ProjectControllerSaveProjectContentData = {
  body: {
    /**
     * Project file (zip, pdf, png, etc.)
     */
    file?: Blob | File;
  };
  path: {
    id: number;
  };
  query?: never;
  url: '/projects/{id}/saveContent';
};

export type ProjectControllerSaveProjectContentErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * File validation failed
   */
  422: unknown;
};

export type ProjectControllerSaveProjectContentResponses = {
  /**
   * File uploaded successfully
   */
  201: unknown;
};

export type ProjectControllerGetProjectImageData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/projects/{id}/image';
};

export type ProjectControllerGetProjectImageErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetProjectImageResponses = {
  /**
   * CDN URL for the project image
   */
  200: ImageUrlResponseDto;
  /**
   * Project has no image
   */
  204: void;
};

export type ProjectControllerGetProjectImageResponse =
  ProjectControllerGetProjectImageResponses[keyof ProjectControllerGetProjectImageResponses];

export type ProjectControllerUploadProjectImageData = {
  body: {
    /**
     * Project image file (JPEG, PNG, GIF, WebP)
     */
    file?: Blob | File;
  };
  path: {
    id: number;
  };
  query?: never;
  url: '/projects/{id}/image';
};

export type ProjectControllerUploadProjectImageErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Invalid file type or size
   */
  422: unknown;
};

export type ProjectControllerUploadProjectImageResponses = {
  /**
   * Image uploaded successfully
   */
  201: unknown;
};

export type ProjectControllerGetPublishedProjectImageData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/projects/public/{id}/image';
};

export type ProjectControllerGetPublishedProjectImageErrors = {
  /**
   * Project not found, not published, or has no image
   */
  404: unknown;
};

export type ProjectControllerGetPublishedProjectImageResponses = {
  /**
   * Returns the CDN URL for the project image
   */
  200: ImageUrlResponseDto;
};

export type ProjectControllerGetPublishedProjectImageResponse =
  ProjectControllerGetPublishedProjectImageResponses[keyof ProjectControllerGetPublishedProjectImageResponses];

export type ProjectControllerFetchProjectContentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/fetchContent';
};

export type ProjectControllerFetchProjectContentErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * File not found
   */
  404: unknown;
};

export type ProjectControllerFetchProjectContentResponses = {
  /**
   * File fetched successfully
   */
  200: Blob | File;
};

export type ProjectControllerFetchProjectContentResponse =
  ProjectControllerFetchProjectContentResponses[keyof ProjectControllerFetchProjectContentResponses];

export type ProjectControllerSaveCheckpointData = {
  body: {
    file?: Blob | File;
  };
  path: {
    id: string;
    name: string;
  };
  query?: never;
  url: '/projects/{id}/saveCheckpoint/{name}';
};

export type ProjectControllerSaveCheckpointErrors = {
  /**
   * The project holds as many named versions as it may
   */
  400: CheckpointLimitDto;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * File validation failed
   */
  422: unknown;
};

export type ProjectControllerSaveCheckpointError =
  ProjectControllerSaveCheckpointErrors[keyof ProjectControllerSaveCheckpointErrors];

export type ProjectControllerSaveCheckpointResponses = {
  /**
   * File uploaded successfully
   */
  201: unknown;
};

export type ProjectControllerDeleteCheckpointData = {
  body?: never;
  path: {
    id: string;
    name: string;
  };
  query?: never;
  url: '/projects/{id}/deleteCheckpoint/{name}';
};

export type ProjectControllerDeleteCheckpointErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerDeleteCheckpointResponses = {
  /**
   * File deleted successfully
   */
  201: unknown;
};

export type ProjectControllerPublishData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/publish';
};

export type ProjectControllerPublishErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Project content exceeds the publishing budget
   */
  413: ProjectTooLargeDto;
};

export type ProjectControllerPublishError =
  ProjectControllerPublishErrors[keyof ProjectControllerPublishErrors];

export type ProjectControllerPublishResponses = {
  /**
   * Project published successfully
   */
  201: unknown;
};

export type ProjectControllerUnpublishData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/unpublish';
};

export type ProjectControllerUnpublishErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerUnpublishResponses = {
  /**
   * Project unpublished successfully
   */
  201: unknown;
};

export type ProjectControllerGetVersionsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/versions';
};

export type ProjectControllerGetVersionsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetVersionsResponses = {
  /**
   * Project versions retrieved successfully
   */
  200: ProjectVersionsResponseDto;
};

export type ProjectControllerGetVersionsResponse =
  ProjectControllerGetVersionsResponses[keyof ProjectControllerGetVersionsResponses];

export type ProjectControllerGetCheckpointsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/checkpoints';
};

export type ProjectControllerGetCheckpointsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetCheckpointsResponses = {
  /**
   * Project checkpoints retrieved successfully
   */
  200: ProjectCheckpointsResponseDto;
};

export type ProjectControllerGetCheckpointsResponse =
  ProjectControllerGetCheckpointsResponses[keyof ProjectControllerGetCheckpointsResponses];

export type ProjectControllerDeleteVersionData = {
  body?: never;
  path: {
    id: string;
    version: string;
  };
  query?: never;
  url: '/projects/{id}/versions/{version}';
};

export type ProjectControllerDeleteVersionErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * No such version
   */
  404: unknown;
};

export type ProjectControllerDeleteVersionResponses = {
  /**
   * Version deleted successfully
   */
  200: unknown;
};

export type ProjectControllerGetVersionData = {
  body?: never;
  path: {
    id: string;
    version: string;
  };
  query?: never;
  url: '/projects/{id}/versions/{version}';
};

export type ProjectControllerGetVersionErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetVersionResponses = {
  /**
   * Project version retrieved successfully
   */
  200: Blob | File;
};

export type ProjectControllerGetVersionResponse =
  ProjectControllerGetVersionResponses[keyof ProjectControllerGetVersionResponses];

export type ProjectControllerGetCheckpointData = {
  body?: never;
  path: {
    id: string;
    checkpoint: string;
  };
  query?: never;
  url: '/projects/{id}/checkpoints/{checkpoint}';
};

export type ProjectControllerGetCheckpointErrors = {
  /**
   * Forbidden
   */
  403: unknown;
};

export type ProjectControllerGetCheckpointResponses = {
  /**
   * Project checkpoint retrieved successfully
   */
  200: Blob | File;
};

export type ProjectControllerGetCheckpointResponse =
  ProjectControllerGetCheckpointResponses[keyof ProjectControllerGetCheckpointResponses];

export type ProjectControllerUnlikeProjectData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/like';
};

export type ProjectControllerUnlikeProjectResponses = {
  /**
   * Like removed
   */
  200: LikeResponseDto;
};

export type ProjectControllerUnlikeProjectResponse =
  ProjectControllerUnlikeProjectResponses[keyof ProjectControllerUnlikeProjectResponses];

export type ProjectControllerLikeProjectData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/like';
};

export type ProjectControllerLikeProjectResponses = {
  /**
   * Like status
   */
  200: LikeResponseDto;
};

export type ProjectControllerLikeProjectResponse =
  ProjectControllerLikeProjectResponses[keyof ProjectControllerLikeProjectResponses];

export type ProjectControllerGetLikeStatusData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/like-status';
};

export type ProjectControllerGetLikeStatusResponses = {
  /**
   * Like status
   */
  200: LikeResponseDto;
};

export type ProjectControllerGetLikeStatusResponse =
  ProjectControllerGetLikeStatusResponses[keyof ProjectControllerGetLikeStatusResponses];

export type ProjectControllerRegisterReleaseViewData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/view';
};

export type ProjectControllerRegisterReleaseViewResponses = {
  /**
   * Updated view count
   */
  200: ViewResponseDto;
};

export type ProjectControllerRegisterReleaseViewResponse =
  ProjectControllerRegisterReleaseViewResponses[keyof ProjectControllerRegisterReleaseViewResponses];

export type ProjectControllerUpdateReleaseData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/update-release';
};

export type ProjectControllerUpdateReleaseErrors = {
  /**
   * Project is not published
   */
  400: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Project content exceeds the publishing budget
   */
  413: ProjectTooLargeDto;
};

export type ProjectControllerUpdateReleaseError =
  ProjectControllerUpdateReleaseErrors[keyof ProjectControllerUpdateReleaseErrors];

export type ProjectControllerUpdateReleaseResponses = {
  /**
   * Release updated successfully
   */
  200: unknown;
};

export type MultiplayerControllerListData = {
  body?: never;
  path?: never;
  query?: {
    projectId?: number;
    /**
     * Narrow to sessions whose room or game name holds this
     */
    q?: string;
  };
  url: '/game-sessions';
};

export type MultiplayerControllerListResponses = {
  200: GameSessionListResponseDto;
};

export type MultiplayerControllerListResponse =
  MultiplayerControllerListResponses[keyof MultiplayerControllerListResponses];

export type MultiplayerControllerCreateData = {
  body: CreateGameSessionDto;
  path?: never;
  query?: never;
  url: '/game-sessions';
};

export type MultiplayerControllerCreateResponses = {
  201: GameSessionConnectionResponseDto;
};

export type MultiplayerControllerCreateResponse =
  MultiplayerControllerCreateResponses[keyof MultiplayerControllerCreateResponses];

export type MultiplayerControllerJoinByCodeData = {
  body: JoinByCodeDto;
  path?: never;
  query?: never;
  url: '/game-sessions/join-by-code';
};

export type MultiplayerControllerJoinByCodeResponses = {
  200: GameSessionConnectionResponseDto;
};

export type MultiplayerControllerJoinByCodeResponse =
  MultiplayerControllerJoinByCodeResponses[keyof MultiplayerControllerJoinByCodeResponses];

export type MultiplayerControllerRemoveData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}';
};

export type MultiplayerControllerRemoveResponses = {
  200: unknown;
};

export type MultiplayerControllerGetData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}';
};

export type MultiplayerControllerGetResponses = {
  200: GameSessionResponseDto;
};

export type MultiplayerControllerGetResponse =
  MultiplayerControllerGetResponses[keyof MultiplayerControllerGetResponses];

export type MultiplayerControllerUpdateData = {
  body: UpdateGameSessionDto;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}';
};

export type MultiplayerControllerUpdateResponses = {
  200: unknown;
};

export type MultiplayerControllerPlayersData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}/players';
};

export type MultiplayerControllerPlayersResponses = {
  200: SessionRosterResponseDto;
};

export type MultiplayerControllerPlayersResponse =
  MultiplayerControllerPlayersResponses[keyof MultiplayerControllerPlayersResponses];

export type MultiplayerControllerInviteData = {
  body: InviteToSessionDto;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}/invite';
};

export type MultiplayerControllerInviteResponses = {
  200: unknown;
};

export type MultiplayerControllerJoinData = {
  body: JoinGameSessionDto;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}/join';
};

export type MultiplayerControllerJoinResponses = {
  200: GameSessionConnectionResponseDto;
};

export type MultiplayerControllerJoinResponse =
  MultiplayerControllerJoinResponses[keyof MultiplayerControllerJoinResponses];

export type MultiplayerControllerLeaveData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}/leave';
};

export type MultiplayerControllerLeaveResponses = {
  200: unknown;
};

export type MultiplayerControllerRefreshTicketData = {
  body?: RefreshTicketDto;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}/ticket';
};

export type MultiplayerControllerRefreshTicketResponses = {
  200: GameSessionConnectionResponseDto;
};

export type MultiplayerControllerRefreshTicketResponse =
  MultiplayerControllerRefreshTicketResponses[keyof MultiplayerControllerRefreshTicketResponses];

export type ProjectCommentControllerGetCommentsData = {
  body?: never;
  path: {
    projectId: number;
  };
  query?: {
    page?: number;
    limit?: number;
    sort?: 'newest' | 'oldest';
  };
  url: '/projects/{projectId}/comments';
};

export type ProjectCommentControllerGetCommentsResponses = {
  /**
   * Paginated list of comments
   */
  200: PaginatedCommentsResponseDto;
};

export type ProjectCommentControllerGetCommentsResponse =
  ProjectCommentControllerGetCommentsResponses[keyof ProjectCommentControllerGetCommentsResponses];

export type ProjectCommentControllerCreateCommentData = {
  body: CreateCommentDto;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/projects/{projectId}/comments';
};

export type ProjectCommentControllerCreateCommentResponses = {
  /**
   * Comment created
   */
  201: CommentResponseDto;
};

export type ProjectCommentControllerCreateCommentResponse =
  ProjectCommentControllerCreateCommentResponses[keyof ProjectCommentControllerCreateCommentResponses];

export type ProjectCommentControllerCreateReplyData = {
  body: CreateCommentDto;
  path: {
    projectId: number;
    commentId: number;
  };
  query?: never;
  url: '/projects/{projectId}/comments/{commentId}/reply';
};

export type ProjectCommentControllerCreateReplyResponses = {
  /**
   * Reply created
   */
  201: CommentResponseDto;
};

export type ProjectCommentControllerCreateReplyResponse =
  ProjectCommentControllerCreateReplyResponses[keyof ProjectCommentControllerCreateReplyResponses];

export type ProjectCommentControllerDeleteCommentData = {
  body?: never;
  path: {
    projectId: number;
    commentId: number;
  };
  query?: never;
  url: '/projects/{projectId}/comments/{commentId}';
};

export type ProjectCommentControllerDeleteCommentResponses = {
  /**
   * Comment deleted
   */
  204: void;
};

export type ProjectCommentControllerDeleteCommentResponse =
  ProjectCommentControllerDeleteCommentResponses[keyof ProjectCommentControllerDeleteCommentResponses];

export type ProjectCommentControllerUpdateCommentData = {
  body: CreateCommentDto;
  path: {
    commentId: number;
    projectId: number;
  };
  query?: never;
  url: '/projects/{projectId}/comments/{commentId}';
};

export type ProjectCommentControllerUpdateCommentResponses = {
  /**
   * Comment updated
   */
  200: CommentResponseDto;
};

export type ProjectCommentControllerUpdateCommentResponse =
  ProjectCommentControllerUpdateCommentResponses[keyof ProjectCommentControllerUpdateCommentResponses];

export type NotificationsControllerGetWebRtcOfferData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/notifications/webrtc-offer';
};

export type NotificationsControllerGetWebRtcOfferResponses = {
  /**
   * Notification websocket configuration
   */
  200: unknown;
};

export type NotificationsControllerSendTestNotificationData = {
  body: NotificationTestDto;
  path?: never;
  query?: never;
  url: '/notifications/test';
};

export type NotificationsControllerSendTestNotificationResponses = {
  /**
   * Notification created and sent
   */
  200: unknown;
};

export type NotificationsControllerMarkAllAsReadData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/notifications/read-all';
};

export type NotificationsControllerMarkAllAsReadResponses = {
  /**
   * Number of notifications marked as read
   */
  200: unknown;
};

export type NotificationsControllerMarkAsReadData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/notifications/{id}/read';
};

export type NotificationsControllerMarkAsReadResponses = {
  /**
   * Notification marked as read
   */
  200: unknown;
};

export type FriendsControllerListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/friends';
};

export type FriendsControllerListResponses = {
  200: Array<FriendDto>;
};

export type FriendsControllerListResponse =
  FriendsControllerListResponses[keyof FriendsControllerListResponses];

export type FriendsControllerRequestsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/friends/requests';
};

export type FriendsControllerRequestsResponses = {
  200: Array<FriendRequestDto>;
};

export type FriendsControllerRequestsResponse =
  FriendsControllerRequestsResponses[keyof FriendsControllerRequestsResponses];

export type FriendsControllerSendData = {
  body: SendFriendRequestDto;
  path?: never;
  query?: never;
  url: '/friends/requests';
};

export type FriendsControllerSendErrors = {
  /**
   * Target user not found
   */
  404: unknown;
  /**
   * Already friends or already requested
   */
  409: unknown;
};

export type FriendsControllerSendResponses = {
  /**
   * The created request, or empty when a crossed request was auto-accepted
   */
  201: FriendRequestDto;
};

export type FriendsControllerSendResponse =
  FriendsControllerSendResponses[keyof FriendsControllerSendResponses];

export type FriendsControllerAcceptData = {
  body?: never;
  path: {
    /**
     * Friend request ID
     */
    id: number;
  };
  query?: never;
  url: '/friends/requests/{id}/accept';
};

export type FriendsControllerAcceptErrors = {
  /**
   * Request not found
   */
  404: unknown;
};

export type FriendsControllerAcceptResponses = {
  204: void;
};

export type FriendsControllerAcceptResponse =
  FriendsControllerAcceptResponses[keyof FriendsControllerAcceptResponses];

export type FriendsControllerDeclineData = {
  body?: never;
  path: {
    /**
     * Friend request ID
     */
    id: number;
  };
  query?: never;
  url: '/friends/requests/{id}';
};

export type FriendsControllerDeclineErrors = {
  /**
   * Request not found
   */
  404: unknown;
};

export type FriendsControllerDeclineResponses = {
  204: void;
};

export type FriendsControllerDeclineResponse =
  FriendsControllerDeclineResponses[keyof FriendsControllerDeclineResponses];

export type FriendsControllerRecentPlayersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Look-back window (default 30)
     */
    days?: number;
  };
  url: '/friends/recent-players';
};

export type FriendsControllerRecentPlayersResponses = {
  200: Array<RecentPlayerDto>;
};

export type FriendsControllerRecentPlayersResponse =
  FriendsControllerRecentPlayersResponses[keyof FriendsControllerRecentPlayersResponses];

export type FriendsControllerRemoveData = {
  body?: never;
  path: {
    /**
     * ID of the friend to remove
     */
    userId: number;
  };
  query?: never;
  url: '/friends/{userId}';
};

export type FriendsControllerRemoveErrors = {
  /**
   * Not friends
   */
  404: unknown;
};

export type FriendsControllerRemoveResponses = {
  204: void;
};

export type FriendsControllerRemoveResponse =
  FriendsControllerRemoveResponses[keyof FriendsControllerRemoveResponses];

export type UserFriendshipControllerFriendshipData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/friendship';
};

export type UserFriendshipControllerFriendshipResponses = {
  200: FriendshipStatusDto;
};

export type UserFriendshipControllerFriendshipResponse =
  UserFriendshipControllerFriendshipResponses[keyof UserFriendshipControllerFriendshipResponses];

export type PresenceControllerFriendsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/presence/friends';
};

export type PresenceControllerFriendsResponses = {
  200: Array<PresenceDto>;
};

export type PresenceControllerFriendsResponse =
  PresenceControllerFriendsResponses[keyof PresenceControllerFriendsResponses];

export type UserPresenceControllerPresenceData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/presence';
};

export type UserPresenceControllerPresenceErrors = {
  /**
   * User is offline
   */
  404: unknown;
};

export type UserPresenceControllerPresenceResponses = {
  200: PresenceDto;
};

export type UserPresenceControllerPresenceResponse =
  UserPresenceControllerPresenceResponses[keyof UserPresenceControllerPresenceResponses];

export type FeaturedReleaseControllerGetFeaturedData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/releases/featured';
};

export type FeaturedReleaseControllerGetFeaturedResponses = {
  /**
   * The featured release, or null when none is set
   */
  200: FeaturedReleaseResponseDto;
};

export type FeaturedReleaseControllerGetFeaturedResponse =
  FeaturedReleaseControllerGetFeaturedResponses[keyof FeaturedReleaseControllerGetFeaturedResponses];

export type AdminFeaturedReleaseControllerClearFeaturedData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/admin/featured-release';
};

export type AdminFeaturedReleaseControllerClearFeaturedErrors = {
  /**
   * Admin role required
   */
  403: unknown;
};

export type AdminFeaturedReleaseControllerClearFeaturedResponses = {
  /**
   * No featured release remains
   */
  204: void;
};

export type AdminFeaturedReleaseControllerClearFeaturedResponse =
  AdminFeaturedReleaseControllerClearFeaturedResponses[keyof AdminFeaturedReleaseControllerClearFeaturedResponses];

export type AdminFeaturedReleaseControllerSetFeaturedData = {
  body: SetFeaturedReleaseDto;
  path?: never;
  query?: never;
  url: '/admin/featured-release';
};

export type AdminFeaturedReleaseControllerSetFeaturedErrors = {
  /**
   * Project is not published
   */
  400: unknown;
  /**
   * Admin role required
   */
  403: unknown;
  /**
   * Project not found
   */
  404: unknown;
};

export type AdminFeaturedReleaseControllerSetFeaturedResponses = {
  /**
   * The new featured release
   */
  200: FeaturedReleaseDto;
};

export type AdminFeaturedReleaseControllerSetFeaturedResponse =
  AdminFeaturedReleaseControllerSetFeaturedResponses[keyof AdminFeaturedReleaseControllerSetFeaturedResponses];

export type AdminFeaturedReleaseControllerGetHistoryData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/admin/featured-release/history';
};

export type AdminFeaturedReleaseControllerGetHistoryErrors = {
  /**
   * Admin role required
   */
  403: unknown;
};

export type AdminFeaturedReleaseControllerGetHistoryResponses = {
  /**
   * Featured releases, newest first
   */
  200: FeaturedReleaseHistoryDto;
};

export type AdminFeaturedReleaseControllerGetHistoryResponse =
  AdminFeaturedReleaseControllerGetHistoryResponses[keyof AdminFeaturedReleaseControllerGetHistoryResponses];

export type AuthControllerLoginData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type AuthControllerLoginErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Invalid credentials
   */
  401: unknown;
};

export type AuthControllerLoginResponses = {
  /**
   * User logged in successfully
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerGetPasswordPolicyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/password-policy';
};

export type AuthControllerGetPasswordPolicyResponses = {
  200: PasswordPolicyDto;
};

export type AuthControllerGetPasswordPolicyResponse =
  AuthControllerGetPasswordPolicyResponses[keyof AuthControllerGetPasswordPolicyResponses];

export type AuthControllerRegisterData = {
  body: CreateUserDto;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type AuthControllerRegisterErrors = {
  /**
   * Bad request
   */
  400: ValidationErrorResponseDto;
  /**
   * Email or username already in use
   */
  409: ConflictErrorResponseDto;
};

export type AuthControllerRegisterError =
  AuthControllerRegisterErrors[keyof AuthControllerRegisterErrors];

export type AuthControllerRegisterResponses = {
  /**
   * User registered successfully
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginWithGoogleCodeData = {
  body: GoogleCodeDto;
  path?: never;
  query?: never;
  url: '/auth/google/code';
};

export type AuthControllerLoginWithGoogleCodeErrors = {
  /**
   * Invalid Google code or code_verifier
   */
  401: unknown;
};

export type AuthControllerLoginWithGoogleCodeResponses = {
  /**
   * Login successful with Google
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerLoginWithGoogleCodeResponse =
  AuthControllerLoginWithGoogleCodeResponses[keyof AuthControllerLoginWithGoogleCodeResponses];

export type AuthControllerLoginWithGithubData = {
  body: GithubLoginDto;
  path?: never;
  query?: never;
  url: '/auth/github';
};

export type AuthControllerLoginWithGithubErrors = {
  /**
   * Invalid or expired GitHub code
   */
  401: unknown;
};

export type AuthControllerLoginWithGithubResponses = {
  /**
   * Login successful with GitHub
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerLoginWithGithubResponse =
  AuthControllerLoginWithGithubResponses[keyof AuthControllerLoginWithGithubResponses];

export type AuthControllerLoginWithMicrosoftData = {
  body: MicrosoftLoginDto;
  path?: never;
  query?: never;
  url: '/auth/microsoft';
};

export type AuthControllerLoginWithMicrosoftErrors = {
  /**
   * Invalid Microsoft ID token
   */
  401: unknown;
};

export type AuthControllerLoginWithMicrosoftResponses = {
  /**
   * Login successful with Microsoft
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerLoginWithMicrosoftResponse =
  AuthControllerLoginWithMicrosoftResponses[keyof AuthControllerLoginWithMicrosoftResponses];

export type AuthControllerRefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/refresh';
};

export type AuthControllerRefreshErrors = {
  /**
   * Refresh token missing or invalid
   */
  401: unknown;
};

export type AuthControllerRefreshResponses = {
  /**
   * Access token refreshed successfully
   */
  201: {
    access_token: string;
  };
};

export type AuthControllerRefreshResponse =
  AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerChangePasswordData = {
  body: ChangePasswordDto;
  path?: never;
  query?: never;
  url: '/auth/password';
};

export type AuthControllerChangePasswordErrors = {
  /**
   * Current password required for non-OAuth accounts
   */
  400: unknown;
  /**
   * Current password incorrect
   */
  401: unknown;
};

export type AuthControllerChangePasswordResponses = {
  /**
   * Password updated successfully
   */
  200: unknown;
};

export type AuthControllerLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
  /**
   * Logout successful
   */
  200: unknown;
};

export type UserControllerGetProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/profile';
};

export type UserControllerGetProfileErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerGetProfileResponses = {
  /**
   * Returns the current user profile
   */
  200: UserProfileResponseDto;
};

export type UserControllerGetProfileResponse =
  UserControllerGetProfileResponses[keyof UserControllerGetProfileResponses];

export type UserControllerUpdateMyProfileData = {
  body: UpdateUserProfileDto;
  path?: never;
  query?: never;
  url: '/users/profile';
};

export type UserControllerUpdateMyProfileErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * The handle asked for belongs to someone else
   */
  409: unknown;
};

export type UserControllerUpdateMyProfileResponses = {
  /**
   * User profile updated successfully
   */
  200: PublicUserProfileResponseDto;
};

export type UserControllerUpdateMyProfileResponse =
  UserControllerUpdateMyProfileResponses[keyof UserControllerUpdateMyProfileResponses];

export type UserControllerDeleteMeData = {
  body: DeleteAccountDto;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type UserControllerDeleteMeErrors = {
  /**
   * Missing DELETE confirmation
   */
  400: unknown;
  /**
   * Unauthorized or wrong password
   */
  401: unknown;
};

export type UserControllerDeleteMeResponses = {
  /**
   * Account deleted, refresh cookie cleared
   */
  204: void;
};

export type UserControllerDeleteMeResponse =
  UserControllerDeleteMeResponses[keyof UserControllerDeleteMeResponses];

export type UserControllerGetMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type UserControllerGetMeErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerGetMeResponses = {
  200: MeDto;
};

export type UserControllerGetMeResponse =
  UserControllerGetMeResponses[keyof UserControllerGetMeResponses];

export type UserControllerUpdateMeData = {
  body: UpdateMeDto;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type UserControllerUpdateMeErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerUpdateMeResponses = {
  200: MeDto;
};

export type UserControllerUpdateMeResponse =
  UserControllerUpdateMeResponses[keyof UserControllerUpdateMeResponses];

export type UserControllerRegenerateFriendCodeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/me/friend-code/regenerate';
};

export type UserControllerRegenerateFriendCodeErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerRegenerateFriendCodeResponses = {
  200: MeDto;
};

export type UserControllerRegenerateFriendCodeResponse =
  UserControllerRegenerateFriendCodeResponses[keyof UserControllerRegenerateFriendCodeResponses];

export type UserControllerRemoveProfilePictureData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/profile-picture';
};

export type UserControllerRemoveProfilePictureErrors = {
  /**
   * Not your profile
   */
  403: unknown;
};

export type UserControllerRemoveProfilePictureResponses = {
  /**
   * Removed, or there was none
   */
  200: unknown;
};

export type UserControllerGetProfilePictureData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/profile-picture';
};

export type UserControllerGetProfilePictureErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type UserControllerGetProfilePictureResponses = {
  /**
   * Signed cookies and CDN resource URL
   */
  200: SignedCdnResourceDto;
};

export type UserControllerGetProfilePictureResponse =
  UserControllerGetProfilePictureResponses[keyof UserControllerGetProfilePictureResponses];

export type UserControllerUploadProfilePictureData = {
  body: {
    /**
     * Profile picture file
     */
    file?: Blob | File;
  };
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/profile-picture';
};

export type UserControllerUploadProfilePictureErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerUploadProfilePictureResponses = {
  /**
   * Profile uploaded
   */
  201: ProfileImageUploadResponseDto;
};

export type UserControllerUploadProfilePictureResponse =
  UserControllerUploadProfilePictureResponses[keyof UserControllerUploadProfilePictureResponses];

export type UserControllerRemoveProfileBackgroundData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/profile-background';
};

export type UserControllerRemoveProfileBackgroundErrors = {
  /**
   * Not your profile
   */
  403: unknown;
};

export type UserControllerRemoveProfileBackgroundResponses = {
  /**
   * Removed, or there was none
   */
  200: unknown;
};

export type UserControllerUploadProfileBackgroundData = {
  body: {
    /**
     * Profile background file
     */
    file?: Blob | File;
  };
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/profile-background';
};

export type UserControllerUploadProfileBackgroundErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerUploadProfileBackgroundResponses = {
  /**
   * Profile background uploaded
   */
  201: ProfileImageUploadResponseDto;
};

export type UserControllerUploadProfileBackgroundResponse =
  UserControllerUploadProfileBackgroundResponses[keyof UserControllerUploadProfileBackgroundResponses];

export type UserControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Free-text search over username and nickname — what a person types into the search box, where they do not know which of the two they are looking at
     */
    q?: string;
    /**
     * Filter by nickname
     */
    nickname?: string;
    /**
     * Filter by email
     */
    email?: string;
    /**
     * Sort by field
     */
    sortBy?: 'id' | 'username' | 'email' | 'createdAt';
    /**
     * Sort order
     */
    order?: 'asc' | 'desc';
  };
  url: '/users';
};

export type UserControllerFindAllErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type UserControllerFindAllResponses = {
  /**
   * Returns paginated list of users
   */
  200: UserListResponseDto;
};

export type UserControllerFindAllResponse =
  UserControllerFindAllResponses[keyof UserControllerFindAllResponses];

export type UserControllerRemoveData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}';
};

export type UserControllerRemoveErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Insufficient permissions
   */
  403: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UserControllerRemoveResponses = {
  /**
   * User deleted successfully
   */
  200: {
    statusCode?: number;
    message?: string;
  };
};

export type UserControllerRemoveResponse =
  UserControllerRemoveResponses[keyof UserControllerRemoveResponses];

export type UserControllerFindOneData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}';
};

export type UserControllerFindOneErrors = {
  /**
   * Invalid ID format
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UserControllerFindOneResponses = {
  /**
   * Returns the user
   */
  200: UserSingleResponseDto;
};

export type UserControllerFindOneResponse =
  UserControllerFindOneResponses[keyof UserControllerFindOneResponses];

export type UserControllerUpdateData = {
  body: UpdateUserDto;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}';
};

export type UserControllerUpdateErrors = {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Insufficient permissions
   */
  403: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UserControllerUpdateResponses = {
  /**
   * User updated successfully
   */
  200: UserSingleResponseDto;
};

export type UserControllerUpdateResponse =
  UserControllerUpdateResponses[keyof UserControllerUpdateResponses];

export type UserPublicControllerSearchData = {
  body?: never;
  path?: never;
  query: {
    /**
     * What was typed
     */
    q: string;
    limit?: number;
  };
  url: '/users/public/search';
};

export type UserPublicControllerSearchResponses = {
  /**
   * Matching people, exact handle first
   */
  200: PublicUserSearchResponseDto;
};

export type UserPublicControllerSearchResponse =
  UserPublicControllerSearchResponses[keyof UserPublicControllerSearchResponses];

export type UserPublicControllerGetPublicProfileData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/public/{id}/profile';
};

export type UserPublicControllerGetPublicProfileErrors = {
  /**
   * User not found
   */
  404: unknown;
};

export type UserPublicControllerGetPublicProfileResponses = {
  /**
   * Returns the public user profile
   */
  200: PublicUserProfileResponseDto;
};

export type UserPublicControllerGetPublicProfileResponse =
  UserPublicControllerGetPublicProfileResponses[keyof UserPublicControllerGetPublicProfileResponses];

export type UserPublicControllerGetPublicProfileByUsernameData = {
  body?: never;
  path: {
    /**
     * Username
     */
    username: string;
  };
  query?: never;
  url: '/users/public/username/{username}/profile';
};

export type UserPublicControllerGetPublicProfileByUsernameErrors = {
  /**
   * User not found
   */
  404: unknown;
};

export type UserPublicControllerGetPublicProfileByUsernameResponses = {
  /**
   * Returns the public user profile
   */
  200: PublicUserProfileResponseDto;
};

export type UserPublicControllerGetPublicProfileByUsernameResponse =
  UserPublicControllerGetPublicProfileByUsernameResponses[keyof UserPublicControllerGetPublicProfileByUsernameResponses];

export type UserPublicControllerGetLikedGamesData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/users/public/{id}/likes';
};

export type UserPublicControllerGetLikedGamesResponses = {
  /**
   * Returns the list of published games liked by the user
   */
  200: Array<ProjectExResponseDto>;
};

export type UserPublicControllerGetLikedGamesResponse =
  UserPublicControllerGetLikedGamesResponses[keyof UserPublicControllerGetLikedGamesResponses];

export type UserPublicControllerGetPublishedGamesData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: {
    page?: number;
    limit?: number;
    /**
     * Only the games this user owns, rather than every game they are credited on
     */
    ownedOnly?: string;
  };
  url: '/users/public/{id}/published-games';
};

export type UserPublicControllerGetPublishedGamesResponses = {
  /**
   * Returns the list of games published by the user
   */
  200: Array<ProjectExResponseDto>;
};

export type UserPublicControllerGetPublishedGamesResponse =
  UserPublicControllerGetPublishedGamesResponses[keyof UserPublicControllerGetPublishedGamesResponses];

export type UserPublicControllerGetCollaborationsData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/users/public/{id}/collaborations';
};

export type UserPublicControllerGetCollaborationsResponses = {
  /**
   * Games the user helped build but does not own
   */
  200: Array<ProjectExResponseDto>;
};

export type UserPublicControllerGetCollaborationsResponse =
  UserPublicControllerGetCollaborationsResponses[keyof UserPublicControllerGetCollaborationsResponses];

export type UserPublicControllerGetRemixesData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/users/public/{id}/remixes';
};

export type UserPublicControllerGetRemixesResponses = {
  /**
   * Games other people forked from one of this user's
   */
  200: Array<ProjectExResponseDto>;
};

export type UserPublicControllerGetRemixesResponse =
  UserPublicControllerGetRemixesResponses[keyof UserPublicControllerGetRemixesResponses];

export type WorkSessionControllerJoinData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/work-sessions/join/{id}';
};

export type WorkSessionControllerJoinErrors = {
  /**
   * Bad request.
   */
  400: unknown;
};

export type WorkSessionControllerJoinResponses = {
  /**
   * The work session has been successfully created.
   */
  201: JoinWorkSessionDto;
};

export type WorkSessionControllerJoinResponse =
  WorkSessionControllerJoinResponses[keyof WorkSessionControllerJoinResponses];

export type WorkSessionControllerLeaveData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/work-sessions/leave/{id}';
};

export type WorkSessionControllerLeaveErrors = {
  /**
   * Bad request.
   */
  400: unknown;
};

export type WorkSessionControllerLeaveResponses = {
  /**
   * Successfully left the work session.
   */
  204: void;
};

export type WorkSessionControllerLeaveResponse =
  WorkSessionControllerLeaveResponses[keyof WorkSessionControllerLeaveResponses];

export type WorkSessionControllerKickData = {
  body: KickWorkSessionDto;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/work-sessions/kick/{id}';
};

export type WorkSessionControllerKickErrors = {
  /**
   * Bad request.
   */
  400: unknown;
};

export type WorkSessionControllerKickResponses = {
  /**
   * Successfully left the work session.
   */
  204: void;
};

export type WorkSessionControllerKickResponse =
  WorkSessionControllerKickResponses[keyof WorkSessionControllerKickResponses];

export type WorkSessionControllerGetInfoData = {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/work-sessions/info/{id}';
};

export type WorkSessionControllerGetInfoErrors = {
  /**
   * Work session not found.
   */
  404: unknown;
};

export type WorkSessionControllerGetInfoResponses = {
  /**
   * Work session info retrieved successfully.
   */
  200: FetchWorkSessionDto;
};

export type WorkSessionControllerGetInfoResponse =
  WorkSessionControllerGetInfoResponses[keyof WorkSessionControllerGetInfoResponses];
