// This file is auto-generated by @hey-api/openapi-ts

export interface ClientOptions {
  baseUrl: string;
}

export interface UserBasicInfoDto {
  /**
   * The unique identifier of the user
   */
  id: number;
  /**
   * The username
   */
  username: string;
  /**
   * The email address
   */
  email: string;
}

export interface ProjectExResponseDto {
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * Tags associated with the project
   */
  tags: string[];
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED';
  /**
   * The monetization strategy for this project
   */
  monetization: 'NONE' | 'ADS' | 'PAID';
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The date and time when the project was last updated
   */
  updatedAt: string;
  /**
   * The date and time when the project was last published
   */
  publishedAt: string | null;
  /**
   * The number of times players opened this game's play page
   */
  viewCount: number;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The number of comments on the project
   */
  commentCount?: number;
  /**
   * The number of forks created from this project
   */
  forkCount?: number;
  /**
   * The ID of the project this was forked from, if any
   */
  forkedFromId?: number | null;
  /**
   * The users collaborating on this project
   */
  collaborators: UserBasicInfoDto[];
  /**
   * The creator of this project
   */
  creator: UserBasicInfoDto;
}

export interface PaginatedProjectsResponseDto {
  /**
   * The projects included in the current page
   */
  projects: ProjectExResponseDto[];
  /**
   * The total number of projects matching the request
   */
  total: number;
  /**
   * The current page number
   */
  page: number;
  /**
   * The number of projects requested per page
   */
  limit: number;
}

export interface ProjectsCountResponseDto {
  /**
   * The total number of projects matching the request
   */
  total: number;
}

export interface SignedUrlResponseDto {
  /**
   * The signed CloudFront URL for accessing the protected file
   */
  signedUrl: string;
}

export interface ProjectResponseDto {
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * Tags associated with the project
   */
  tags: string[];
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED';
  /**
   * The monetization strategy for this project
   */
  monetization: 'NONE' | 'ADS' | 'PAID';
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The date and time when the project was last updated
   */
  updatedAt: string;
  /**
   * The date and time when the project was last published
   */
  publishedAt: string | null;
  /**
   * The number of times players opened this game's play page
   */
  viewCount: number;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The number of comments on the project
   */
  commentCount?: number;
  /**
   * The number of forks created from this project
   */
  forkCount?: number;
  /**
   * The ID of the project this was forked from, if any
   */
  forkedFromId?: number | null;
}

export interface CreateProjectDto {
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * URL to the project icon
   */
  iconUrl?: string;
  /**
   * Tags attached to the project
   */
  tags?: string[];
}

export interface ForkProjectResponseDto {
  /**
   * The unique identifier of the project
   */
  id: number;
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc: string | null;
  /**
   * Tags associated with the project
   */
  tags: string[];
  /**
   * URL to the project icon
   */
  iconUrl: string | null;
  /**
   * The current status of the project
   */
  status: 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED';
  /**
   * The monetization strategy for this project
   */
  monetization: 'NONE' | 'ADS' | 'PAID';
  /**
   * The price of the project, if applicable
   */
  price: number | null;
  /**
   * The ID of the user who owns this project
   */
  userId: number;
  /**
   * The date and time when the project was created
   */
  createdAt: string;
  /**
   * The date and time when the project was last updated
   */
  updatedAt: string;
  /**
   * The date and time when the project was last published
   */
  publishedAt: string | null;
  /**
   * The number of times players opened this game's play page
   */
  viewCount: number;
  /**
   * The number of unique players who have interacted with this project
   */
  uniquePlayers: number;
  /**
   * The number of currently active players in this project
   */
  activePlayers: number;
  /**
   * The number of likes received by the project
   */
  likes: number;
  /**
   * The number of comments on the project
   */
  commentCount?: number;
  /**
   * The number of forks created from this project
   */
  forkCount?: number;
  /**
   * The ID of the project this was forked from, if any
   */
  forkedFromId?: number | null;
  /**
   * The users collaborating on this project
   */
  collaborators: UserBasicInfoDto[];
  /**
   * The creator of this project
   */
  creator: UserBasicInfoDto;
}

export interface UpdateProjectDto {
  /**
   * The name of the project
   */
  name: string;
  /**
   * A short description of the project
   */
  shortDesc: string;
  /**
   * A detailed description of the project
   */
  longDesc?: Record<string, unknown>;
  /**
   * Tags attached to the project
   */
  tags?: string[];
  /**
   * URL to the project icon
   */
  iconUrl?: string;
  /**
   * Project status
   */
  status?: 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED';
  /**
   * Monetization type
   */
  monetization?: 'NONE' | 'ADS' | 'PAID';
  /**
   * The price of the project
   */
  price?: number;
}

export interface AddCollaboratorDto {
  /**
   * User ID of the user to add as collaborator
   */
  userId?: number;
  /**
   * Username of the user to add as collaborator
   */
  username?: string;
  /**
   * Email of the user to add as collaborator
   */
  email?: string;
}

export interface RemoveCollaboratorDto {
  /**
   * User ID of the user to remove as collaborator
   */
  userId?: number;
  /**
   * Username of the user to remove as collaborator
   */
  username?: string;
  /**
   * Email of the user to remove as collaborator
   */
  email?: string;
}

export interface ImageUrlResponseDto {
  /**
   * The public CDN URL for the image
   */
  url: string;
}

export interface LikeResponseDto {
  /**
   * Total number of likes on the project
   */
  likes: number;
  /**
   * Whether the current user has liked this project
   */
  liked: boolean;
}

export interface ViewResponseDto {
  /**
   * The number of play opens registered for the project
   */
  viewCount: number;
}

export interface CreateGameSessionDto {
  /**
   * ID of the project this session is played on
   */
  projectId: number;
  /**
   * Human-readable title of the session
   */
  title: string;
  /**
   * Maximum number of players, host included
   */
  maxPlayers: number;
  visibility: 'PUBLIC' | 'FRIENDS_ONLY' | 'INVITE_CODE';
}

export interface WebRtcOfferPeerIceServerConfig {
  urls: string;
  username?: Record<string, unknown>;
  credential?: Record<string, unknown>;
}

export interface WebRtcOfferPeerOptsConfig {
  iceServers: WebRtcOfferPeerIceServerConfig[];
}

export interface WebRtcOfferPeerOpts {
  config: WebRtcOfferPeerOptsConfig;
}

export interface WebRtcOfferDto {
  signaling: string[];
  maxConns: number;
  peerOpts: WebRtcOfferPeerOpts;
}

export interface GameSessionConnectionResponseDto {
  sessionUuid: string;
  /**
   * Player id assigned to this connection
   */
  playerId: number;
  webrtcConfig: WebRtcOfferDto;
  /**
   * Short-lived signed ticket presented on the WebRTC connection
   */
  connectionTicket: string;
  /**
   * Join code to share, present only when hosting an INVITE_CODE session
   */
  joinCode?: string;
}

export interface JoinByCodeDto {
  /**
   * Invite code of the session to join
   */
  joinCode: string;
  /**
   * Set by the game editor to allow a self-join for solo testing
   */
  editorTest?: boolean;
}

export interface GameSessionResponseDto {
  sessionUuid: string;
  title: string;
  visibility: 'PUBLIC' | 'FRIENDS_ONLY' | 'INVITE_CODE';
  /**
   * ID of the host user
   */
  hostId: number;
  /**
   * Username of the host
   */
  hostUsername: string;
  /**
   * Display nickname of the host, if set
   */
  hostNickname?: string;
  /**
   * Name of the game (project) being played
   */
  projectName: string;
  /**
   * Maximum number of players, host included
   */
  maxPlayers: number;
  /**
   * Current number of players, host included
   */
  playerCount: number;
}

export interface GameSessionListResponseDto {
  sessions: GameSessionResponseDto[];
}

export interface UpdateGameSessionDto {
  /**
   * New title of the session
   */
  title?: string;
  /**
   * New maximum number of players, host included
   */
  maxPlayers?: number;
  visibility?: 'PUBLIC' | 'FRIENDS_ONLY' | 'INVITE_CODE';
}

export interface JoinGameSessionDto {
  /**
   * Join code, required for INVITE_CODE sessions
   */
  joinCode?: string;
  /**
   * Set by the game editor to allow a self-join for solo testing
   */
  editorTest?: boolean;
}

export interface CommentAuthorDto {
  id: number;
  username: string;
  nickname?: string | null;
}

export interface CommentResponseDto {
  id: number;
  content: string;
  createdAt: string;
  projectId: number;
  author: CommentAuthorDto;
  deleted?: boolean;
  /**
   * Replies to this comment (only for top-level comments)
   */
  replies?: CommentResponseDto[];
}

export interface PaginatedCommentsResponseDto {
  comments: CommentResponseDto[];
  total: number;
  page: number;
  limit: number;
}

export interface CreateCommentDto {
  /**
   * The content of the comment
   */
  content: string;
}

export interface NotificationTestDto {
  /**
   * The title of the test notification
   */
  title: string;
  /**
   * The message content of the test notification
   */
  message: string;
  /**
   * The type of the notification
   */
  type: 'INFO' | 'WARNING';
}

export interface LoginDto {
  /**
   * User email address
   */
  email: string;
  /**
   * User password
   */
  password: string;
}

export interface CreateUserDto {
  /**
   * User email address
   */
  email: string;
  /**
   * User username
   */
  username: string;
  /**
   * User nick name
   */
  nickname?: string;
  /**
   * User password
   */
  password: string;
}

export interface GoogleCodeDto {
  /**
   * Google authorization code
   */
  code: string;
  /**
   * PKCE code verifier
   */
  codeVerifier: string;
}

export interface GithubLoginDto {
  /**
   * GitHub OAuth authorization code
   */
  code: string;
}

export interface MicrosoftLoginDto {
  /**
   * Microsoft ID token
   */
  token: string;
}

export interface ChangePasswordDto {
  /**
   * Current password (not required for OAuth accounts)
   */
  currentPassword?: string;
  /**
   * New password
   */
  newPassword: string;
}

export interface UserRoleDto {
  /**
   * Role ID
   */
  id: number;
  /**
   * Role name
   */
  name: string;
}

export interface UserResponseDto {
  /**
   * User ID
   */
  id: number;
  /**
   * User email address
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname
   */
  nickname: string | null;
  /**
   * User roles
   */
  roles?: UserRoleDto[];
  /**
   * User creation date
   */
  createdAt: string;
  /**
   * User last update date
   */
  updatedAt: string;
}

export interface PaginationMetaDto {
  /**
   * Current page number
   */
  page: number;
  /**
   * Number of items per page
   */
  limit: number;
  /**
   * Total number of items
   */
  total: number;
  /**
   * Total number of pages
   */
  totalPages: number;
}

export interface UserListResponseDto {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * List of users
   */
  data: UserResponseDto[];
  /**
   * Pagination metadata
   */
  meta: PaginationMetaDto;
}

export interface UserSingleResponseDto {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * User data
   */
  data: UserResponseDto;
}

export interface UserProfileResponseDto {
  /**
   * User ID
   */
  id: number;
  /**
   * User email address
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname
   */
  nickname: string | null;
  /**
   * User roles
   */
  roles?: UserRoleDto[];
  /**
   * User creation date
   */
  createdAt: string;
  /**
   * User last update date
   */
  updatedAt: string;
  /**
   * User profile message
   */
  message: string;
}

export interface PublicUserProfileDto {
  /**
   * User ID
   */
  id: number;
  /**
   * Username
   */
  username: string;
  /**
   * User nickname / bio
   */
  nickname?: string | null;
  /**
   * User profile description
   */
  description?: string | null;
  /**
   * Public CDN URL of the profile image (if any)
   */
  profileImageUrl?: string | null;
  /**
   * Public CDN URL of the profile background image (if any)
   */
  backgroundImageUrl?: string | null;
}

export interface PublicUserProfileResponseDto {
  /**
   * HTTP status code
   */
  statusCode: number;
  /**
   * Response message
   */
  message: string;
  /**
   * Public user profile
   */
  data: PublicUserProfileDto;
}

export interface UpdateUserProfileDto {
  /**
   * Public nickname / bio displayed on the profile
   */
  nickname?: string;
  /**
   * Public profile description displayed on the profile
   */
  description?: string;
}

export interface SignedCdnResourceDto {
  /**
   * The CDN URL for the resource (requires signed cookies)
   */
  resourceUrl: string;
  /**
   * Signed Edge cookies (also set as HTTP-only cookies)
   */
  cookies: Record<string, unknown>;
}

export interface UpdateUserDto {
  /**
   * User email address
   */
  email?: string;
  /**
   * User username
   */
  username?: string;
  /**
   * User nick name
   */
  nickname?: string;
  /**
   * User password
   */
  password?: string;
}

export interface JoinWorkSessionDto {
  /**
   * The unique room ID for the work session
   */
  roomId: string;
  /**
   * The user ID of the session's host
   */
  hostId: number;
  /**
   * The WebRTC offer given to the client
   */
  webrtcOffer: WebRtcOfferDto;
}

export interface KickWorkSessionDto {
  /**
   * The ID of the user participating in the work session
   */
  userId: number;
}

export interface FetchWorkSessionDto {
  /**
   * The ID of the user participating in the work session
   */
  users: string[];
  /**
   * The ID of the session's host
   */
  hostId: number;
  /**
   * The ID of the project this work session belongs to
   */
  project: number;
  /**
   * The date and time when the work session started
   */
  startedAt: string;
  /**
   * The ID of the room for this work session
   */
  roomId: string;
}

export interface ProjectControllerGetAllReleasesData {
  body?: never;
  path?: never;
  query?: never;
  url: '/projects/releases';
}

export interface ProjectControllerGetAllReleasesResponses {
  /**
   * A JSON array of projects with collaborators and creator information
   */
  200: ProjectExResponseDto[];
}

export type ProjectControllerGetAllReleasesResponse =
  ProjectControllerGetAllReleasesResponses[keyof ProjectControllerGetAllReleasesResponses];

export interface ProjectControllerGetPaginatedReleasesData {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/projects/releases/paginated';
}

export interface ProjectControllerGetPaginatedReleasesResponses {
  /**
   * A paginated list of released projects
   */
  200: PaginatedProjectsResponseDto;
}

export type ProjectControllerGetPaginatedReleasesResponse =
  ProjectControllerGetPaginatedReleasesResponses[keyof ProjectControllerGetPaginatedReleasesResponses];

export interface ProjectControllerCountReleasedProjectsData {
  body?: never;
  path?: never;
  query?: {
    search?: string;
    /**
     * Comma-separated tag list
     */
    tags?: string;
    releaseWindow?: 'all' | '365d' | '30d' | '7d';
  };
  url: '/projects/releases/count';
}

export interface ProjectControllerCountReleasedProjectsResponses {
  /**
   * The total number of released projects matching the request
   */
  200: ProjectsCountResponseDto;
}

export type ProjectControllerCountReleasedProjectsResponse =
  ProjectControllerCountReleasedProjectsResponses[keyof ProjectControllerCountReleasedProjectsResponses];

export interface ProjectControllerGetReleaseData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}';
}

export interface ProjectControllerGetReleaseResponses {
  /**
   * Project release metadata
   */
  200: ProjectExResponseDto;
}

export type ProjectControllerGetReleaseResponse =
  ProjectControllerGetReleaseResponses[keyof ProjectControllerGetReleaseResponses];

export interface ProjectControllerGetReleaseContentData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/content';
}

export interface ProjectControllerGetReleaseContentResponses {
  /**
   * Project release file
   */
  200: Blob | File;
}

export type ProjectControllerGetReleaseContentResponse =
  ProjectControllerGetReleaseContentResponses[keyof ProjectControllerGetReleaseContentResponses];

export interface ProjectControllerGetReleaseContentUrlData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/content-url';
}

export interface ProjectControllerGetReleaseContentUrlResponses {
  /**
   * Signed Edge URL for the release
   */
  200: SignedUrlResponseDto;
}

export type ProjectControllerGetReleaseContentUrlResponse =
  ProjectControllerGetReleaseContentUrlResponses[keyof ProjectControllerGetReleaseContentUrlResponses];

export interface ProjectControllerFindAllData {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/projects';
}

export interface ProjectControllerFindAllErrors {
  /**
   * Internal server error
   */
  500: unknown;
}

export interface ProjectControllerFindAllResponses {
  /**
   * A paginated list of projects with collaborators and creator information
   */
  200: PaginatedProjectsResponseDto;
}

export type ProjectControllerFindAllResponse =
  ProjectControllerFindAllResponses[keyof ProjectControllerFindAllResponses];

export interface ProjectControllerCreateData {
  body: CreateProjectDto;
  path?: never;
  query?: never;
  url: '/projects';
}

export interface ProjectControllerCreateErrors {
  /**
   * Bad request – invalid input
   */
  400: unknown;
}

export interface ProjectControllerCreateResponses {
  /**
   * Project created successfully
   */
  201: ProjectResponseDto;
}

export type ProjectControllerCreateResponse =
  ProjectControllerCreateResponses[keyof ProjectControllerCreateResponses];

export interface ProjectControllerCountProjectsData {
  body?: never;
  path?: never;
  query?: {
    search?: string;
    /**
     * Comma-separated tag list
     */
    tags?: string;
    status?: 'all' | 'drafts' | 'published';
  };
  url: '/projects/count';
}

export interface ProjectControllerCountProjectsResponses {
  /**
   * The total number of user projects matching the request
   */
  200: ProjectsCountResponseDto;
}

export type ProjectControllerCountProjectsResponse =
  ProjectControllerCountProjectsResponses[keyof ProjectControllerCountProjectsResponses];

export interface ProjectControllerRemoveData {
  body?: never;
  path: {
    /**
     * Numeric ID of the project to delete
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}';
}

export interface ProjectControllerRemoveErrors {
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Error deleting project
   */
  500: unknown;
}

export interface ProjectControllerRemoveResponses {
  /**
   * Project deleted successfully (no content)
   */
  204: void;
}

export type ProjectControllerRemoveResponse =
  ProjectControllerRemoveResponses[keyof ProjectControllerRemoveResponses];

export interface ProjectControllerFindOneData {
  body?: never;
  path: {
    /**
     * Numeric ID of the project to retrieve
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}';
}

export interface ProjectControllerFindOneErrors {
  /**
   * Invalid user or project ID
   */
  403: unknown;
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Internal server error
   */
  500: unknown;
}

export interface ProjectControllerFindOneResponses {
  /**
   * Project object
   */
  200: ProjectResponseDto;
}

export type ProjectControllerFindOneResponse =
  ProjectControllerFindOneResponses[keyof ProjectControllerFindOneResponses];

export interface ProjectControllerUpdateData {
  body: UpdateProjectDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}';
}

export interface ProjectControllerUpdateErrors {
  /**
   * Project not found
   */
  404: unknown;
  /**
   * Error updating project
   */
  500: unknown;
}

export interface ProjectControllerUpdateResponses {
  /**
   * Updated project object
   */
  200: ProjectResponseDto;
}

export type ProjectControllerUpdateResponse =
  ProjectControllerUpdateResponses[keyof ProjectControllerUpdateResponses];

export interface ProjectControllerForkData {
  body?: never;
  path: {
    /**
     * Numeric ID of the published project to fork
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}/fork';
}

export interface ProjectControllerForkErrors {
  /**
   * Project is not published
   */
  400: unknown;
  /**
   * Project not found
   */
  404: unknown;
}

export interface ProjectControllerForkResponses {
  /**
   * Forked project created successfully
   */
  201: ForkProjectResponseDto;
}

export type ProjectControllerForkResponse =
  ProjectControllerForkResponses[keyof ProjectControllerForkResponses];

export interface ProjectControllerAddCollaboratorData {
  body: AddCollaboratorDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}/add-collaborator';
}

export interface ProjectControllerAddCollaboratorErrors {
  /**
   * Bad request - no valid identifier provided
   */
  400: unknown;
  /**
   * Project or user not found
   */
  404: unknown;
  /**
   * Error Patching project
   */
  500: unknown;
}

export interface ProjectControllerAddCollaboratorResponses {
  /**
   * Updated project object with collaborators
   */
  200: ProjectExResponseDto;
}

export type ProjectControllerAddCollaboratorResponse =
  ProjectControllerAddCollaboratorResponses[keyof ProjectControllerAddCollaboratorResponses];

export interface ProjectControllerRemoveCollaboratorData {
  body: RemoveCollaboratorDto;
  path: {
    /**
     * Numeric ID of the project to update
     */
    id: number;
  };
  query?: never;
  url: '/projects/{id}/remove-collaborator';
}

export interface ProjectControllerRemoveCollaboratorErrors {
  /**
   * Bad request - no valid identifier provided
   */
  400: unknown;
  /**
   * Forbidden - cannot remove project creator
   */
  403: unknown;
  /**
   * Project or user not found
   */
  404: unknown;
  /**
   * Error remove collaborator on project
   */
  500: unknown;
}

export interface ProjectControllerRemoveCollaboratorResponses {
  /**
   * Updated project object with collaborators
   */
  200: ProjectExResponseDto;
}

export type ProjectControllerRemoveCollaboratorResponse =
  ProjectControllerRemoveCollaboratorResponses[keyof ProjectControllerRemoveCollaboratorResponses];

export interface ProjectControllerSaveProjectContentData {
  body: {
    /**
     * Project file (zip, pdf, png, etc.)
     */
    file?: Blob | File;
  };
  path: {
    id: number;
  };
  query?: never;
  url: '/projects/{id}/saveContent';
}

export interface ProjectControllerSaveProjectContentErrors {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * File validation failed
   */
  422: unknown;
}

export interface ProjectControllerSaveProjectContentResponses {
  /**
   * File uploaded successfully
   */
  201: unknown;
}

export interface ProjectControllerGetProjectImageData {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/projects/{id}/image';
}

export interface ProjectControllerGetProjectImageErrors {
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerGetProjectImageResponses {
  /**
   * CDN URL for the project image
   */
  200: ImageUrlResponseDto;
  /**
   * Project has no image
   */
  204: void;
}

export type ProjectControllerGetProjectImageResponse =
  ProjectControllerGetProjectImageResponses[keyof ProjectControllerGetProjectImageResponses];

export interface ProjectControllerUploadProjectImageData {
  body: {
    /**
     * Project image file (JPEG, PNG, GIF, WebP)
     */
    file?: Blob | File;
  };
  path: {
    id: number;
  };
  query?: never;
  url: '/projects/{id}/image';
}

export interface ProjectControllerUploadProjectImageErrors {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Invalid file type or size
   */
  422: unknown;
}

export interface ProjectControllerUploadProjectImageResponses {
  /**
   * Image uploaded successfully
   */
  201: unknown;
}

export interface ProjectControllerGetPublishedProjectImageData {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/projects/public/{id}/image';
}

export interface ProjectControllerGetPublishedProjectImageErrors {
  /**
   * Project not found, not published, or has no image
   */
  404: unknown;
}

export interface ProjectControllerGetPublishedProjectImageResponses {
  /**
   * Returns the CDN URL for the project image
   */
  200: ImageUrlResponseDto;
}

export type ProjectControllerGetPublishedProjectImageResponse =
  ProjectControllerGetPublishedProjectImageResponses[keyof ProjectControllerGetPublishedProjectImageResponses];

export interface ProjectControllerFetchProjectContentData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/fetchContent';
}

export interface ProjectControllerFetchProjectContentErrors {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * File not found
   */
  404: unknown;
}

export interface ProjectControllerFetchProjectContentResponses {
  /**
   * File fetched successfully
   */
  200: Blob | File;
}

export type ProjectControllerFetchProjectContentResponse =
  ProjectControllerFetchProjectContentResponses[keyof ProjectControllerFetchProjectContentResponses];

export interface ProjectControllerSaveCheckpointData {
  body: {
    file?: Blob | File;
  };
  path: {
    id: string;
    name: string;
  };
  query?: never;
  url: '/projects/{id}/saveCheckpoint/{name}';
}

export interface ProjectControllerSaveCheckpointErrors {
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerSaveCheckpointResponses {
  /**
   * File uploaded successfully
   */
  201: unknown;
}

export interface ProjectControllerDeleteCheckpointData {
  body?: never;
  path: {
    id: string;
    name: string;
  };
  query?: never;
  url: '/projects/{id}/deleteCheckpoint/{name}';
}

export interface ProjectControllerDeleteCheckpointErrors {
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerDeleteCheckpointResponses {
  /**
   * File deleted successfully
   */
  201: unknown;
}

export interface ProjectControllerPublishData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/publish';
}

export interface ProjectControllerPublishErrors {
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerPublishResponses {
  /**
   * Project published successfully
   */
  201: unknown;
}

export interface ProjectControllerUnpublishData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/unpublish';
}

export interface ProjectControllerUnpublishErrors {
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerUnpublishResponses {
  /**
   * Project unpublished successfully
   */
  201: unknown;
}

export interface ProjectControllerGetVersionsData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/versions';
}

export interface ProjectControllerGetVersionsErrors {
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerGetVersionsResponses {
  /**
   * Project versions retrieved successfully
   */
  200: unknown;
}

export interface ProjectControllerGetCheckpointsData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/checkpoints';
}

export interface ProjectControllerGetCheckpointsErrors {
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerGetCheckpointsResponses {
  /**
   * Project checkpoints retrieved successfully
   */
  200: unknown;
}

export interface ProjectControllerGetVersionData {
  body?: never;
  path: {
    id: string;
    version: string;
  };
  query?: never;
  url: '/projects/{id}/versions/{version}';
}

export interface ProjectControllerGetVersionErrors {
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerGetVersionResponses {
  /**
   * Project version retrieved successfully
   */
  200: Blob | File;
}

export type ProjectControllerGetVersionResponse =
  ProjectControllerGetVersionResponses[keyof ProjectControllerGetVersionResponses];

export interface ProjectControllerGetCheckpointData {
  body?: never;
  path: {
    id: string;
    checkpoint: string;
  };
  query?: never;
  url: '/projects/{id}/checkpoints/{checkpoint}';
}

export interface ProjectControllerGetCheckpointErrors {
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerGetCheckpointResponses {
  /**
   * Project checkpoint retrieved successfully
   */
  200: Blob | File;
}

export type ProjectControllerGetCheckpointResponse =
  ProjectControllerGetCheckpointResponses[keyof ProjectControllerGetCheckpointResponses];

export interface ProjectControllerUnlikeProjectData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/like';
}

export interface ProjectControllerUnlikeProjectResponses {
  /**
   * Like removed
   */
  200: LikeResponseDto;
}

export type ProjectControllerUnlikeProjectResponse =
  ProjectControllerUnlikeProjectResponses[keyof ProjectControllerUnlikeProjectResponses];

export interface ProjectControllerLikeProjectData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/like';
}

export interface ProjectControllerLikeProjectResponses {
  /**
   * Like status
   */
  200: LikeResponseDto;
}

export type ProjectControllerLikeProjectResponse =
  ProjectControllerLikeProjectResponses[keyof ProjectControllerLikeProjectResponses];

export interface ProjectControllerGetLikeStatusData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/like-status';
}

export interface ProjectControllerGetLikeStatusResponses {
  /**
   * Like status
   */
  200: LikeResponseDto;
}

export type ProjectControllerGetLikeStatusResponse =
  ProjectControllerGetLikeStatusResponses[keyof ProjectControllerGetLikeStatusResponses];

export interface ProjectControllerRegisterReleaseViewData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/releases/{id}/view';
}

export interface ProjectControllerRegisterReleaseViewResponses {
  /**
   * Updated view count
   */
  200: ViewResponseDto;
}

export type ProjectControllerRegisterReleaseViewResponse =
  ProjectControllerRegisterReleaseViewResponses[keyof ProjectControllerRegisterReleaseViewResponses];

export interface ProjectControllerUpdateReleaseData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/projects/{id}/update-release';
}

export interface ProjectControllerUpdateReleaseErrors {
  /**
   * Project is not published
   */
  400: unknown;
  /**
   * Forbidden
   */
  403: unknown;
}

export interface ProjectControllerUpdateReleaseResponses {
  /**
   * Release updated successfully
   */
  200: unknown;
}

export interface MultiplayerControllerListData {
  body?: never;
  path?: never;
  query: {
    projectId: number;
  };
  url: '/game-sessions';
}

export interface MultiplayerControllerListResponses {
  200: GameSessionListResponseDto;
}

export type MultiplayerControllerListResponse =
  MultiplayerControllerListResponses[keyof MultiplayerControllerListResponses];

export interface MultiplayerControllerCreateData {
  body: CreateGameSessionDto;
  path?: never;
  query?: never;
  url: '/game-sessions';
}

export interface MultiplayerControllerCreateResponses {
  201: GameSessionConnectionResponseDto;
}

export type MultiplayerControllerCreateResponse =
  MultiplayerControllerCreateResponses[keyof MultiplayerControllerCreateResponses];

export interface MultiplayerControllerJoinByCodeData {
  body: JoinByCodeDto;
  path?: never;
  query?: never;
  url: '/game-sessions/join-by-code';
}

export interface MultiplayerControllerJoinByCodeResponses {
  200: GameSessionConnectionResponseDto;
}

export type MultiplayerControllerJoinByCodeResponse =
  MultiplayerControllerJoinByCodeResponses[keyof MultiplayerControllerJoinByCodeResponses];

export interface MultiplayerControllerRemoveData {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}';
}

export interface MultiplayerControllerRemoveResponses {
  200: unknown;
}

export interface MultiplayerControllerGetData {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}';
}

export interface MultiplayerControllerGetResponses {
  200: GameSessionResponseDto;
}

export type MultiplayerControllerGetResponse =
  MultiplayerControllerGetResponses[keyof MultiplayerControllerGetResponses];

export interface MultiplayerControllerUpdateData {
  body: UpdateGameSessionDto;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}';
}

export interface MultiplayerControllerUpdateResponses {
  200: unknown;
}

export interface MultiplayerControllerJoinData {
  body: JoinGameSessionDto;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}/join';
}

export interface MultiplayerControllerJoinResponses {
  200: GameSessionConnectionResponseDto;
}

export type MultiplayerControllerJoinResponse =
  MultiplayerControllerJoinResponses[keyof MultiplayerControllerJoinResponses];

export interface MultiplayerControllerLeaveData {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}/leave';
}

export interface MultiplayerControllerLeaveResponses {
  200: unknown;
}

export interface MultiplayerControllerRefreshTicketData {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/game-sessions/{sessionId}/ticket';
}

export interface MultiplayerControllerRefreshTicketResponses {
  200: GameSessionConnectionResponseDto;
}

export type MultiplayerControllerRefreshTicketResponse =
  MultiplayerControllerRefreshTicketResponses[keyof MultiplayerControllerRefreshTicketResponses];

export interface ProjectCommentControllerGetCommentsData {
  body?: never;
  path: {
    projectId: number;
  };
  query?: {
    page?: number;
    limit?: number;
    sort?: 'newest' | 'oldest';
  };
  url: '/projects/{projectId}/comments';
}

export interface ProjectCommentControllerGetCommentsResponses {
  /**
   * Paginated list of comments
   */
  200: PaginatedCommentsResponseDto;
}

export type ProjectCommentControllerGetCommentsResponse =
  ProjectCommentControllerGetCommentsResponses[keyof ProjectCommentControllerGetCommentsResponses];

export interface ProjectCommentControllerCreateCommentData {
  body: CreateCommentDto;
  path: {
    projectId: number;
  };
  query?: never;
  url: '/projects/{projectId}/comments';
}

export interface ProjectCommentControllerCreateCommentResponses {
  /**
   * Comment created
   */
  201: CommentResponseDto;
}

export type ProjectCommentControllerCreateCommentResponse =
  ProjectCommentControllerCreateCommentResponses[keyof ProjectCommentControllerCreateCommentResponses];

export interface ProjectCommentControllerCreateReplyData {
  body: CreateCommentDto;
  path: {
    projectId: number;
    commentId: number;
  };
  query?: never;
  url: '/projects/{projectId}/comments/{commentId}/reply';
}

export interface ProjectCommentControllerCreateReplyResponses {
  /**
   * Reply created
   */
  201: CommentResponseDto;
}

export type ProjectCommentControllerCreateReplyResponse =
  ProjectCommentControllerCreateReplyResponses[keyof ProjectCommentControllerCreateReplyResponses];

export interface ProjectCommentControllerDeleteCommentData {
  body?: never;
  path: {
    projectId: number;
    commentId: number;
  };
  query?: never;
  url: '/projects/{projectId}/comments/{commentId}';
}

export interface ProjectCommentControllerDeleteCommentResponses {
  /**
   * Comment deleted
   */
  204: void;
}

export type ProjectCommentControllerDeleteCommentResponse =
  ProjectCommentControllerDeleteCommentResponses[keyof ProjectCommentControllerDeleteCommentResponses];

export interface ProjectCommentControllerUpdateCommentData {
  body: CreateCommentDto;
  path: {
    commentId: number;
    projectId: number;
  };
  query?: never;
  url: '/projects/{projectId}/comments/{commentId}';
}

export interface ProjectCommentControllerUpdateCommentResponses {
  /**
   * Comment updated
   */
  200: CommentResponseDto;
}

export type ProjectCommentControllerUpdateCommentResponse =
  ProjectCommentControllerUpdateCommentResponses[keyof ProjectCommentControllerUpdateCommentResponses];

export interface NotificationsControllerGetWebRtcOfferData {
  body?: never;
  path?: never;
  query?: never;
  url: '/notifications/webrtc-offer';
}

export interface NotificationsControllerGetWebRtcOfferResponses {
  /**
   * Notification websocket configuration
   */
  200: unknown;
}

export interface NotificationsControllerSendTestNotificationData {
  body: NotificationTestDto;
  path?: never;
  query?: never;
  url: '/notifications/test';
}

export interface NotificationsControllerSendTestNotificationResponses {
  /**
   * Notification created and sent
   */
  200: unknown;
}

export interface NotificationsControllerMarkAsReadData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/notifications/{id}/read';
}

export interface NotificationsControllerMarkAsReadResponses {
  /**
   * Notification marked as read
   */
  200: unknown;
}

export interface AuthControllerLoginData {
  body: LoginDto;
  path?: never;
  query?: never;
  url: '/auth/login';
}

export interface AuthControllerLoginErrors {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Invalid credentials
   */
  401: unknown;
}

export interface AuthControllerLoginResponses {
  /**
   * User logged in successfully
   */
  201: {
    access_token: string;
  };
}

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export interface AuthControllerRegisterData {
  body: CreateUserDto;
  path?: never;
  query?: never;
  url: '/auth/register';
}

export interface AuthControllerRegisterErrors {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Cannot register as an admin
   */
  403: unknown;
  /**
   * Email already in use
   */
  409: unknown;
}

export interface AuthControllerRegisterResponses {
  /**
   * User registered successfully
   */
  201: {
    access_token: string;
  };
}

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export interface AuthControllerLoginWithGoogleCodeData {
  body: GoogleCodeDto;
  path?: never;
  query?: never;
  url: '/auth/google/code';
}

export interface AuthControllerLoginWithGoogleCodeErrors {
  /**
   * Invalid Google code or code_verifier
   */
  401: unknown;
}

export interface AuthControllerLoginWithGoogleCodeResponses {
  /**
   * Login successful with Google
   */
  201: {
    access_token: string;
  };
}

export type AuthControllerLoginWithGoogleCodeResponse =
  AuthControllerLoginWithGoogleCodeResponses[keyof AuthControllerLoginWithGoogleCodeResponses];

export interface AuthControllerLoginWithGithubData {
  body: GithubLoginDto;
  path?: never;
  query?: never;
  url: '/auth/github';
}

export interface AuthControllerLoginWithGithubErrors {
  /**
   * Invalid or expired GitHub code
   */
  401: unknown;
}

export interface AuthControllerLoginWithGithubResponses {
  /**
   * Login successful with GitHub
   */
  201: {
    access_token: string;
  };
}

export type AuthControllerLoginWithGithubResponse =
  AuthControllerLoginWithGithubResponses[keyof AuthControllerLoginWithGithubResponses];

export interface AuthControllerLoginWithMicrosoftData {
  body: MicrosoftLoginDto;
  path?: never;
  query?: never;
  url: '/auth/microsoft';
}

export interface AuthControllerLoginWithMicrosoftErrors {
  /**
   * Invalid Microsoft ID token
   */
  401: unknown;
}

export interface AuthControllerLoginWithMicrosoftResponses {
  /**
   * Login successful with Microsoft
   */
  201: {
    access_token: string;
  };
}

export type AuthControllerLoginWithMicrosoftResponse =
  AuthControllerLoginWithMicrosoftResponses[keyof AuthControllerLoginWithMicrosoftResponses];

export interface AuthControllerRefreshData {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/refresh';
}

export interface AuthControllerRefreshErrors {
  /**
   * Refresh token missing or invalid
   */
  401: unknown;
}

export interface AuthControllerRefreshResponses {
  /**
   * Access token refreshed successfully
   */
  201: {
    access_token: string;
  };
}

export type AuthControllerRefreshResponse =
  AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export interface AuthControllerChangePasswordData {
  body: ChangePasswordDto;
  path?: never;
  query?: never;
  url: '/auth/password';
}

export interface AuthControllerChangePasswordErrors {
  /**
   * Current password required for non-OAuth accounts
   */
  400: unknown;
  /**
   * Current password incorrect
   */
  401: unknown;
}

export interface AuthControllerChangePasswordResponses {
  /**
   * Password updated successfully
   */
  200: unknown;
}

export interface AuthControllerLogoutData {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout';
}

export interface AuthControllerLogoutResponses {
  /**
   * Logout successful
   */
  200: unknown;
}

export interface UserControllerGetProfileData {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/profile';
}

export interface UserControllerGetProfileErrors {
  /**
   * Unauthorized
   */
  401: unknown;
}

export interface UserControllerGetProfileResponses {
  /**
   * Returns the current user profile
   */
  200: UserProfileResponseDto;
}

export type UserControllerGetProfileResponse =
  UserControllerGetProfileResponses[keyof UserControllerGetProfileResponses];

export interface UserControllerUpdateMyProfileData {
  body: UpdateUserProfileDto;
  path?: never;
  query?: never;
  url: '/users/profile';
}

export interface UserControllerUpdateMyProfileErrors {
  /**
   * Unauthorized
   */
  401: unknown;
}

export interface UserControllerUpdateMyProfileResponses {
  /**
   * User profile updated successfully
   */
  200: PublicUserProfileResponseDto;
}

export type UserControllerUpdateMyProfileResponse =
  UserControllerUpdateMyProfileResponses[keyof UserControllerUpdateMyProfileResponses];

export interface UserControllerGetProfilePictureData {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/profile-picture';
}

export interface UserControllerGetProfilePictureErrors {
  /**
   * Not found
   */
  404: unknown;
}

export interface UserControllerGetProfilePictureResponses {
  /**
   * Signed cookies and CDN resource URL
   */
  200: SignedCdnResourceDto;
}

export type UserControllerGetProfilePictureResponse =
  UserControllerGetProfilePictureResponses[keyof UserControllerGetProfilePictureResponses];

export interface UserControllerUploadProfilePictureData {
  body: {
    /**
     * Profile picture file
     */
    file?: Blob | File;
  };
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/profile-picture';
}

export interface UserControllerUploadProfilePictureErrors {
  /**
   * Unauthorized
   */
  401: unknown;
}

export interface UserControllerUploadProfilePictureResponses {
  /**
   * Profile uploaded
   */
  201: unknown;
}

export interface UserControllerUploadProfileBackgroundData {
  body: {
    /**
     * Profile background file
     */
    file?: Blob | File;
  };
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}/profile-background';
}

export interface UserControllerUploadProfileBackgroundErrors {
  /**
   * Unauthorized
   */
  401: unknown;
}

export interface UserControllerUploadProfileBackgroundResponses {
  /**
   * Profile background uploaded
   */
  201: unknown;
}

export interface UserControllerFindAllData {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Filter by nickname
     */
    nickname?: string;
    /**
     * Filter by email
     */
    email?: string;
    /**
     * Sort by field
     */
    sortBy?: 'id' | 'username' | 'email' | 'createdAt';
    /**
     * Sort order
     */
    order?: 'asc' | 'desc';
  };
  url: '/users';
}

export interface UserControllerFindAllErrors {
  /**
   * Unauthorized
   */
  401: unknown;
}

export interface UserControllerFindAllResponses {
  /**
   * Returns paginated list of users
   */
  200: UserListResponseDto;
}

export type UserControllerFindAllResponse =
  UserControllerFindAllResponses[keyof UserControllerFindAllResponses];

export interface UserControllerRemoveData {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}';
}

export interface UserControllerRemoveErrors {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Insufficient permissions
   */
  403: unknown;
  /**
   * User not found
   */
  404: unknown;
}

export interface UserControllerRemoveResponses {
  /**
   * User deleted successfully
   */
  200: {
    statusCode?: number;
    message?: string;
  };
}

export type UserControllerRemoveResponse =
  UserControllerRemoveResponses[keyof UserControllerRemoveResponses];

export interface UserControllerFindOneData {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}';
}

export interface UserControllerFindOneErrors {
  /**
   * Invalid ID format
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
}

export interface UserControllerFindOneResponses {
  /**
   * Returns the user
   */
  200: UserSingleResponseDto;
}

export type UserControllerFindOneResponse =
  UserControllerFindOneResponses[keyof UserControllerFindOneResponses];

export interface UserControllerUpdateData {
  body: UpdateUserDto;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/{id}';
}

export interface UserControllerUpdateErrors {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Insufficient permissions
   */
  403: unknown;
  /**
   * User not found
   */
  404: unknown;
}

export interface UserControllerUpdateResponses {
  /**
   * User updated successfully
   */
  200: UserSingleResponseDto;
}

export type UserControllerUpdateResponse =
  UserControllerUpdateResponses[keyof UserControllerUpdateResponses];

export interface UserPublicControllerGetPublicProfileData {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: never;
  url: '/users/public/{id}/profile';
}

export interface UserPublicControllerGetPublicProfileErrors {
  /**
   * User not found
   */
  404: unknown;
}

export interface UserPublicControllerGetPublicProfileResponses {
  /**
   * Returns the public user profile
   */
  200: PublicUserProfileResponseDto;
}

export type UserPublicControllerGetPublicProfileResponse =
  UserPublicControllerGetPublicProfileResponses[keyof UserPublicControllerGetPublicProfileResponses];

export interface UserPublicControllerGetPublicProfileByUsernameData {
  body?: never;
  path: {
    /**
     * Username
     */
    username: string;
  };
  query?: never;
  url: '/users/public/username/{username}/profile';
}

export interface UserPublicControllerGetPublicProfileByUsernameErrors {
  /**
   * User not found
   */
  404: unknown;
}

export interface UserPublicControllerGetPublicProfileByUsernameResponses {
  /**
   * Returns the public user profile
   */
  200: PublicUserProfileResponseDto;
}

export type UserPublicControllerGetPublicProfileByUsernameResponse =
  UserPublicControllerGetPublicProfileByUsernameResponses[keyof UserPublicControllerGetPublicProfileByUsernameResponses];

export interface UserPublicControllerGetLikedGamesData {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/users/public/{id}/likes';
}

export interface UserPublicControllerGetLikedGamesResponses {
  /**
   * Returns the list of published games liked by the user
   */
  200: ProjectExResponseDto[];
}

export type UserPublicControllerGetLikedGamesResponse =
  UserPublicControllerGetLikedGamesResponses[keyof UserPublicControllerGetLikedGamesResponses];

export interface UserPublicControllerGetPublishedGamesData {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: number;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/users/public/{id}/published-games';
}

export interface UserPublicControllerGetPublishedGamesResponses {
  /**
   * Returns the list of games published by the user
   */
  200: ProjectExResponseDto[];
}

export type UserPublicControllerGetPublishedGamesResponse =
  UserPublicControllerGetPublishedGamesResponses[keyof UserPublicControllerGetPublishedGamesResponses];

export interface WorkSessionControllerJoinData {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/work-sessions/join/{id}';
}

export interface WorkSessionControllerJoinErrors {
  /**
   * Bad request.
   */
  400: unknown;
}

export interface WorkSessionControllerJoinResponses {
  /**
   * The work session has been successfully created.
   */
  201: JoinWorkSessionDto;
}

export type WorkSessionControllerJoinResponse =
  WorkSessionControllerJoinResponses[keyof WorkSessionControllerJoinResponses];

export interface WorkSessionControllerLeaveData {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/work-sessions/leave/{id}';
}

export interface WorkSessionControllerLeaveErrors {
  /**
   * Bad request.
   */
  400: unknown;
}

export interface WorkSessionControllerLeaveResponses {
  /**
   * Successfully left the work session.
   */
  204: void;
}

export type WorkSessionControllerLeaveResponse =
  WorkSessionControllerLeaveResponses[keyof WorkSessionControllerLeaveResponses];

export interface WorkSessionControllerKickData {
  body: KickWorkSessionDto;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/work-sessions/kick/{id}';
}

export interface WorkSessionControllerKickErrors {
  /**
   * Bad request.
   */
  400: unknown;
}

export interface WorkSessionControllerKickResponses {
  /**
   * Successfully left the work session.
   */
  204: void;
}

export type WorkSessionControllerKickResponse =
  WorkSessionControllerKickResponses[keyof WorkSessionControllerKickResponses];

export interface WorkSessionControllerGetInfoData {
  body?: never;
  path: {
    /**
     * Project ID
     */
    id: number;
  };
  query?: never;
  url: '/work-sessions/info/{id}';
}

export interface WorkSessionControllerGetInfoErrors {
  /**
   * Work session not found.
   */
  404: unknown;
}

export interface WorkSessionControllerGetInfoResponses {
  /**
   * Work session info retrieved successfully.
   */
  200: FetchWorkSessionDto;
}

export type WorkSessionControllerGetInfoResponse =
  WorkSessionControllerGetInfoResponses[keyof WorkSessionControllerGetInfoResponses];
