// Generates packages/ui/src/icons/paths.ts from pixelarticons (MIT) for the icon subset in tools/icons.json.
// Run: node tools/build-icons.mjs
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';

const require = createRequire(import.meta.url);
const root = resolve(import.meta.dirname, '..');
const aliases = JSON.parse(await readFile(resolve(root, 'tools/icons.json'), 'utf8'));
const svgDir = dirname(require.resolve('pixelarticons/package.json')) + '/svg';

/**
 * Glyphs taken from the design rather than from pixelarticons, on the same 24-grid.
 * `overrides` names every one of them that intentionally shadows an `icons.json` entry of the
 * same name; a glyph on both sides that is not listed there is caught below, since otherwise
 * editing `icons.json` for one of these silently does nothing and nothing says so.
 */
const { glyphs: CUSTOM, overrides } = JSON.parse(
  await readFile(resolve(root, 'tools/icons-custom.json'), 'utf8'),
);
const overrideSet = new Set(overrides);
for (const name of Object.keys(CUSTOM)) {
  if (Object.hasOwn(aliases, name) && !overrideSet.has(name)) {
    throw new Error(
      `build-icons: '${name}' is defined in both icons.json and tools/icons-custom.json but is ` +
        `not in its "overrides" list — add it there if the shadowing is deliberate, or remove ` +
        'the duplicate.',
    );
  }
}
for (const name of overrides) {
  if (!Object.hasOwn(aliases, name)) {
    console.warn(
      `build-icons: '${name}' is in icons-custom.json's "overrides" but icons.json has no such entry to override`,
    );
  }
}

const byName = new Map();
for (const [name, file] of Object.entries(aliases)) {
  const svg = await readFile(`${svgDir}/${file}.svg`, 'utf8');
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) {
    throw new Error(`${name}: no <path d> found`);
  }
  byName.set(name, paths.join(' '));
}
// Last, so a design glyph replaces the pixelarticons one of the same name rather than colliding
// with it.
for (const [name, glyph] of Object.entries(CUSTOM)) {
  byName.set(name, glyph.d);
}

const entries = [...byName].map(([name, d]) => `  '${name}': '${d}',`);
entries.sort();

const out = `// GENERATED by tools/build-icons.mjs from pixelarticons ${require('pixelarticons/package.json').version} (MIT). Do not edit.
export const ICON_PATHS = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;
const target = resolve(root, 'packages/ui/src/icons/paths.ts');

// --check fails when the committed paths drift from the generator, which nothing else would notice.
if (process.argv.includes('--check')) {
  // Compared as name -> path, not byte for byte: the committed file is Prettier's, which wraps the
  // long paths onto their own line, so the generator's own text never matches it verbatim.
  const current = await readFile(target, 'utf8').catch(() => '');
  const found = new Map();
  for (const m of current.matchAll(/'?([a-zA-Z0-9-]+)'?:\s*\n?\s*'([^']+)'/g)) {
    found.set(m[1], m[2]);
  }

  const drift = [];
  for (const [name, d] of byName) {
    if (!found.has(name)) {
      drift.push(`missing: ${name}`);
    } else if (found.get(name) !== d) {
      drift.push(`different picture: ${name}`);
    }
  }
  for (const name of found.keys()) {
    if (!byName.has(name)) {
      drift.push(`unexpected: ${name}`);
    }
  }

  if (drift.length > 0) {
    console.error(
      `build-icons: packages/ui/src/icons/paths.ts disagrees with the generator ` +
        `(${String(drift.length)}):\n  ${drift.join('\n  ')}\n` +
        'Run `node tools/build-icons.mjs`, then Prettier, and commit the result.',
    );
    process.exit(1);
  }
  console.warn(`build-icons: paths.ts matches the generator (${byName.size} icons)`);
} else {
  await writeFile(target, out);
  console.warn(`build-icons: wrote ${entries.length} icons`);
}
