#!/bin/sh

npm run lint -- --fix

if [ $? -ne 0 ]; then
  echo "❌ Linting failed. Please fix the errors before committing."
  exit 1
fi

npx jest
if [ $? -ne 0 ]; then
  echo "❌ Jest tests failed. Please fix the errors before committing."
  exit 1
fi

# npm cypress:run
# if [ $? -ne 0 ]; then
#   echo "❌ Cypress tests failed. Please fix the errors before committing."
#   exit 1
# fi

echo "✅ Linting passed successfully."
